var c=false,e=window,g=document;function j(a,b){return a.innerHTML=b}function k(a,b){return a.className=b}function l(a,b){return a.parseError=b}var m="appendChild",n="createElement",o="addEventListener",p="childNodes",q="length",s="close",t="body";function u(a,b,d){var f=new XMLHttpRequest;f.open("GET",a,c);f.onreadystatechange=function(){if(f.readyState==4&&f.status==200)b(f.responseText);else d&&d()};f.send()};/*
 Copyright 2009 Google Inc.  All Rights Reserved.
 Your use of this software is subject to the Terms of Service located
 at https://chrome.google.com/extensions/intl/en/gallery_tos.html.
*/
var v=null,w=0;chrome.extension.getURL("images/button_x.png");
var x=/(chrome|https?:\/\/chrome\.google\.com\/extensions)/,y=function(a){this.d=this.c=this.url=this.a=this.title="";var b=a[p][0];this.a=b.attributes.href.value;var d=/url\?q\=(.*)\&sa/.exec(this.a);if(d[q]>1)this.url=d[1];this.title=b.innerHTML;b=a[p][1];if(b[p][q]>0)this.c=b[p][0].src;this.d=a[p][2].innerHTML},z=function(a){this.b=[];this.e=[];l(this,c);var b=g[n]("div");j(b,a);if(b[p][q]>0){a=b[p][0];if(a.nodeName!="DIV")l(this,true);for(a=a.firstChild;a&&!this.parseError;a=a.nextSibling)if(a.nodeName==
"DIV")if(a[p][q]==3){b=new y(a);b.a!=""&&b.url!=""&&this.b.push(b)}else l(this,true)}else l(this,true)},B=function(a,b){b?u(b+"search?esrch=BR&tbs=prv:1&q=related:"+a,A):console.log("No domain set")},A=function(a){v=new z(a);if(v.parseError){a=g[n]("div");k(a,"SP_ZeroResultsContainer");a[m](C());var b=g[n]("span");j(b,"Error talking to Google.");a[m](b);g[t][m](a)}else if(v.b[q]){a=g[n]("div");k(a,"SP_MainContainer");b=D();a[m](b);b=g[n]("div");b.id="sp_results";a[m](b);g[t][m](a);g[o]("keydown",
E,c);if(v.b[q]){a=g.getElementById("sp_results");b=v.b;var d=Math.min(b[q],4);for(w=0;w<d;w++){var f=F(b[w],w);a[m](f)}}}else G()},D=function(){var a=g[n]("div"),b=g[n]("img");b.id="sp_logo";b.src="http://www.google.com/images/logos/similar_pages_logo_sm.gif";a[m](b);a[m](C());return a},C=function(){var a=g[n]("img");a.id="sp_close_button";a.src="url("+chrome.extension.getURL("images/button_x.png")+")";a[o]("click",function(){e[s]()},c);return a},G=function(){var a=g[n]("div");k(a,"SP_ZeroResultsContainer");
a[m](C());var b=g[n]("span");j(b,"No similar pages found.");a[m](b);g[t][m](a)},H=function(a){var b=g[n]("div");k(b,"SP_SpecialCaseContainer");var d=D();b[m](d);d=g[n]("span");j(d,a);b[m](d);g[t][m](b)},F=function(a,b){var d=g[n]("div");d.id="page_"+b;k(d," SP_PageEntry ");var f="http://www.google.com"+a.a,h=g[n]("a");k(h,"SP_ImageAnchor");h.href=f;h.target="_blank";h[o]("click",function(){e[s]()},c);var i=g[n]("div");k(i,"SP_ImageWrapper");var r=g[n]("img");r.id="thumb_"+b;k(r,"SP_ImageThumb");I(r,
d.id);r.src=a.c;i[m](r);h[m](i);d[m](h);b=g[n]("div");k(b,"SP_PageEntryText");h=g[n]("div");h.style.width="800px";i=g[n]("a");i[o]("click",function(){e[s]()},c);i.target="_blank";j(i,a.title);i.href=f;i.title=a.title.replace("<b>","").replace("</b>","");h[m](i);b[m](h);f=g[n]("span");j(f,a.d);b[m](f);f=g[n]("div");f.style.width="800px";f.style.color="green";j(f,a.url);b[m](f);d[m](b);return d},I=function(a){var b=a.id;a[o]("error",function(){var d=g.getElementById(b),f=d.parentNode;f.className+=" SP_ImageNotFound ";
f.removeChild(d);d=g[n]("span");j(d,"Preview<br>not available");f[m](d)},c)},E=function(a){a.keyCode==27&&e[s]()};
(function(){chrome.tabs.getSelected(null,function(a){a=a.url;var b=localStorage.requestDomain;if(a.search(x)==0)H("This extension works best on homepages or the main page of most websites.<p>Try the extension on a website you already love&mdash;test drive it and see the page suggestions on something you know.");else if(b)b=="http://www.google.cn/"?H("The extension is currently not available for your country/region.  Please check back soon."):B(a,b);else G()})})();
