(function(){var b=devhd.pkg("pages");var d=devhd.log.get("page.explore");var e=devhd.i18n.L;b.ExplorePage=function(h){this.guid=h};var a=b.ExplorePage.prototype=new b.BasePage();a.service=function(i,h){this.pageInfo=i;this.width=h.width;this.categoryLabel="#home";this.initBase(h);this.startRenderHTML()};a.destroy=function(i,h){if(this.topArea!=null){this.topArea.destroy();
this.topArea=null}this.feeds=null;this.destroyBase()};a.allowsSideArea=function(){return false};a.allowsPageHeader=function(){return true};a.startRenderHTML=function(){this._cancelAllVisualFinders();this.state="loading";this.feeds=[];this.pending=0;this.complete=false;this.feedIds={};var i=this;var h=0;this.bundles.askStreamBundleDefinition(this.pageInfo.key,function(j){if(i.isDestroyed()){return
}f.call(i,j)},function(j){h++;c.call(i,j)},function(){if(i.isDestroyed()){return}if(i.feeds.length+i.pending==0){i.pageElem.innerHTML=templates.page.explore.notFound(i.pageInfo.key,i.home);return}i.complete=true},function(j,k){i.pageElem.innerHTML=templates.page.explore.notFound(i.pageInfo.key,i.home)})};function f(h){if(h==null){this.pageElem.innerHTML=e(e(272),this.pageInfo.key);
return}this.bundle=h;this.feedly.setPageTitle(templates.page.explore.title(h));this.feedly.clearNbrPages();this.feedly.selectTab(this.categoryLabel);this.feedly.pushContext({uri:this.pageInfo.uri,pageNumber:0,title:h.title,level:1,category:this.categoryLabel,subscriptions:[]});this.pageElem.innerHTML=templates.page.explore.layout(h)}function c(i){try{if(this.feedIds[i.id]!=null){return
}if(i.id.indexOf("?")>-1){return}this.feedIds[i.id]=true;i.subscribed=this.reader.lookupSubscription(i.id)!=null;var h=i.id;var j=this;this.pending++;this.reco.askFeedSnapshot(h,3,function(l){if(j.isDestroyed()){return}if(l==null||l.length==0||new Date().getTime()-j.reader.lookupEntry(l[0]).lastModifiedTime>devhd.utils.DurationUtils.DAYS(30)){}else{devhd.utils.HTMLUtils.append(j.element("contentArea"),templates.page.explore.feedArea(i,j.feeds.length%4));
i.title=devhd.utils.StringUtils.cleanSourceTitle(j.reader.lookupEntry(l[0]).getSourceTitle());j.element("feed_"+h+"_title").innerHTML=templates.page.explore.feedAreaTitle(i,j.home);j.displayEntries(h,l);j.feeds.push(i);if(j.feeds.length>0&&j.feeds.length%4==0){devhd.utils.HTMLUtils.append(j.element("contentArea"),"<div style='clear:both; padding-top:34px'></div>")
}}j.pending--},function(m,l){if(j.isDestroyed()){return}devhd.utils.HTMLUtils.remove(j.element(h+"_feed"));j.pending--})}catch(k){d.error(227,"failed to ask entries for ",i.id,k)}}a.displayEntries=function(k,s){try{var r=[];for(var o=0;o<s.length;o++){r.push(this.reader.lookupEntry(s[o]))}var t=this.element("main_"+k+"_headline");t.innerHTML=templates.page.base.displayRecommendations(r.slice(0,1),this.home);
this.askFindVisual(r[0],"U10");if(r.length>1){var m=[];for(var n=1;n<r.length&&n<3;n++){m.push({entry:r[n],type:15})}this.element("main_"+k+"_others").innerHTML=templates.page.base.parts(m,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home)}var p=this;this.reader.askFeedMetadata(k,function(i){if(p.isDestroyed()){return
}if(i==null){return}p.element("main_"+k+"_about").innerHTML=templates.page.explore.feedMeta(i)})}catch(q){var l=devhd.utils.ExceptionUtils.formatError("display articles",q);d.error(306,"failed to display articles ",q);var h=this.element("main_"+k+"_others");h.innerHTML=l}};a.onSubscriptionAddedToCategory=function(i,h,j){};a.buryFeed=function(h){var k=[];
for(var j=0;j<this.feeds.length;j++){if(this.feeds[j].id==h){continue}k.push(this.feeds[j])}this.feeds=k;this.effects.fade(this.element(h+"_feed"),{delay:0.8,from:1,to:0,onComplete:function(i){devhd.utils.HTMLUtils.remove(i)}},"feedly")};a.askSubscribeToAll=function(){this.dialog.show(templates.forms.newCategory(this.bundle.title.toLowerCase()),550);
var h=this;this.bind("create","click",function(){var i=h.element("categoryLabel").value;h.dialog.hide();h.doSubscribeToAll(i)});this.bind("cancel","click",function(){h.dialog.hide()})};a.doSubscribeToAll=function(j){if(j==null){j=this.bundle.title.toLowerCase()}var h=[];for(var k=0;k<this.feeds.length;k++){if(this.reader.lookupSubscription(this.feeds[k].id)!=null){continue
}h.push(this.feeds[k])}g.call(this,h,j,0)};function g(h,i,l){var k=this;if(h==null||h.length==null||l>=h.length){this.reader.syncSubscriptions(function(){k.signs.setMessage(e(261),1,false);k.home.getDocument().defaultView.setTimeout(function(){k.reader.reset();k.reco.reset();k.feedly.updateTabs();k.feedly.loadPage("category/"+i,{forceRecreate:true})
},1000)},true);return}var j=h[l];this.signs.setMessage(e(e(262),l+1,h.length,j.title),100,false);this.reader.askAddSubscription(j.id,j.title,[i],{favorite:false,seeded:true},function(){g.call(k,h,i,l+1)},true)}})();