(function(){var a=devhd.pkg("pages");var d=devhd.i18n.L;var c=devhd.log.get("page.list");a.ListPage=function(){};var e=a.ListPage.prototype=new a.BasePage();e.service=function(i,h){this.pageInfo=i;this.width=h.width;this.feedId=devhd.utils.FeedIdUtils.create(i.key);this.action=i.parameters.action;this.returnTo=i.parameters.returnTo;if(this.pageInfo.pageNumber<0){c.warn(30,"invalid page number: ",this.pageInfo.pageNumber,". Hint:",this.pageInfo.uri);
this.pageInfo.pageNumber=0}if(i.key!=null&&i.key.indexOf("state/com.google/broadcast")>0&&i.key.indexOf("state/com.google/broadcast-")==-1){this.feedly.selectTab("feedly.shared")}else{if(i.key!=null&&i.key.indexOf("feedly.")==0){this.feedly.selectTab(i.key)}else{if(this.pageInfo.label!=null){this.feedly.selectTab(this.pageInfo.label)}}}this.subscription=this.reader.lookupSubscription(this.feedId);
this.category=this.pageInfo.label;if(this.category==null&&this.subscription!=null){var g=devhd.utils.ContextStackUtils.find(this.feedly.getContextStack(),"category");if(g!=null){this.category=g}}this.broadcast=this.pageInfo.key.indexOf("state/com.google/broadcast")>-1;this.socialMix=this.pageInfo.key.indexOf("state/com.google/broadcast-")>-1;this.realtimeScrolling=true;
this.initBase(h);this.startRenderHTML()};e.destroy=function(h,g){if(this.topArea!=null){this.topArea.destroy()}this.destroyBase()};e.canEmbed=function(){return this.pageInfo.type=="category"&&this.category!=null&&this.category.length>0&&this.category.indexOf("feedly.")==-1&&this.category.indexOf("#")==-1};e.showEmbedder=function(h){var g=this;this.home.askIncludeControl("embed",function(){var i=new devhd.control.EmbedControl();
i.setHome(g.home);i.setNetcaster(g.netcaster);i.setReader(g.reader);i.setCategoryLabel(g.category);g.feedly.setMessageBarControl(i)})};e.startRenderHTML=function(){this._cancelAllVisualFinders();this.entryIndex={};this.endOfList=null;this.state="loading";this.pageElem.innerHTML=templates.page.list.prelayout(this.home);var g=this;this.reader.askFeedInformation(this.feedId,function(h){if(g.isDestroyed()==true){return
}g.onFeedInformationReady(h)},function(h){if(g.isDestroyed()==true){return}g.pageElem.innerHTML=templates.page.base.invalidFeed(h,g.feedId,g.home)})};e._buildPageModel=function(q){var l=0;var p=0;var o=0;var j=-1;var i=parseInt(this.feedly.getPagePreference("entryOverviewSize"));var k=2;if(this.pageInfo.uri=="latest"&&i==1){k=16}switch(i){case 100:l=10*k;
o=l;p=l;break;case 6:case 7:var h=Math.floor(this.width/(devhd.utils.PageConstants["U"+i+"_IMAGE_WIDTH"]+1+17));o=5*h;j=5*devhd.utils.PageConstants.U_HEIGHT(i);l=o*k*2;p=l;break;default:o=40;j=o*devhd.utils.PageConstants.U_HEIGHT(i);l=k*o;p=l}var g=this.pageInfo.pageNumber*p;var m=g+l;var n=Math.ceil(l/o);this.pageModel={pageNumber:this.pageInfo.pageNumber,start:g,end:m,nbrEntriesPerZone:o,nbrZones:n,zoneHeight:j,type:i}
};e.computeZoneHeight=function(g){var h=parseInt(this.feedly.getPagePreference("entryOverviewSize"));switch(h){case 100:return -1;case 6:var i=Math.floor(this.width/(2+10+1+devhd.utils.PageConstants.U6_IMAGE_WIDTH+1+10+2));return Math.ceil(g/i)*devhd.utils.PageConstants.U_HEIGHT(h);case 4:case 2:default:return g*devhd.utils.PageConstants.U_HEIGHT(h)
}};e.showCustomizer=function(g){this.showListCustomizer(g.target)};e.markAsRead=function(g){if(isNaN(g)){g=null}this.popup.hide();var h=this;if(this.subscription!=null){this.markAllSubscriptionEntriesAsRead(this.subscription.id,false,g,function(){if(g!=null){h.feedly.refresh()}})}else{if(this.category!=null){this.markCategoryAsRead(this.category,g,function(){if(g!=null){h.feedly.refresh()
}})}}};e.markAsReadOneDay=function(){this.markAsRead((new Date().getTime()-devhd.utils.DurationUtils.DAYS(1)))};e.markAsReadOneWeek=function(){this.markAsRead((new Date().getTime()-devhd.utils.DurationUtils.DAYS(7)))};e.assignDefaultOverviewSize=function(){var g=this.reader.listEntries({feedIds:[this.feedInfo.id]});if(this.feedInfo.id.indexOf("flickr")>-1||this.feedInfo.id.indexOf("smugmug")>-1){this.feedly.setPagePreference("entryOverviewSize","6",true)
}else{if(this.feedInfo.id.indexOf("youtube")>-1||this.feedInfo.id.indexOf("hulu")>-1||this.feedInfo.id.indexOf("vimeo.com")>-1){this.feedly.setPagePreference("entryOverviewSize","7",true)}}};e.onFeedInformationReady=function(g){if(this.isDestroyed()){return}this._cancelAllVisualFinders();this.entryIndex={};this.endOfList=null;this.state="loading";this.selectedEntryId=null;
this.feedInfo=g;var h=-1;this.feedly.clearNbrPages();if(this.feedly.isPagePreferenceLayered("entryOverviewSize")==false){this.assignDefaultOverviewSize()}this._buildPageModel(h);this.feedly.pushContext({uri:this.pageInfo.uri,title:this.feedInfo.title,pageNumber:this.pageInfo.pageNumber,level:this.feedInfo.level==1?1:2,queryInfo:{flsId:this.feedInfo.id,excludeLabel:this.hideReadArticlesFilter()?"read":null},category:this.category,feedId:this.pageInfo.type=="subscription"?this.pageInfo.key:null,website:this.feedInfo.website,subscriptions:this.subscription!=null?[this.subscription.id]:null});
this.feedly.setPageTitle(templates.page.list.title(this.feedInfo,{maxWidth:this.width-20,subscription:this.subscription,website:this.feedInfo.website},this.home));this.pageElem.innerHTML=templates.page.list.layout(this.feedInfo,this.pageModel,this.width,{maxWidth:this.width-20,subscription:this.subscription,website:this.feedInfo.website},this.home);
this.element("aboutArea").innerHTML=templates.page.list.layoutAboutArea(this.feedInfo,this.pageModel,this.width,{maxWidth:this.width-20,subscription:this.subscription,website:this.feedInfo.website},this.home);this.element("aboutArea").style.display="block";if(this.feedInfo.label==true){this.updatePageTitleHint()}this.createZoneLocationIndex();this.displayedZoneCount=0;
if(this.requestedScrollTop==null){this.lazyDisplay(0)}if(this.action=="subscribe"&&this.home.getUserId()!=null){this.subscribeToFeed(this.feedInfo.id,this.feedInfo.title)}};e.isFullyLoaded=function(){if(this.zoneLocationIndex==null){return true}return this.displayedZoneCount==this.zoneLocationIndex.length};e.askLazyDisplay=function(g){if(this.isDestroyed()){return
}if(this.isFullyLoaded()==true){return}this.lazyDisplay(g)};e.lazyDisplay=function(k){this.updateZoneLocationIndex();var l=k;var g=k+devhd.utils.HTMLUtils.getClientHeight(this.home.getDocument())*1.4;for(var j=this.zoneLocationIndex.length-1;j>=0;j--){var h=this.zoneLocationIndex[j];if(b(h,l,g)){this.askDisplayEntries(j);return}}};e.createZoneLocationIndex=function(){this.zoneLocationIndex=[];
for(var g=0;g<this.pageModel.nbrZones;g++){var h=this.element("zone"+g);this.zoneLocationIndex.push({start:h.offsetTop,end:h.offsetTop+h.offsetHeight,element:h})}};e.updateZoneLocationIndex=function(){for(var g=0;g<this.zoneLocationIndex.length;g++){var h=this.zoneLocationIndex[g];h.start=h.element.offsetTop;h.end=h.element.offsetTop+h.element.offsetHeight
}};function b(g,h,i){return g.start>=h&&g.start<=i||g.end>=h&&g.end<=i||g.start<=h&&g.end>=i}e.askDisplayEntries=function(g){if(this.isDestroyed()){return}if(this.zoneLocationIndex[g].requested==true){return}if(this.zoneLocationIndex[g].displayed==true){return}this.zoneLocationIndex[g].element.innerHTML=templates.page.list.loading(this.home);var k=this;
var i=this.pageModel.start+(g+1)*this.pageModel.nbrEntriesPerZone;var h=this.hideReadArticlesFilter()?"read":null;var j=this.oldestFirst()?"o":null;this.zoneLocationIndex[g].requested=true;this.reader.askEntries(this.feedInfo.id,{xt:h,r:j},i,function(m,q,o,n){if(k.isDestroyed()==true){return}try{if(q>0){var l=null;if(k.subscription!=null){l=k.subscription.unreadCount
}else{if(k.pageInfo.label!=null){l=k.reader.getCategoryUnreadCount(k.pageInfo.label)}}}k.busyCount--;k.onEntriesReady(m,i,g,n)}catch(p){c.error(513,"display articles",p)}},function(m,l){k.busyCount--;k.onEntriesError(m,l)})};e.onPageScrollChanged=function(i,h){this.askLazyDisplay(i);if(h&&this.feedly.getPagePreference("autoSelectOnScroll")=="yes"&&parseInt(this.feedly.getPagePreference("entryOverviewSize"))!=6&&this.inlinedEntryId==null){var g=this.findScrollFocus(i);
if(g!=null){this.selectEntry(g,false)}}if(h&&this.feedly.getPagePreference("autoSelectOnScroll")=="inlined-only"&&parseInt(this.feedly.getPagePreference("entryOverviewSize"))==100){var g=this.findScrollFocus(i);if(g!=null){this.selectEntry(g,false)}}};e.findScrollFocus=function(g){if(this.zoneLocationIndex==null){return null}var n=this.home.getDocument().body;
var m=g+100+g/(n.scrollHeight-n.clientHeight)*(n.clientHeight-200);var o=null;var h=null;for(var l=0;l<this.zoneLocationIndex.length;l++){var p=this.zoneLocationIndex[l];if(p.entryIds!=null&&p.entryIds.length>0){for(var k=0;k<p.entryIds.length;k++){if(l==0&&k==0){o=p.entryIds[k]}var q=this.element(p.entryIds[k]+"_main");if(q==null){continue}if(q.offsetTop<m){h=p.entryIds[k]
}else{return h||o}}}}return h};e.onNewEntriesAvailable=function(h,i,g){if(this.feedly==null||this.feedInfo==null){return}};e.onEntriesReady=function(t,s,g,m){if(this.isDestroyed()){return}if(this.feedInfo.label!=true&&this.websiteLinkOK!=true){this.feedly.setPageTitle(templates.page.list.title(this.feedInfo,{maxWidth:this.width-20,subscription:this.subscription,website:this.feedInfo.website},this.home));
this.websiteLinkOK=true}for(var n=0;n<=g;n++){if(this.zoneLocationIndex[n].displayed==true){continue}var k=t.slice(this.pageModel.start+n*this.pageModel.nbrEntriesPerZone,this.pageModel.start+(n+1)*this.pageModel.nbrEntriesPerZone);if(this.broadcast==false){var q=this;k=k.sort(function(i,w){var v=q.reader.lookupEntry(i);var j=q.reader.lookupEntry(w);
if(q.oldestFirst()){return v.lastModifiedTime-j.lastModifiedTime}else{return j.lastModifiedTime-v.lastModifiedTime}})}this.displayEntries(k,n);this.zoneLocationIndex[n].entryIds=k;this.zoneLocationIndex[n].displayed=true;if(k.length==0&&n==0){this.element("emptyListMessage").style.display="block"}this.zoneLocationIndex[n].element.style.height="auto";
if(k.length<this.pageModel.nbrEntriesPerZone||(n==g&&m==true)){var r=this.computeZoneHeight(k.length);this.zoneLocationIndex[n].element.style.partial="true";for(var l=n+1;l<this.pageModel.nbrZones;l++){this.zoneLocationIndex[l].entryIds=[];this.zoneLocationIndex[l].displayed=true;this.zoneLocationIndex[l].element.style.display="none"}var u=this.element("listPagePagingControls_Next");
u.className=u.className+" listPagePagingControlInactif";u.onclick="";if(this.pageModel.pageNumber==0){u.style.display="none"}this.element("endOfListIndicator").style.display="inline";this.endOfList=true;this.onEndOfListDetected();break}this.displayedZoneCount=Math.max(this.displayedZoneCount,g+1)}this.element("range").innerHTML=templates.page.base.range(this.pageModel.start+1,t.length,this.home);
if(this.selectedEntryId==null&&this.requestedSelectedEntryId==null&&this.navigation=="nextPage"&&this.navigationMode=="keyboard"){var p=t[this.pageModel.start];if(p!=null){this.selectEntry(p,false)}}if(this.selectedEntryId==null&&this.requestedSelectedEntryId==null&&this.navigation=="previousPage"&&this.navigationMode=="keyboard"){if(g==this.pageModel.nbrZones-1){var o=t[t.length-1];
if(o!=null){this.selectEntry(o,false)}}}if(this.requestedSelectedEntryId!=null&&this.selectedEntryId==null){for(var n=0;n<t.length;n++){if(t[n]==this.requestedSelectedEntryId){this.selectEntry(this.requestedSelectedEntryId,false)}}}if(this.subscription!=null&&this.subscription.unreadCount==1&&this.autoInlineUnique==null){var h=this.findNextEntryId(true);
if(h!=null){this.inlineEntry(h)}}this.autoInlineUnique="unarmed"};e.onEntriesError=function(h,g){this.element("main_"+this.feedInfo.id+"_entries").innerHTML=templates.page.base.errorBox(h+" -- "+g,this.pageInfo,this.home)};e.onEndOfListDetected=function(){this.feedly.setNbrPages(this.pageModel.pageNumber+1)};e.displayEntries=function(m,g){if(g==0&&this.feedly.getPagePreference("entryOverviewSize")=="4"&&m.length>7&&this.pageInfo.uri!="latest"){var l=0;
for(var h=0;h<3;h++){var p=this.reader.lookupEntry(m[h]);if(p.fits(devhd.utils.PageConstants.UR_IMAGE_WIDTH,devhd.utils.PageConstants.UR_IMAGE_HEIGHT)>=2){l++}}if(l>=2){var n=[];for(var h=0;h<3;h++){var p=this.reader.lookupEntry(m[h]);this.entryIndex[p.getId()]=p;n.push(p)}var j=this;this.home.askIncludeControl("recommendationArea",function(){j.topArea=new devhd.control.RecommendationAreaControl();
j.topArea.setHome(j.home);j.topArea.setReader(j.reader);j.topArea.setFeatured(n);j.topArea.setDisplayMode(j.feedly.getDisplayMode());j.topArea.setPage(j);j.topArea.setPart(j.element("topArea"));j.topArea.display()});m=m.slice(3)}}try{var o=this["displayU"+this.feedly.getPagePreference("entryOverviewSize")+"Entries"];if(o==null){o=this.displayU4Entries
}o.call(this,this.feedInfo.id,m,g)}catch(k){c.error(829,"display articles (list) ",k);throw k}};e.displayU1Entries=function(i,h,g){this.displayUEntries(1,h,this.element("zone"+g),true,false);this.state="loaded"};e.displayU3Entries=function(i,h,g){this.displayUEntries(3,h,this.element("zone"+g),true,true);this.state="loaded"};e.displayU4Entries=function(i,h,g){this.displayUEntries(4,h,this.element("zone"+g),true,true);
this.state="loaded"};e.displayU6Entries=function(i,h,g){this.displayUEntries(6,h,this.element("zone"+g),false,true);this.state="loaded"};e.displayU7Entries=function(i,h,g){this.displayUEntries(7,h,this.element("zone"+g),false,true);this.state="loaded"};e.displayU100Entries=function(g,r,j){var l=this.feedly.getPagePreference("entryOverviewSize");var s=false;
var m=[];for(var n=0;n<r.length;n++){var t=this.reader.lookupEntry(r[n]);m.push({entry:t,type:l});this.entryIndex[t.getId()]=t;if(t.embedsVideo==true){s=true}}var p=true;if(this.subscription!=null){p=false}var k=this.element("zone"+j);k.innerHTML=templates.page.base.parts(m,this.width,{linkTo:"entry",includeSourceTitle:p,feedInfo:this.feedInfo,includeDateSeparator:true,lastDate:this.lastDate},this.home);
try{this.lastDate=findOldest(m).entry.getLastModifiedDate()}catch(q){}var h=k.getElementsByTagName("a");for(var n=0;n<h.length;n++){h[n].target="_blank"}var o=this;devhd.utils.ArrayUtils.forEach(k.getElementsByTagName("img"),function(i){o.bind(i,"load",f)});this.state="loaded"};function f(k){if(this.isDestroyed()==true){return}var l=k.target;if(l.src.indexOf("feedburner.com")>-1||l.src.indexOf("feedproxy.google.com")>-1){l.style.display="none"
}var g=this.width-40;var i=parseInt(l.width);var j=parseInt(l.height);if(!isNaN(i)&&!isNaN(j)&&i>0){l.style.maxHeight=(g*j/i)+"px"}l.style.maxWidth=g+"px"}e.markAllSubscriptionEntriesAsRead=function(h,i,g,j){this.state="batchMarkAsRead";this.reader.markAllSubscriptionEntriesAsRead(h,i,g,j)};e.onSubscriptionMarkedAsRead=function(g){if(this.feedId!=g){return
}this.state="loaded"};e.onSubscriptionAdded=function(h,g,i){if(i==true){return}this.feedly.reloadPage({forceRecreate:true,disableAutoMarkAsRead:true})};e.onSubscriptionAddedToCategory=function(h,g,i){if(this.feedId!=h){return}if(i==true){return}this.feedly.pushContext({uri:"category/"+g,pageNumber:0,title:this.reader.formatTitle(g),level:1,category:g});
this.feedly.selectTab(g);this.feedly.reloadPage({forceRecreate:true,disableAutoMarkAsRead:true})};e.onSubscriptionRemovedFromCategory=function(h,g){if(this.feedId!=h){return}var k=this.reader.lookupSubscription(h);var j="feedly.others";var i=k.listCategoryLabels();if(i.length>0){j=i[0]}this.feedly.pushContext({uri:"category/"+j,pageNumber:0,title:this.reader.formatTitle(j),level:1,category:j});
this.feedly.selectTab(j);this.feedly.reloadPage({forceRecreate:true,disableAutoMarkAsRead:true})};e.onSubscriptionRemoved=function(g){if(this.feedId!=g){return}var h=this.feedly.goBack();if(h==false){this.feedly.loadDashboardPage()}};e.markPageAsRead=function(){this.signs.setMessage(d(295),100);var g=this;this.home.getDocument().defaultView.setTimeout(function(){var h=[];
if(g.recoEntryIds!=null&&g.recoEntryIds.length>0){for(var m=0;m<g.recoEntryIds.length;m++){h.push(g.recoEntryIds[m])}}for(var m=0;m<g.zoneLocationIndex.length;m++){var k=g.zoneLocationIndex[m];if(k.entryIds!=null&&k.entryIds.length>0){for(var l=0;l<k.entryIds.length;l++){h.push(k.entryIds[l])}}}g.reader.markEntriesAsRead(h)},15)};e.countNextUnreadEntries=function(p){var n=0;
var o=false;if(this.selectedEntryId==null){return -1}for(var m=0;m<this.zoneLocationIndex.length;m++){var g=this.zoneLocationIndex[m];if(g.entryIds!=null&&g.entryIds.length>0){for(var k=0;k<g.entryIds.length;k++){if(o==true){var l=g.entryIds[k];var h=this.reader.lookupEntry(l);if(h.isRead()==false){n++}}if(g.entryIds[k]==this.selectedEntryId){o=true
}}}}return n};e.findNextEntryId=function(o){var n=false;if(this.selectedEntryId==null){n=true}for(var m=0;m<this.zoneLocationIndex.length;m++){var g=this.zoneLocationIndex[m];if(g.entryIds!=null&&g.entryIds.length>0){for(var k=0;k<g.entryIds.length;k++){if(n==true){if(o==true){var l=g.entryIds[k];var h=this.reader.lookupEntry(l);if(h.isRead()==false){return l
}else{continue}}else{return g.entryIds[k]}}if(g.entryIds[k]==this.selectedEntryId){n=true}}}}return null};e.findLastLoadedEntry=function(j){for(var h=this.zoneLocationIndex.length-1;h>=0;h--){var g=this.zoneLocationIndex[h];if(g.entryIds!=null&&g.entryIds.length>0){return g.entryIds[g.entryIds.length-1]}}return null};e.findPreviousEntryId=function(o){var n=false;
if(this.selectedEntryId==null){n=true}for(var m=this.zoneLocationIndex.length-1;m>=0;m--){var g=this.zoneLocationIndex[m];if(g.entryIds!=null&&g.entryIds.length>0){for(var k=g.entryIds.length-1;k>=0;k--){if(n==true){if(o==true){var l=g.entryIds[k];var h=this.reader.lookupEntry(l);if(h.isRead()==false){return l}else{continue}}else{return g.entryIds[k]
}}if(g.entryIds[k]==this.selectedEntryId){n=true}}}}};e.onPreviousEntry=function(i,g){var h=this.findPreviousEntryId(i);if(h!=null){if(g==true){if(this.feedly.getPagePreference("entryOverviewSize")!="100"){this.selectEntry(h,"toview")}}else{this.inlineEntry(h,true)}}else{this.feedly.loadPreviousPage({selectEntry:true,navigationMode:"keyboard"})}};e.onNextEntry=function(i,g){var h=this.findNextEntryId(i);
if(h==null&&this.isFullyLoaded()==false){var j=this.findLastLoadedEntry();if(this.selectedEntryId!=j){h=j}}if(h!=null){if(g==true){if(this.feedly.getPagePreference("entryOverviewSize")!="100"){this.selectEntry(h,"toview")}}else{this.inlineEntry(h,true)}}else{if(this.endOfList==true){this.signs.setMessage(d(87))}else{if(this.isFullyLoaded()==true){this.feedly.loadNextPage({selectEntry:true,navigationMode:"keyboard"});
return}else{this.signs.setMessage(d(105))}}}};e.onCategoryUnreadCountChanged=function(g,h,i){if(this.isDestroyed()==true){return}if(this.pageInfo.label!=g){return}if(i==true){return}this.updatePageTitleHint()};e.updatePageTitleHint=function(){var g=this.reader.getCategoryUnreadCount(this.pageInfo.label);this.element("pageTitleHint").innerHTML=templates.page.base.labelFeedHeaderHint(this.pageInfo.label,g,this.home)
}})();