(function(){var c=devhd.pkg("pages");c.WelcomePage=function(k){this.guid=k};var f=c.WelcomePage.prototype=new c.BasePage();f.service=function(l,k){this.pageInfo=l;this.width=k.width;this.title="Welcome";this.initBase(k);this.startRenderHTML()};f.destroy=function(l,k){this.destroyBase()};f.allowsSideArea=function(){return false};f.allowsPageHeader=function(){return true
};var a=["tech","style","web design","green","gaming","cooking","celebrities","finance"];function g(k){return"01440539406158127124/"+k}f.startRenderHTML=function(){try{this.state="loading";this.feedly.setNbrPages(1);this.feedly.unselectTabs();this.feedly.pushContext({uri:this.pageInfo.uri,pageNumber:0,title:this.title,level:0});this.feedly.setPageTitle(templates.page.welcome.title());
this.pageElem.innerHTML=templates.page.welcome.layout();this.element("mediaArea").innerHTML=templates.page.welcome.layoutGallery();this.element("photoArea").innerHTML=templates.page.welcome.layoutPhotos();this.element("sectionsArea").innerHTML=templates.page.welcome.layoutSections(a,this.home);this.element("sectionsArea").style.display="block";var l={};
var k=this;devhd.utils.FlowUtils.sequence({},[function(p,o){j.call(k,g("featured"),16,l,function(q){e.call(k,q);devhd.fn.callback(p)},function(q,r){$debug("[welcome-page] failed to display featured.");devhd.fn.callback(p)},o)},function(p,o){j.call(k,g("shows"),5,l,function(q){i.call(k,q,7);devhd.fn.callback(p)},function(q,r){$debug("[welcome-page] failed to display videos");
devhd.fn.callback(p)},o)},function(p,o){devhd.utils.FlowUtils.parallelForEach({},a,function(q,r,u,s,t){j.call(k,g(q),3,l,function(v){b.call(k,q,v);devhd.fn.callback(u)},function(v,w){$debug("[welcome-page] failed to display category:"+q);devhd.fn.callback(u)},s)},{onSuccess:p,onError:o})},function(q,p){var o="";j.call(k,g("photos"),5,l,function(r){d.call(k,r);
devhd.fn.callback(q)},function(r,s){$debug("[welcome-page] failed to display photos");devhd.fn.callback(q)},p)},])}catch(m){var n=devhd.utils.ExceptionUtils.formatError("render welcome page",m);$debug("[welcome page] "+n);this.pageElem.innerHTML=n}};function j(l,k,o,p,n){var m=this;this.reader.askMix(l,function(s){try{if(s==null||s.length==0){devhd.fn.callback(n);
return}var q=[];for(var r=0;r<s.length&&q.length<k;r++){if(o[s[r].getId()]==true){continue}q.push(s[r]);o[s[r].getId()]=true}devhd.fn.callback(p,q)}catch(t){$debug("[mix]"+t.name+" -- "+t.message);devhd.fn.callback(n)}})}var h=3;function e(l){var o=l.sort(function(t,s){if(s.metadata.starred!=t.metadata.starred){return s.metadata.starred-t.metadata.starred
}else{return s.lastModifiedTime-t.lastModifiedTime}});var n=[],m=[];for(var q=0;q<h&&(2*q+1<o.length);q++){n.push(o[2*q]);m.push(o[2*q+1])}var k=o.slice(2*h);if(n.length==0){this.pageElem.innerHTML="Empty";return}this.element("headlines1").innerHTML=templates.page.welcome.displayRecommendations(n,this.home);for(var q=0;q<n.length;q++){this.askFindVisual(n[q],"U10")
}this.element("headlines2").innerHTML=templates.page.welcome.displayRecommendations(m,this.home);for(var q=0;q<m.length;q++){this.askFindVisual(m[q],"U10")}var r=[];for(var p=1;p<k.length;p++){r.push({entry:k[p],type:4})}r=r.sort(function(t,s){return s.entry.lastModifiedTime-t.entry.lastModifiedTime});this.element("headlines3").innerHTML=templates.page.welcome.layoutFeatured(r,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:false,includeFavIcon:true},this.home);
for(var p=0;p<r.length;p++){this.askFindVisual(r[p].entry,"U4")}}function d(k){if(k.length==0){return}var o=[];for(var m=0;m<k.length&&m<5;m++){var l=k[m];o.push({entry:l,type:6})}this.element("photoArea").style.display="block";this.element("photos").innerHTML=templates.page.base.parts(o,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true},this.home);
for(var n=0;n<o.length;n++){this.askFindVisual(o[n].entry,"U6")}}function i(k){if(k.length==0){return}var o=[];for(var m=0;m<k.length&&m<5;m++){var l=k[m];o.push({entry:l,type:7})}this.element("mediaArea").style.display="block";this.element("gallery").innerHTML=templates.page.base.parts(o,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true},this.home);
for(var n=0;n<o.length;n++){this.askFindVisual(o[n].entry,"U7")}}function b(m,k){var n=this.element("main_section_"+m+"_entries");if(n==null){return}var o=k.slice(0,3).sort(function(r,q){return q.lastModifiedTime-r.lastModifiedTime});if(o.length==0){this.element("main_section_"+m+"_holder").style.display="none";return}var p=[];for(var l=0;l<o.length;
l++){p.push({entry:o[l],type:15})}n.innerHTML=templates.page.base.parts(p,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home)}})();