(function(){var a=devhd.pkg("pages");var e=devhd.i18n.L;var d=devhd.log.get("page.sites");a.SitesPage=function(g){this.guid=g};var b=a.SitesPage.prototype=new a.BasePage();b.service=function(h,g){this.pageInfo=h;this.width=g.width;this.categoryLabel="#my";this.initBase(g);this.startRenderHTML()};b.destroy=function(h,g){if(this.topArea!=null){this.topArea.destroy();
this.topArea=null}this.entries=null;this.feeds=null;this.destroyBase()};b.startRenderHTML=function(){this._cancelAllVisualFinders();this.state="loading";this.feeds=[];this.pending=0;this.entries=[];this.complete=false;this.feedIds={};this.feedTitles={};var i=templates.page.sites.title();this.feedly.setPageTitle(i);this.feedly.clearNbrPages();this.feedly.selectTab(this.categoryLabel);
this.feedly.pushContext({uri:this.pageInfo.uri,pageNumber:0,title:i,level:1,category:this.categoryLabel,subscriptions:[]});this.pageElem.innerHTML=templates.page.sites.layout();this.startTime=new Date().getTime();var g=0;var h=this;this.bookmarks.askSuggestFeeds(40,function(j){g++;if(g<10){var k=h.element("exploreBar");if(k!=null){k.style.width=(g*40)+"px"
}}if(h.feeds.length>25){return}c.call(h,j)},function(){if(h.isDestroyed()){return}if(h.feeds.length+h.pending==0){h.feedly.loadPage("home");return}h.complete=true;f.call(h)},function(j,k){h.feedly.loadPage("home")});this.analytics.trackPageView("topsites")};function f(){if(this.featured==true){return}var g=12;if((new Date().getTime()-this.startTime)<8000){if(this.pending>0&&this.feeds.length<g){return
}if(this.pending==0&&this.complete==false){return}}this.entries=this.entries.sort(function(k,i){var m=i.topScore/(new Date().getTime()-i.lastModifiedTime>devhd.utils.DurationUtils.DAYS(7)?1000:1);var l=k.topScore/(new Date().getTime()-k.lastModifiedTime>devhd.utils.DurationUtils.DAYS(7)?1000:1);return m-l});for(var h=0;h<this.entries.length&&h<3;h++){devhd.utils.HTMLUtils.remove(this.element(this.entries[h].getId()+"_main"))
}var j=this;this.home.askIncludeControl("recommendationArea",function(){j.topArea=new devhd.control.RecommendationAreaControl();j.topArea.setHome(j.home);j.topArea.setReader(j.reader);j.topArea.setFeatured(j.entries.slice(0,3));j.topArea.setPage(j);j.topArea.setDisplayMode(j.feedly.getDisplayMode());j.topArea.setPart(j.element("topArea"));j.topArea.display();
var i=j.home.getDocument().getElementById("featuredModule_part");if(i!=null){i.innerHTML=templates.modules.layoutFeatured(j.feeds.slice(0,15),{showIndexUnreadCount:false},j.home);i.style.display="block"}j.featured=true})}function c(h){try{if(this.feedIds[h.id]!=null){f.call(this);return}if(this.feedTitles[h.title]!=null){f.call(this);return}if(h.id.indexOf("?")>-1){f.call(this);
return}this.feedIds[h.id]=true;this.feedTitles[h.title]=true;h.subscribed=this.reader.lookupSubscription(h.id)!=null;devhd.utils.HTMLUtils.append(this.element("contentArea"),templates.page.sites.feedArea(h));var g=h.id;var i=this;this.pending++;this.reco.askFeedSnapshot(g,7,function(k){if(i.isDestroyed()){return}if(k==null||k.length==0||new Date().getTime()-i.reader.lookupEntry(k[0]).lastModifiedTime>devhd.utils.DurationUtils.DAYS(15)){devhd.utils.HTMLUtils.remove(i.element(g+"_feed"))
}else{h.title=devhd.utils.StringUtils.cleanSourceTitle(i.reader.lookupEntry(k[0]).getSourceTitle());i.element("feed_"+g+"_title").innerHTML=templates.page.sites.feedAreaTitle(h,i.home);i.displayEntries(g,k);i.feeds.push(h)}i.pending--;f.call(i)},function(l,k){if(i.isDestroyed()){return}devhd.utils.HTMLUtils.remove(i.element(g+"_feed"));i.pending--;f.call(i)
})}catch(j){d.error(286,"ask entries ",g,j)}}b.displayEntries=function(k,s){try{var q=[];for(var o=0;o<s.length;o++){var t=this.reader.lookupEntry(s[o]);if(t.getCleanTitle()==""){continue}q.push(t)}this.entries=this.entries.concat(q);var r=devhd.utils.EntryUtils.suggestType(q);if(r==6||r==7){var m=[];for(var n=0;n<q.length;n++){m.push({entry:q[n],type:r})
}var h=this.element("main_"+k+"_entries");h.style.marginRight="-34px";h.innerHTML=templates.page.base.parts(m,this.width,{includeSourceTitle:true,includeCategoryLabel:false},this.home);for(var n=0;n<m.length;n++){this.askFindVisual(m[n].entry,"U"+r)}}else{var g=4;var m=[];for(var n=0;n<q.length&&n<g;n++){m.push({entry:q[n],type:4})}var h=this.element("main_"+k+"_entries");
h.innerHTML=templates.page.base.parts(m,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home);for(var n=0;n<m.length&&n<g;n++){this.askFindVisual(m[n].entry,"U4")}m=[];for(var n=g;n<q.length;n++){m.push({entry:q[n],type:12})}if(m.length>0){this.element("main_"+k+"_saved").innerHTML=templates.page.base.parts(m,this.width,{includeSourceTitle:true,includeCategoryLabel:false,includeNoThanks:true,includeFavIcon:true},this.home)
}}}catch(p){d.error(377,"display articles ",k,p);var l=devhd.utils.ExceptionUtils.formatError("display articles",p);var h=this.element("main_"+k+"_entries");h.innerHTML=l}};b.excludeFeed=function(h){if(h==null){return}this.bookmarks.askExcludeFeed(h);var g=this.element(h+"_feed");this.effects.fade(this.element(h+"_feed"),{delay:1,from:1,to:0,onComplete:function(i){devhd.utils.HTMLUtils.remove(i)
}},"feedly")};b.markFeedAsFavorite=function(g){}})();