/*
FreshStart - License Agreement

Visibo Limited gives you permission to make verbatim copies of the 'FreshStart' software (the "Software") without restriction, so long as your copies include a copy of this license and all of the original copyright notices and associated disclaimers. You may not distribute modified source code. You may not charge a fee for the Software or claim that the Software is yours. You may not use the name Visibo to endorse or promote products derived from the Software without prior written permission.

THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE. UNDER NO CIRCUMSTANCES SHALL VISIBO LIMITED BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND RELATED TO OR ARISING OUT OF YOUR USE OF THE SOFTWARE, EVEN IF VISIBO LIMITED HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.

Copyright (c) 2009 Visibo Limited- contactus@visibotech.com. All rights reserved.

*/
function save_options(){var a=parseInt(document.getElementById("backupPeriod").value);if(isNaN(a))a=document.getElementById("backupPeriod").value=5;if(a<1||a>999)alert(chrome.i18n.getMessage("optionsBackupPeriodOutOfRange"));else{localStorage.backupPeriod=a;a=document.getElementById("crashRestore");localStorage.crashRestore=a.checked;chrome.extension.getBackgroundPage().changeBackupSetting();document.getElementById("options-saved").style.display="inline";a=document.getElementById("dateFormatSelect");
localStorage.dateFormat=a.children[a.selectedIndex].value}}
function restoreSetting(){if(localStorage.crashRestore=="true"){var a=document.getElementById("crashRestore");a.checked=true;document.getElementById("backupPeriod").disabled=""}else{a=document.getElementById("crashRestore");a.checked=false;document.getElementById("backupPeriod").disabled="disabled"}if(localStorage.backupPeriod)document.getElementById("backupPeriod").value=localStorage.backupPeriod;else document.getElementById("backupPeriod").value=5;if(localStorage.dateFormat){a=document.getElementById("dateFormatSelect");
for(var b=0;b<a.children.length;b++){var c=a.children[b];if(c.value==localStorage.dateFormat){c.selected="true";break}}}}
function init(){document.title=chrome.i18n.getMessage("optionsPageTitle");document.getElementById("pagetitle").innerHTML=chrome.i18n.getMessage("optionsPageTitle");document.getElementById("optionsEnableCrashRecovery").innerHTML=chrome.i18n.getMessage("optionsEnableCrashRecovery");document.getElementById("optionsBackupPeriod").innerHTML=chrome.i18n.getMessage("optionsBackupPeriod");document.getElementById("optionsDateFormat").innerHTML=chrome.i18n.getMessage("optionsDateFormat");document.getElementById("stringSave").innerHTML=
chrome.i18n.getMessage("save");document.getElementById("options-saved").innerHTML=chrome.i18n.getMessage("optionsSaved");document.getElementById("middleClickTips").innerHTML=chrome.i18n.getMessage("middleClickTips");document.getElementById("supportUs").innerHTML=chrome.i18n.getMessage("supportUs");document.getElementById("contactUs").innerHTML=chrome.i18n.getMessage("contactUs");document.getElementById("contactUs2").innerHTML=chrome.i18n.getMessage("contactUs2");document.getElementById("contactUs3").innerHTML=
chrome.i18n.getMessage("contactUs3");document.getElementById("contactUs4").innerHTML=chrome.i18n.getMessage("contactUs4");document.getElementById("copyright").innerHTML=chrome.i18n.getMessage("copyright");document.getElementById("stringMinutes").innerHTML=chrome.i18n.getMessage("minutes");document.getElementById("optionsNewUserTips").innerHTML=chrome.i18n.getMessage("optionsNewUserTips")}
function togglePeriod(){if(document.getElementById("crashRestore").checked)document.getElementById("backupPeriod").disabled="";else document.getElementById("backupPeriod").disabled="disabled"};
