/*
FreshStart - License Agreement

Visibo Limited gives you permission to make verbatim copies of the 'FreshStart' software (the "Software") without restriction, so long as your copies include a copy of this license and all of the original copyright notices and associated disclaimers. You may not distribute modified source code. You may not charge a fee for the Software or claim that the Software is yours. You may not use the name Visibo to endorse or promote products derived from the Software without prior written permission.

THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE. UNDER NO CIRCUMSTANCES SHALL VISIBO LIMITED BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND RELATED TO OR ARISING OUT OF YOUR USE OF THE SOFTWARE, EVEN IF VISIBO LIMITED HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.

Copyright (c) 2009 Visibo Limited- contactus@visibotech.com. All rights reserved.

*/
var background=chrome.extension.getBackgroundPage(),sessions=[],editedSession,editedBlock;function openUpdate(){localStorage.setItem("updateread",background.MAJOR_VERSION);chrome.tabs.create({url:"http://www.visibotech.com/FreshStart/update140.html",selected:true});window.close()}
function init(){$("#stringUpdatedMessage").html(chrome.i18n.getMessage("updatedMessage"));$("#stringSaveSession").html(chrome.i18n.getMessage("saveSession"));$("#savetitle").val(chrome.i18n.getMessage("mySession"));$("#smsavelist").attr("title",chrome.i18n.getMessage("smSaveList"));$("#smsavetoggle").attr("title",chrome.i18n.getMessage("smSaveToggle"));$("#smeditnewtoggle").attr("title",chrome.i18n.getMessage("smSaveToggle"));$("#smeditsavedtoggle").attr("title",chrome.i18n.getMessage("smSaveToggle"));
$("#smrestorelabel").html(chrome.i18n.getMessage("restoreSession"));$("#smrestorelabel2").html(chrome.i18n.getMessage("restoreSession2"));$("#smheadingtitle").html(chrome.i18n.getMessage("smHeadingTitle"));$("#smheadingnew").html(chrome.i18n.getMessage("smHeadingNew"));$("#smheadingsaved").html(chrome.i18n.getMessage("smHeadingSaved"));$("#smeditsave").attr("value",chrome.i18n.getMessage("smEditSave"));$("#smeditcancel").attr("value",chrome.i18n.getMessage("smEditCancel"));$("#smeditremove").attr("value",
chrome.i18n.getMessage("remove"));$("#options").html(chrome.i18n.getMessage("options"));$("#smrestorecrash").html(chrome.i18n.getMessage("restorePreviousSession"));$("#sessionTextBoxCloseBtn").attr("title",chrome.i18n.getMessage("sessionTextBoxClose"));$("#importSessionBtn").attr("title",chrome.i18n.getMessage("sessionTextBoxImport"));if(localStorage.lastUsedSessionName)document.getElementById("savetitle").value=localStorage.lastUsedSessionName;if(localStorage.getItem("updateread"))if(localStorage.getItem("updateread")>=
background.MAJOR_VERSION)document.getElementById("updateNotifier").style.display="none";chrome.tabs.getAllInWindow(null,function(b){for(var c=document.getElementById("smsavelist"),e=0;e<b.length;e++){var f=b[e],g=document.createElement("div");g.setAttribute("class","smtabline");g.setAttribute("title",f.title+" : "+f.url);var d=document.createElement("input");d.setAttribute("class","smcheck");d.setAttribute("type","checkbox");d.setAttribute("checked",true);d.id="tabcheck"+f.id;var h=document.createElement("div");
h.setAttribute("class","smtablabel");h.textContent=f.title;g.appendChild(d);g.appendChild(h);c.appendChild(g)}$("#smsavebase .smcheck").change(function(){var i=$("#smsavebase .smcheck:checked").length==0;$("#smsavebutton").attr("disabled",i)})});background.initSession(function(b){sessions=b;createSessionList()});var a=document.getElementById("savetitle");a.focus();a.select();a.addEventListener("keypress",function(b){b.keyCode==13&&save()});if(localStorage.crashRestore=="true")document.getElementById("smrestorecrash").textContent=
chrome.i18n.getMessage("restorePreviousSession");else document.getElementById("smrestorecrash").textContent=chrome.i18n.getMessage("enableCrashRecovery")}function crashRestore(){localStorage.crashRestore=="true"?chrome.tabs.create({url:chrome.extension.getURL("./crashRestore.html"),selected:true}):chrome.tabs.create({url:chrome.extension.getURL("./options.html"),selected:true});window.close()}
function createSessionList(){if(sessions.length==0){var a=document.getElementById("smrestorelist"),b=document.createElement("div");b.setAttribute("class","nosessionsaved");b.textContent=chrome.i18n.getMessage("noSessionSaved");a.appendChild(b)}else{a=document.getElementById("smrestorelist");for(var c=0;c<sessions.length;c++){var e=sessions[c];b=document.createElement("div");b.setAttribute("class","smsessionblock");b.setAttribute("title",chrome.i18n.getMessage("clickToRestore",[e.title]));b.id="session_"+
c;b.sessionId=c;b.onmousedown=stopDragEffect;var f=document.createElement("div");f.setAttribute("class","smsessionlabel");var g=document.createElement("div");g.textContent=e.title;g.setAttribute("class","smsessiontitle");var d=document.createElement("div");d.setAttribute("class","smsessioncount");d.textContent=chrome.i18n.getMessage("tabsCount",[e.tabsCount.toString()]);var h=document.createElement("div");h.setAttribute("class","smsessiontimelabel");e=changeDateFormat(e.date);h.textContent=e;h.addEventListener("mousedown",
load,true);f.appendChild(g);f.appendChild(d);f.addEventListener("mousedown",load,true);b.appendChild(f);b.appendChild(h);f=document.createElement("div");f.setAttribute("class","controls");g=document.createElement("div");g.setAttribute("class","control smsessionedit");g.setAttribute("title",chrome.i18n.getMessage("edit"));g.onmouseover=showTooltip;g.onmouseout=hideTooltip;g.onclick=edit;d=document.createElement("div");d.setAttribute("class","control smsessionremove");d.setAttribute("title",chrome.i18n.getMessage("remove"));
d.onmouseover=showTooltip;d.onmouseout=hideTooltip;d.onclick=remove;h=document.createElement("div");h.setAttribute("class","control smsessionexport");h.setAttribute("title",chrome.i18n.getMessage("export"));h.onmouseover=showTooltip;h.onmouseout=hideTooltip;h.onclick=exportSession;e=document.createElement("div");e.setAttribute("class","tooltip");f.appendChild(e);f.appendChild(d);f.appendChild(g);f.appendChild(h);b.appendChild(f);a.appendChild(b)}}}
function changeDateFormat(a){var b=a.split("/");switch(localStorage.dateFormat){case "1":a=b[0]+"/"+b[1]+"/"+b[2];break;case "2":a=b[1]+"/"+b[0]+"/"+b[2];break;case "3":a=b[2]+"-"+b[1]+"-"+b[0];break;default:a=a}return a}
function save(a){if($("#smsavebutton").attr("disabled")!="true"){a=document.getElementById("savetitle");var b="My Session";if(a)b=a.value;localStorage.lastUsedSessionName=b;chrome.tabs.getAllInWindow(null,function(c){var e=new Date;e=e.getDate()+"/"+(e.getMonth()+1)+"/"+(e.getYear()+1900);e=new background.SessionData(b,e);for(var f=0;f<c.length;f++){var g=c[f],d=document.getElementById("tabcheck"+g.id);d&&d.checked&&e.urls.push({url:g.url,title:g.title})}e.urls.length>0&&background.saveSession(e);
window.close()})}}function load(a){var b=closest(a.target,"smsessionblock");if(sessions[b.sessionId]){var c=a.button;if(a.ctrlKey||a.metaKey)c=1;background.restoreSession(sessions[b.sessionId].folderId,c)}window.close()}function stopDragEffect(a){a.preventDefault();a.stopPropagation()}
function showTooltip(a){var b=closest(a.target,"smsessionblock").querySelector(".tooltip");b.textContent=a.target.getAttribute("title");b.style.marginRight=a.target.parentNode.offsetWidth-a.target.offsetLeft-16+"px"}function hideTooltip(a){closest(a.target,"smsessionblock").querySelector(".tooltip").textContent=""}function renameChange(a){a.keyCode==13&&editSave(a)}
function edit(a){a=closest(a.target,"smsessionblock");editedSession=sessions[a.sessionId];editedBlock=a;background.getSession(editedSession.folderId,function(b){chrome.tabs.getAllInWindow(null,function(c){$("#smtitle").val("");$(".smeditlist .smtabline").remove();$("#smeditlist1").hide();$("#smeditlist2").hide();for(var e={},f=0;f<b.urls.length;++f)e[b.urls[f].url]=b.urls[f];var g=$("#smeditlist1");for(f=0;f<c.length;f++){var d=c[f];if(!(d.url in e)){var h=$("<div>",{"class":"smtabline",title:d.url,
pageTitle:d.title,url:d.url}).appendTo(g),i=$("<input>",{"class":"smcheck",type:"checkbox"}).appendTo(h);d=$("<div>",{"class":"smtablabel",text:d.title}).appendTo(h);$("#smeditlist1").show()}}c=$("#smeditlist2");for(f=0;f<b.urls.length;f++){d=b.urls[f];h=$("<div>",{"class":"smtabline",title:d.url,pageTitle:d.title,url:d.url}).appendTo(c);i=$("<input>",{"class":"smcheck",type:"checkbox",checked:"true"}).appendTo(h);d=$("<a>",{"class":"smtablabel",onclick:function(){window.open(this.href);return false},
href:d.url,text:d.title}).appendTo(h);$("#smeditlist2").show()}$("#smeditsession .smcheck").change(function(){var j=$("#smeditsession .smcheck:checked").length==0;$("#smeditsave").attr("disabled",j)});$("#smeditsession").show().animate({left:"0%"},250,"swing",function(){$("#smtitle").val(editedSession.title).focus().select()})})})}
function editSave(a){if(!$("#smeditsave").attr("disabled"))if($("#smtitle").val()){a=$(".smeditlist .smtabline");var b=new Date;editedSession.date=b.getDate()+"/"+(b.getMonth()+1)+"/"+(b.getYear()+1900);editedSession.title=$("#smtitle").val();editedSession.urls=[];for(b=0;b<a.length;++b){var c=$(a[b]);c.find("input").attr("checked")&&editedSession.urls.push({url:c.attr("url"),title:c.attr("pageTitle")})}editedSession.urls.length?background.updateSession(editedSession,function(){$(editedBlock).find(".smsessiontitle").text(editedSession.title);
$(editedBlock).find(".smsessioncount").text(chrome.i18n.getMessage("tabsCount",[editedSession.urls.length]))}):remove({target:editedBlock});editCancel()}}function editCancel(a){$("#smeditsession").animate({left:"100%"},250,"swing",function(){$("#smeditsession").hide()})}function editRemove(a){remove({target:editedBlock});editCancel(a)}
function remove(a){var b=chrome.i18n.getMessage("confirmDeleteQuestion");renderConfirmBox(b,function(c){if(c){var e=closest(a.target,"smsessionblock");for(c=0;c<sessions.length;c++){var f=sessions[c];(f=document.getElementById("session_"+c))&&f.parentNode.removeChild(f)}sessions[e.sessionId]&&background.removeSession(sessions[e.sessionId].folderId,function(){sessions.splice(e.sessionId,1);createSessionList()})}})}
function renderConfirmBox(a,b){var c=$("#smrestorebase"),e=$("<div>",{"class":"confirmBox",style:"display:none"}).appendTo(c);e.fadeIn();c=$("<div>",{"class":"messageBox"});c.html(a);c.appendTo(e);a=$("<div>",{"class":"confirmButton"});a.html(chrome.i18n.getMessage("confirm"));a.click(function(){b(true);e.remove()});a.appendTo(e);a=$("<div>",{"class":"cancelButton"});a.html(chrome.i18n.getMessage("cancel"));a.click(function(){b(false);e.remove()});a.appendTo(e)}
function closest(a,b){for(;a&&a.className.indexOf(b)<0;)a=a.parentNode;return a}function saveToggle(){var a=$("#smsavelist .smcheck");a.first().attr("checked")?a.removeAttr("checked"):a.attr("checked",true);$("#smsavebase .smcheck").change()}function newToggle(){var a=$("#smeditlist1 .smcheck");a.first().attr("checked")?a.removeAttr("checked"):a.attr("checked",true);$("#smeditsession .smcheck").change()}
function savedToggle(){var a=$("#smeditlist2 .smcheck");a.first().attr("checked")?a.removeAttr("checked"):a.attr("checked",true);$("#smeditsession .smcheck").change()}
function exportSession(a){a=closest(a.target,"smsessionblock");sessions[a.sessionId]&&background.getSession(sessions[a.sessionId].folderId,function(b){var c="";c+="Name: "+b.title+"\n";c+="Date: "+b.date+"\n";c+="\n";for(var e=0;e<b.urls.length;++e){c+="Title: "+b.urls[e].title+"\n";c+="Url: "+b.urls[e].url+"\n";c+="\n"}showExportedSessionAsText(c)})}
function showExportedSessionAsText(a){$("#sessionTextBoxTips").html(chrome.i18n.getMessage("exportedSessionCopyTips"));$("#importSessionBtn").css("display","none");$("#sessionTextBox").fadeIn();$("#sessionTextBoxTextArea")[0].value=a;$("#sessionTextBoxTextArea")[0].select()}
function importSession(a){a=$("#sessionTextBoxTextArea")[0].value;console.log(a);a=a.split("\n");var b="imported session",c=new Date,e=c.getDate()+"/"+(c.getMonth()+1)+"/"+(c.getYear()+1900);c=[];for(var f="",g="",d=0;d<a.length;d++){if(a[d].indexOf("Name: ")>-1)b=a[d].replace("Name: ","");else if(a[d].indexOf("Date: ")>-1)e=a[d].replace("Date: ","");else if(a[d].indexOf("Title: ")>-1)f=a[d].replace("Title: ","");else if(a[d].indexOf("Url: ")>-1)g=a[d].replace("Url: ","");if(f!=""&&g!=""){c.push({url:g,
title:f});f=g=""}}a=new background.SessionData(b,e);for(d=0;d<c.length;d++)a.urls.push({url:c[d].url,title:c[d].title});a.urls.length>0&&background.saveSession(a);$("#sessionTextBox").fadeOut();createSessionList();window.close()}function showImportSessionBox(){$("#sessionTextBoxTips").html(chrome.i18n.getMessage("importedSessionTips"));$("#importSessionBtn").css("display","block");$("#sessionTextBoxTextArea")[0].value="";$("#sessionTextBox").fadeIn()};
