/*
FreshStart - License Agreement

Visibo Limited gives you permission to make verbatim copies of the 'FreshStart' software (the "Software") without restriction, so long as your copies include a copy of this license and all of the original copyright notices and associated disclaimers. You may not distribute modified source code. You may not charge a fee for the Software or claim that the Software is yours. You may not use the name Visibo to endorse or promote products derived from the Software without prior written permission.

THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE. UNDER NO CIRCUMSTANCES SHALL VISIBO LIMITED BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND RELATED TO OR ARISING OUT OF YOUR USE OF THE SOFTWARE, EVEN IF VISIBO LIMITED HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.

Copyright (c) 2009 Visibo Limited- contactus@visibotech.com. All rights reserved.

*/
var MAJOR_VERSION=1.4;function SessionData(a,e,d,c){this.title=a;this.date=e;this.urls=[];this.tabsCount=d;this.folderId=c}
function init(){try{localStorage.prevSession=localStorage.currentSession}catch(a){console.log(a)}try{localStorage.getItem("mysessions")&&localStorage.setItem("welcomeshown","true");if(!localStorage.getItem("welcomeshown")&&!localStorage.getItem("updateread")){localStorage.setItem("welcomeshown","true");localStorage.setItem("updateread",MAJOR_VERSION);chrome.bookmarks.getTree(function(d){chrome.bookmarks.getChildren(d[0].children[1].id,function(c){for(var b,f=0;f<c.length;++f)if(c[f].title=="FreshStart Sessions"){b=
c[f].id;break}b||chrome.tabs.create({url:"http://www.visibotech.com/FreshStart/welcome.html"})})})}}catch(e){}versionUpdate();changeBackupSetting()}var backupTimerId;
function changeBackupSetting(){if(localStorage.crashRestore=="true"){window.clearInterval(backupTimerId);var a=parseInt(localStorage.backupPeriod);if(isNaN(a)||a<1||a>1E3)a=5;backupTimerId=window.setInterval(saveBackupSession,6E4*a);console.log("Setting periodic backup period to "+60*a+" seconds")}else try{delete localStorage.currentSession;delete localStorage.prevSession;window.clearInterval(backupTimerId)}catch(e){console.log(e)}}
function versionUpdate(){try{var a=JSON.parse(localStorage.getItem("mysessions"));a&&getSessionFolder(function(d){for(var c=a.length-1;c>-1;c--){for(var b=0;b<a[c].urls.length;b++)a[c].urls[b]={title:a[c].urls[b],url:a[c].urls[b]};saveSessionToFolder(a[c],d)}delete localStorage.mysessions})}catch(e){console.log("Error: version update fail: "+e)}}
function initSession(a){getSessionFolder(function(e){chrome.bookmarks.getChildren(e,function(d){for(var c=[],b=0;b<d.length;b++){var f=d[b].title.match(/^(.*) \((\d+\/\d+\/\d+)\)--(\d+)tabs$/i);if(d[b].url!=null)console.log("Error: Not a sessions folder:"+d[b].title);else try{sessionData=new SessionData(f[1],f[2],f[3],d[b].id);c.push(sessionData)}catch(g){console.log("Error: wrong session format:"+d[b].title)}}a(c)})})}
function getSession(a,e){chrome.bookmarks.get(a,function(d){var c=d[0].title.match(/^(.*) \((\d+\/\d+\/\d+)\)--(\d+)tabs$/i);sessionData=new SessionData(c[1],c[2],c[3],d[0].id);chrome.bookmarks.getChildren(a,function(b){for(var f=0;f<b.length;f++)b[f].url&&sessionData.urls.push({id:b[f].id,url:b[f].url,title:b[f].title});e(sessionData)})})}
function restoreSession(a,e){chrome.bookmarks.getChildren(a,function(d){for(var c=[],b=0;b<d.length;b++)d[b].url&&c.push(d[b].url);if(e==0)chrome.windows.getLastFocused(function(f){chrome.windows.create({url:c[0],width:f.width,height:f.height},function(g){for(var h=1;h<c.length;h++)chrome.tabs.create({windowId:g.id,url:c[h]})})});else if(e==1)for(b=0;b<c.length;b++)chrome.tabs.create({url:c[b]})})}function removeSession(a,e){chrome.bookmarks.removeTree(a,e)}
function saveSession(a){getSessionFolder(function(e){saveSessionToFolder(a,e)})}function saveSessionToFolder(a,e,d){chrome.bookmarks.create({parentId:e,index:0,title:a.title+" ("+a.date+")--"+a.urls.length+"tabs"},function(c){for(var b=0;b<a.urls.length;b++)chrome.bookmarks.create({parentId:c.id,title:a.urls[b].title,url:a.urls[b].url})});bookmarkPositionWorkaround()}
function bookmarkPositionWorkaround(){setTimeout(function(){chrome.bookmarks.getChildren("0",function(a){chrome.bookmarks.create({parentId:a[0].id,url:"http://www.example.com"},function(e){chrome.bookmarks.remove(e.id)})})},500)}
function updateSession(a,e){chrome.bookmarks.getChildren(a.folderId,function(d){chrome.bookmarks.update(a.folderId,{title:a.title+" ("+a.date+")--"+a.urls.length+"tabs"});for(var c=0;c<d.length;++c)chrome.bookmarks.remove(d[c].id);for(c=0;c<a.urls.length;++c)chrome.bookmarks.create({parentId:a.folderId,title:a.urls[c].title,url:a.urls[c].url});bookmarkPositionWorkaround();e()})}
function getSessionFolder(a){var e,d;chrome.bookmarks.getTree(function(c){d=c[0].children[1].id;chrome.bookmarks.getChildren(d,function(b){for(var f=0;f<b.length;f++)if(b[f].title=="FreshStart Sessions"){e=b[f].id;break}e==null?chrome.bookmarks.create({parentId:d,title:"FreshStart Sessions"},function(g){e=g.id;a(e)}):a(e)})})}
function saveBackupSession(){chrome.windows.getAll(null,function(a){for(var e=[],d=0;d<a.length;d++)chrome.tabs.getAllInWindow(a[d].id,function(c){var b=new Date;b=b.getDate()+"/"+(b.getMonth()+1)+"/"+(b.getYear()+1900);b=new SessionData("currentSession",b);for(var f=0;f<c.length;f++){var g=c[f];b.urls.push({url:g.url,title:g.title})}e.push(b);localStorage.currentSession=JSON.stringify(e)})})}
function restoreCrashSession(a,e){try{var d=JSON.parse(localStorage.prevSession)[a].urls;if(e==0)chrome.windows.getLastFocused(function(b){chrome.windows.create({url:d[0].url,width:b.width,height:b.height},function(f){for(var g=1;g<d.length;g++)chrome.tabs.create({windowId:f.id,url:d[g].url})})});else if(e==1)for(a=0;a<d.length;a++)chrome.tabs.create({url:d[a].url})}catch(c){console.log(c)}};
