(function(){var e=devhd.pkg("control");var b=e.BaseControl.prototype;var f=e.createClass("TwitterControl",e.BaseControl);var c=devhd.log.get("control.twitter");var d=devhd.i18n.L;f.initialize=function(){b.initialize.call(this);this.completionModel={};this.charsize=140};f.setAnnotator=function(g){this.annotator=g};f.setTwitter=function(g){this.twitter=g
};f.setTinyURL=function(g){this.tinyURL=g};f.setPostfix=function(g){this.postfix=g};f.setEntry=function(g){this.entry=g};f.destroy=function(){this.twitterNoteElem=null;this.msgSizeElem=null;this.panelTwitterElem=null;this.panelSendingElem=null;this.twitter=null;this.annotator=null;this.tinyURL=null;this.entry=null;b.destroy.call(this)};f.display=function(){var i=this.getModel("message");
var g=this.getModel("url");var j=this.getModel("title");if(j==null&&this.entry!=null){j=this.entry.getCleanTitle()}if(g==null&&this.entry!=null){g=this.entry.getAlternateLink()}if(i!=null){this.doDisplay(i)}else{if(g==null){this.doDisplay(j)}else{this.part.innerHTML=templates.twitter.minimizing();var h=this;this.tinyURL.askTinyURL(g,function(m,k,l){h.doDisplay(j+" "+m,l)
},function(l,k){c.error(101,"failed to shorten URL because ",l);h.doDisplay(j+" "+g)})}}};f.doDisplay=function(i,h){if(this.isDestroyed()==true){return}this.part.innerHTML=templates.twitter.form(i,this.twitter.getScreenName(),this.postfix,this.twitter.getPhotoURL(),h);if(this.postfix!=""){try{var g=devhd.str.toSafeHTML(i).length+1;var k=this.element("twitterNote");
k.setSelectionRange(g,g)}catch(j){c.warn(130,"problem setting selection ",j)}}this.twitterNoteElem=this.element("twitterNote");this.msgSizeElem=this.element("msgSize");this.panelTwitterElem=this.element("panelTwitter");this.panelSendingElem=this.element("panelSending");this.bind("twitterCancelAction","click",f.cancelIt);this.bind("twitterSendAction","click",f.sendIt);
this.bind(this.part,"keydown",f.dispatchKeys);this.bind(this.part,"keyup",f.tweetSize);this.tweetSize();this.reset()};f.dispatchKeys=function(g){if(g.keyCode==27){this.cancelIt();devhd.events.cancelEvent(g);return}if((g.keyCode==77&&g.ctrlKey)||(g.keyCode==13&&(g.metaKey||g.ctrlKey))){this.sendIt();devhd.events.cancelEvent(g);return}};f.sendIt=function(){var k=a.call(this);
if(k.status.length>this.charsize){this.setMessage(d(520),1000);return}else{if(k.status.length==0){this.setMessage(d(521),1000);return}}var j=this;this.showSending();if(this.annotator!=null&&this.entry!=null){try{var i=this.getNote();i=i.replace("(via feedly)","");var m=i.indexOf("http://");if(m>-1){var h=i.indexOf(" ",m+1);if(h>-1){i=devhd.utils.StringUtils.trim(i.slice(h))
}}var g={type:"twitter.tweet",userId:this.home.getUserId(),note:i,feedId:this.entry.getFeedId()};this.annotator.askSaveMarkersForEntry(this.entry,[g])}catch(l){c.warn(222,"failed to save twitter annotation ",l)}}this.twitter.askUpdate(k,function(){j.fire("onControlDoneSending",d(d(531)))},function(n,o){j.showPanel();j.setMessage(d(d(522),o),1000)})};
f.cancelIt=function(){this.fire("onControlDoneSending")};f.getNote=function(){return devhd.str.trim(this.twitterNoteElem.value)};f.reset=function(){if(this.twitterNoteElem==null){return}this.showPanel();this.twitterNoteElem.focus()};f.showPanel=function(){this.panelSendingElem.style.display="none";this.panelTwitterElem.style.display="block"};f.showSending=function(){this.panelSendingElem.style.display="block";
this.panelTwitterElem.style.display="none"};f.tweetSize=function(){var g=(this.charsize-this.twitterNoteElem.value.length);this.msgSizeElem.innerHTML=""+g;if(g<0){this.msgSizeElem.style.color="red"}else{if(g<10){this.msgSizeElem.style.color="orange"}else{this.msgSizeElem.style.color="#1a3f7a"}}};function a(){var g={status:this.getNote()};if(this.entry!=null){g.entryId=this.entry.getId()
}return g}})();