(function(){var h=devhd.pkg("control");var d=h.BaseControl.prototype;var f=h.createClass("WallControl",h.BaseControl);var m=devhd.log.get("control.wall");var i=devhd.i18n.L;f.initialize=function(){d.initialize.call(this);this.completionModel={};this.charsize=132};f.setPreferences=function(n){this.preferences=n};f.setReader=function(n){this.reader=n;
this.reader.registerObserver(this)};f.setAnnotator=function(n){this.annotator=n;this.annotator.registerObserver(this)};f.setFriendfeed=function(n){this.friendfeed=n};f.setDigg=function(n){this.digg=n};f.setTinyURL=function(n){this.tinyURL=n};f.setTwitter=function(n){this.twitter=n};f.setContext=function(n){this.context=n;this.key=this.context.entryId||this.context.url;
this.entry=this.context.entry};f.setReadOnly=function(n){this.readOnly=n==true};f.destroy=function(){if(this.reader!=null){this.reader.unregisterObserver(this)}if(this.annotator!=null){this.annotator.unregisterObserver(this)}if(this.context!=null){delete this.context.entry}this.context=null;this.reader=null;this.annotator=null;this.friendfeed=null;this.digg=null;
this.preferences=null;this.twitter=null;this.tinyURL=null;d.destroy.call(this)};f.display=function(){try{this.part.innerHTML=templates.control.wall.layoutWallControl(this.key,this.home);var n=this;g.call(this);l.call(this);a.call(this);b.call(this)}catch(o){m.error(115," failed to display ",o)}};function a(){this.element(this.key+"_commentsHolder").innerHTML=templates.control.wall.commentsLoading(this.home);
var n=this;this.annotator.askCommentsForEntry(this.entry.getAlternateLink(),function(o){if(n.isDestroyed()==true){return}k.call(n,o)},function(o,p){if(n.isDestroyed()==true){return}j.call(n,o,p)},function(){if(n.isDestroyed()==true){return}c.call(n)})}function k(n){if(n.channel){this.element(this.key+"_commentsHolder").innerHTML=templates.control.wall.rss2comments(this.entry,n,this.home)
}else{this.element(this.key+"_commentsHolder").innerHTML=templates.control.wall.atom2comments(this.entry,n,this.home)}}function j(o,n){this.element(this.key+"_commentsHolder").style.display="none"}function c(){this.element(this.key+"_commentsHolder").style.display="none"}function l(){if(this.preferences.get("friendfeedConversations")!="yes"){this.element(this.key+"_friendfeedOverheardHolder").innerHTML="";
return}var n=this;this.friendfeed.askResolveConversationsByURL(this.entry.getAlternateLink(),true,function(s){if(n.isDestroyed()==true){return}try{var p=[];for(var q=0;q<s.length;q++){if(s[q].likes.length==0&&s[q].comments.length==0){continue}if((s[q].title.indexOf(n.entry.getTitle()))==-1){continue}if(n.entry.getTitle().split(" ").length==1&&s[q].title!=n.entry.getTitle()){continue
}p.push(s[q])}n.ffConversations=p;if(n.ffConversations.length>0){var o=n.element(n.key+"_friendfeedOverheardHolder");o.innerHTML=templates.control.wall.friendfeedOverheard(n.ffConversations,true,n.home)}else{n.element(n.key+"_friendfeedOverheardHolder").innerHTML=""}}catch(r){n.element(n.key+"_friendfeedOverheardHolder").innerHTML="";m.error(222,"failed to resolve conversation ",r)
}},function(p,o){if(n.isDestroyed()==true){return}m.error(230,"friendfeed search error ",p," -- ",n.entry.getTitle());n.element(n.key+"_friendfeedOverheardHolder").innerHTML=""})}function b(){var n=this;this.tinyURL.askURLStats(this.entry.getAlternateLink(),function(o){if(n.isDestroyed()==true){return}if(o==null||o.clicks==0){return}n.element(n.entry.getId()+"_liveHolder").innerHTML=templates.control.wall.live(n.entry,o);
n.twitter.askSearch({q:"http://bit.ly/"+o.hash,rpp:50},function(r){try{if(n.isDestroyed()){return}var p=[];for(var q=r.length-1;q>=0;q--){if(r[q].text.indexOf("http://bit.ly/"+o.hash)>-1){p.push(r[q])}}n.element(n.entry.getId()+"_tweets").innerHTML=templates.page.base.tweetStream(p,10,p[0],this.twitterId)}catch(s){}})})}function g(){var n=this;this.digg.askStoryInfo(this.entry.getAlternateLink(),true,function(o){if(n.isDestroyed()==true){return
}if(o==null){return}n.element(n.key+"_diggHolder").innerHTML=templates.control.wall.digg(n.entry,o);if(o.comments>0){e.call(n,o.id,o.comments,o.href)}})}function e(q,o,n){var p=this;this.digg.askComments(q,function(r){if(p.isDestroyed()==true){return}if(r==null||r.length==0){return}p.element(p.key+"_diggComments").innerHTML=templates.control.wall.diggComments(p.entry,r,o,n)
})}})();