/*
TooManyTabs for Chrome - License Agreement

Visibo Limited gives you permission to make verbatim copies of the 'TooManyTabs for Chrome' software (the "Software") without restriction, so long as your copies include a copy of this license and all of the original copyright notices and associated disclaimers. You may not distribute modified source code. You may not charge a fee for the Software or claim that the Software is yours. You may not use the name Visibo to endorse or promote products derived from the Software without prior written permission.

THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE. UNDER NO CIRCUMSTANCES SHALL VISIBO LIMITED BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND RELATED TO OR ARISING OUT OF YOUR USE OF THE SOFTWARE, EVEN IF VISIBO LIMITED HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.

Copyright (c) 2009 Visibo Limited- contactus@visibotech.com. All rights reserved.
*/
var TABAREA_WIDTH=620,TMTAREA_HEIGHT=430,MAJOR_VERSION=1.2,tabDataMapRef,tabRegistryRef,currentRow,maxTabIconOrder,extraTabAreaNeeded=0,separatorTabIconOrder,resizedTimes=0,smallMode=false;
function createTabIcon(a){var b=document.getElementById("innertabarea"),c=document.createElement("div");c.setAttribute("class","tabexterior");c.setAttribute("id","tab"+a);c.tabId=a;var d=document.createElement("div");d.setAttribute("class","tabinterior");var e=document.createElement("img");e.setAttribute("class","tabimage");e.setAttribute("id","tabimg"+a);e.src="sample_screen.png";e.title=tabDataMapRef[a].URL[tabDataMapRef[a].URL.length-1];e.addEventListener("click",onTabSelect);e.tabId=a;var f=document.createElement("div");
f.setAttribute("class","tabtitle");f.textContent=tabDataMapRef[a].title;f.title=tabDataMapRef[a].title;f.addEventListener("click",onTabSelect);f.tabId=a;var g=document.createElement("img"),h=chrome.extension.getURL("tmtchrome_defaulticon.png");g.setAttribute("class","tabfavicon");g.src=tabDataMapRef[a].favIconURL?tabDataMapRef[a].favIconURL:h;h=document.createElement("div");h.setAttribute("class","tabpopicon");h.addEventListener("click",onTabPop);h.title="Click to pop this tab to TooManyTabs column";
h.tabId=a;var j=document.createElement("div");j.setAttribute("class","tabclosebutton");j.addEventListener("click",onTabClose);j.title="Click to close";j.tabId=a;d.appendChild(e);c.appendChild(d);c.appendChild(f);c.appendChild(g);c.appendChild(h);c.appendChild(j);b.appendChild(c);setTimeout(function(){loadScreenCap(a)},Math.random()*500)}function loadScreenCap(a){var b=document.getElementById("tabimg"+a);if(b)if(tabDataMapRef[a].screenCap)b.src=tabDataMapRef[a].screenCap}
function placeTabIcon(a){a=document.getElementById("tab"+a);var b=a.order,c=Math.floor(b/5),d=b%5;if(b>=separatorTabIconOrder){b=b+5+(4-(separatorTabIconOrder-1)%5);c=Math.floor(b/5);d=b%5}a.setAttribute("style","left:"+(20+c*185+d%2*20)+"px; top:"+d*100+"px; z-index:"+(100+d)+";")}
function onTabSelect(a){var b=a.currentTarget;chrome.windows.getLastFocused(function(c){if(tabDataMapRef[b.tabId]){var d=document.getElementById("errordisplay");d.setAttribute("style","opacity:1.0;");d.textContent="Contacting tab...";chrome.tabs.update(b.tabId,{selected:true});chrome.tabs.get(b.tabId,function(f){f.selected==true&&tabDataMapRef[b.tabId].windowId==c.id&&window.close()});var e=c.id;if(window.location.search.indexOf("tmtwindow")!=-1)e=chrome.extension.getBackgroundPage().lastFocusId;
if(tabDataMapRef[b.tabId].windowId!=e){chrome.extension.getBackgroundPage().askTabToFocus(b.tabId);window.location.search.indexOf("tmtwindow")!=-1?setTimeout(function(){chrome.tabs.move(b.tabId,{windowId:e,index:0});chrome.tabs.update(b.tabId,{selected:true});window.close()},600):setTimeout(function(){chrome.tabs.move(b.tabId,{windowId:e,index:0});chrome.tabs.update(b.tabId,{selected:true});setTimeout(function(){var f=document.getElementById("errordisplay");f.textContent="Hm, no response from that tab. Either it is a system panel, or it's busy...";
setTimeout(function(){f.textContent=""},3E3)},500)},600)}else window.close()}})}function onTabClose(a){cancelTMTContextMenu();var b=a.currentTarget;chrome.tabs.remove(b.tabId,function(){var c=document.getElementById("tab"+b.tabId);if(c.order==maxTabIconOrder)maxTabIconOrder-=1;document.getElementById("innertabarea").removeChild(c)})}var lastSortedOrder;
function sortTabs(a){maxTabIconOrder=0;var b=[],c=chrome.extension.getBackgroundPage();if(a!="keyword"){var d=document.getElementById("numsearchresults"),e=document.getElementById("searchseparator");d.setAttribute("style","left:"+(20+Math.floor(separatorTabIconOrder/5)*185)+"px; top:"+(separatorTabIconOrder%5*100+20)+"px;");e.setAttribute("style","left:"+(120+(Math.floor(separatorTabIconOrder/5)+1)*185)+"px;");d=document.getElementById("searchbox");d.value="";extraTabAreaNeeded=0;adjustInnerArea()}if(a==
"tabid"){for(i=0;i<tabRegistryRef.length;i++){a=document.getElementById("tab"+tabRegistryRef[i]);a.order=tabRegistryRef.length-i-1;if(a.order>maxTabIconOrder)maxTabIconOrder=a.order}for(i=tabRegistryRef.length-1;i>=0;i--)b.push(tabRegistryRef[i]);separatorTabIconOrder=99999;lastSortedOrder=b;c.lastOrder="tabid"}else if(a=="name"){for(i=0;i<tabRegistryRef.length;i++)b.push(tabRegistryRef[i]);b.sort(nameSortFunction);for(i=0;i<tabRegistryRef.length;i++){a=document.getElementById("tab"+b[i]);a.order=
i;if(a.order>maxTabIconOrder)maxTabIconOrder=a.order}separatorTabIconOrder=99999;lastSortedOrder=b;c.lastOrder="name"}else if(a=="domain"){for(i=0;i<tabRegistryRef.length;i++)b.push(tabRegistryRef[i]);b.sort(domainSortFunction);for(i=0;i<tabRegistryRef.length;i++){a=document.getElementById("tab"+b[i]);a.order=i;if(a.order>maxTabIconOrder)maxTabIconOrder=a.order}separatorTabIconOrder=99999;lastSortedOrder=b;c.lastOrder="domain"}else if(a=="keyword"){for(i=0;i<tabRegistryRef.length;i++)b.push(tabRegistryRef[i]);
separatorTabIconOrder=0;b.sort(keywordSortFunction);for(i=0;i<tabRegistryRef.length;i++){a=document.getElementById("tab"+b[i]);a.order=i;if(a.order>maxTabIconOrder)maxTabIconOrder=a.order}d=document.getElementById("searchbox");b=d.value.toLowerCase();for(i=separatorTabIconOrder=0;i<tabRegistryRef.length;i++)if(tabDataMapRef[tabRegistryRef[i]].title.toLowerCase().indexOf(b)!=-1||tabDataMapRef[tabRegistryRef[i]].URL[tabDataMapRef[tabRegistryRef[i]].URL.length-1].toLowerCase().indexOf(b)!=-1)separatorTabIconOrder++}}
function nameSortFunction(a,b){if(!tabDataMapRef[a].title)return 1;if(!tabDataMapRef[b].title)return 1;return tabDataMapRef[a].title.toLowerCase()<tabDataMapRef[b].title.toLowerCase()?-1:1}function domainSortFunction(a,b){return tabDataMapRef[a].URL[tabDataMapRef[a].URL.length-1]<tabDataMapRef[b].URL[tabDataMapRef[b].URL.length-1]?-1:1}
function keywordSortFunction(a,b){var c=document.getElementById("searchbox").value.toLowerCase();if(!tabDataMapRef[a].title)tabDataMapRef[a].title="untitled";if(!tabDataMapRef[b].title)tabDataMapRef[b].title="untitled";var d=tabDataMapRef[a].title.toLowerCase().indexOf(c),e=tabDataMapRef[b].title.toLowerCase().indexOf(c),f=tabDataMapRef[a].URL[tabDataMapRef[a].URL.length-1].toLowerCase().indexOf(c);c=tabDataMapRef[b].URL[tabDataMapRef[b].URL.length-1].toLowerCase().indexOf(c);console.log(tabDataMapRef[a].URL[tabDataMapRef[a].URL.length-
1].toLowerCase()+" "+f);if(f!=-1)d=f;if(c!=-1)e=c;if(d==-1&&e==-1){a=lastSortedOrder.indexOf(a);b=lastSortedOrder.indexOf(b);return a<b?-1:1}else if(d!=-1&&e!=-1){a=lastSortedOrder.indexOf(a);b=lastSortedOrder.indexOf(b);return a<b?-1:1}else return d==-1?1:-1}var sortingTimer,sortingTimer2;
function sortTabsCommand(a){sortingTimer&&clearTimeout(sortingTimer);sortingTimer2&&clearTimeout(sortingTimer2);sortTabs(a);doTabAreaAnimation(6);sortingTimer=setTimeout(function(){for(i=0;i<tabRegistryRef.length;i++)placeTabIcon(tabRegistryRef[i]);moveInnerArea(0,0)},180)}
function findTabsCommand(){var a=document.getElementById("searchbox").value.toLowerCase().trim();console.log(a);sortingTimer&&clearTimeout(sortingTimer);sortTabs("keyword");sortingTimer=setTimeout(function(){for(i=0;i<tabRegistryRef.length;i++)placeTabIcon(tabRegistryRef[i]);moveInnerArea(0,0);var b=document.getElementById("numsearchresults"),c=document.getElementById("searchseparator");if(separatorTabIconOrder<tabRegistryRef.length){b.textContent=separatorTabIconOrder+" tab match(es)";b.setAttribute("style",
"left:"+(20+Math.floor(separatorTabIconOrder/5)*185)+"px; top:"+(separatorTabIconOrder%5*100+20)+"px;");c.setAttribute("style","left:"+(120+(Math.floor(separatorTabIconOrder/5)+1)*185)+"px;");extraTabAreaNeeded=4-(separatorTabIconOrder-1)%5+5}else{b.setAttribute("style","left:0px; top:600px;");c.setAttribute("style","left: -10px;");extraTabAreaNeeded=0}adjustInnerArea()},200)}
function doTabAreaAnimation(a){if(!(a<=0)){var b=document.getElementById("tabarea");if(a==6)b.setAttribute("style","top:70px; opacity:0.75;");else if(a==5)b.setAttribute("style","top:85px; opacity:0.33;");else if(a==4)b.setAttribute("style","top:90px; opacity:0.0;");else if(a==3)b.setAttribute("style","top:85px; opacity:0.33;");else if(a==2)b.setAttribute("style","top:70px; opacity:0.75;");else a==1&&b.setAttribute("style","");sortingTimer2=setTimeout(function(){doTabAreaAnimation(a-1)},60)}}
function createTMTTab(a){var b=document.getElementById("innertmtarea"),c=document.createElement("div");c.setAttribute("class","tmttab");c.setAttribute("id","tmt"+a);c.index=a;var d=document.createElement("div");d.setAttribute("class","tmttabiconbox");var e=document.createElement("img");e.setAttribute("class","tmttabicon");e.src=currentRow.tabs[a].favIconURL?currentRow.tabs[a].favIconURL:"http://code.google.com/favicon.ico";d.appendChild(e);e=document.createElement("div");e.setAttribute("class","tmttabtitle");
e.textContent=currentRow.tabs[a].title;e.title="Click to restore '"+currentRow.tabs[a].title+"'";e.addEventListener("click",onTabRestore);d.addEventListener("click",onTMTContextMenu);c.appendChild(d);c.appendChild(e);b.appendChild(c)}function removeTMTTab(a){var b=document.getElementById("tmt"+a);document.getElementById("innertmtarea").removeChild(b);a=a+1;for(b=document.getElementById("tmt"+a);b;){b.index=a-1;b.setAttribute("id","tmt"+b.index);a++;b=document.getElementById("tmt"+a)}}
function onTabPop(a){cancelTMTContextMenu();var b=a.currentTarget;a=chrome.extension.getBackgroundPage();a.currentRowId==3&&nextTMTRow();a.popTab(b.tabId);var c=document.getElementById("tab"+b.tabId);if(c.order==maxTabIconOrder)maxTabIconOrder-=1;b=document.getElementById("innertabarea");b.removeChild(c);currentRow=a.getCurrentRow();if(!currentRow){console.log("chrome-background-ref-bug-fix active");c=JSON.parse(localStorage.getItem("currentRowId"));currentRow=a.rowDataMap[c]}createTMTTab(currentRow.tabs.length-
1);a=parseInt(document.defaultView.getComputedStyle(b).getPropertyValue("height").replace("px",""));moveTMTArea(-0.15*a,6)}
function onTabRestore(a){cancelTMTContextMenu();var b=a.currentTarget.parentNode.index;a=chrome.extension.getBackgroundPage();var c=false;if(window.location.search.indexOf("tmtwindow")!=-1)c=true;a.restoreTab(b,c,function(d,e){createTabIcon(d);d=document.getElementById("tab"+d);maxTabIconOrder+=1;d.order=maxTabIconOrder;console.log("restored.order = "+d.order+", restored id = "+d.tabId);placeTabIcon(d.tabId);e&&removeTMTTab(b);adjustInnerArea();e=document.getElementById("innertabarea");e=parseInt(e.style.width.replace("px",
""));moveInnerArea(-0.125*e,6)})}function onTabRemove(a){a=document.getElementById("tmtcontextmenu");chrome.extension.getBackgroundPage().removeTabInRow(a.index);removeTMTTab(a.index)}function onTMTContextMenu(a){var b=document.getElementById("tmtcontextmenu"),c=a.currentTarget.parentNode.index;b.setAttribute("style","top:"+a.pageY+"px;");b.index=c}function cancelTMTContextMenu(){document.getElementById("tmtcontextmenu").setAttribute("style","top:600px;")}
function clearTMTArea(){var a=chrome.extension.getBackgroundPage();currentRow=a.getCurrentRow();if(!currentRow){console.log("chrome-background-ref-bug-fix active");var b=JSON.parse(localStorage.getItem("currentRowId"));currentRow=a.rowDataMap[b]}a=document.getElementById("innertmtarea");for(i=0;i<currentRow.tabs.length;i++){b=document.getElementById("tmt"+i);a.removeChild(b)}(b=document.getElementById("clearallbutton"))&&a.removeChild(b);moveTMTArea(1E3,4)}
function fillTMTArea(){var a=chrome.extension.getBackgroundPage();currentRow=a.getCurrentRow();if(!currentRow){console.log("chrome-background-ref-bug-fix active");var b=JSON.parse(localStorage.getItem("currentRowId"));currentRow=a.rowDataMap[b]}document.getElementById("tmtrowlabel").textContent=currentRow.name;document.getElementById("tmtrowtip").textContent=currentRow.tip;for(i=0;i<currentRow.tabs.length;i++)createTMTTab(i);b=document.getElementById("innertmtarea");if(a.currentRowId==3){a=document.createElement("div");
a.setAttribute("class","tmtclearallbutton");a.setAttribute("id","clearallbutton");a.textContent="Clear All";a.addEventListener("click",clearAllTMTTabs,false);b.appendChild(a)}}
function clearAllTMTTabs(a){a=chrome.extension.getBackgroundPage();currentRow=a.getCurrentRow();if(!currentRow){console.log("chrome-background-ref-bug-fix active");var b=JSON.parse(localStorage.getItem("currentRowId"));currentRow=a.rowDataMap[b]}b=document.getElementById("innertmtarea");var c=currentRow.tabs.length;for(i=0;i<c;i++){var d=document.getElementById("tmt"+i);b.removeChild(d);a.removeTabInRow(0)}}
function nextTMTRow(){clearTMTArea();chrome.extension.getBackgroundPage().nextRow();fillTMTArea()}function prevTMTRow(){clearTMTArea();chrome.extension.getBackgroundPage().prevRow();fillTMTArea()}
function main(){if(localStorage.getItem("popupsize"))if(localStorage.getItem("popupsize")=="narrow")document.body.setAttribute("style","width:680px; height:600px;");else if(localStorage.getItem("popupsize")=="small"){document.body.setAttribute("style","width:620px; height:450px;");smallMode=true}localStorage.getItem("updateread")&&localStorage.getItem("updateread")>=MAJOR_VERSION&&document.getElementById("logoarea").setAttribute("style","display:none; ");var a=chrome.extension.getBackgroundPage();
tabDataMapRef=a.tabDataMap;document.getElementById("innertabarea").addEventListener("mousewheel",mouseWheelMoveInnerArea,false);chrome.windows.getLastFocused(function(b){b=b.id;if(window.location.search.indexOf("tmtwindow")!=-1)b=chrome.extension.getBackgroundPage().lastFocusId;tabRegistryRef=a.tabRegistry[b];adjustInnerArea();var c;c=document.getElementById("innertabarea");for(c=0;c<tabRegistryRef.length;c++)tabDataMapRef[tabRegistryRef[c]].windowId==b&&createTabIcon(tabRegistryRef[c]);a.lastOrder?
sortTabs(a.lastOrder):sortTabs("tabid");for(c=0;c<tabRegistryRef.length;c++)tabDataMapRef[tabRegistryRef[c]].windowId==b&&placeTabIcon(tabRegistryRef[c]);moveInnerArea(0,0);fillTMTArea();document.getElementById("tmtlistbox").addEventListener("mousewheel",mouseWheelMoveTMTArea,false);moveTMTArea(0,0);b=a.getThemeColor();changeBackground(b);chrome.tabs.getSelected(null,function(d){d=document.getElementById("tab"+d.id);var e=document.createElement("div");e.setAttribute("id","youareheresign");d.appendChild(e)});
document.getElementById("searchbox").focus()})}function adjustInnerArea(){var a=document.getElementById("innertabarea"),b=tabRegistryRef.length;if(maxTabIconOrder)b=maxTabIconOrder+extraTabAreaNeeded;b=(Math.ceil((b+1)/5)+1)*180+20;if(b<TABAREA_WIDTH)b=TABAREA_WIDTH;a.style.width=b+"px"}
function moveInnerArea(a,b){cancelTMTContextMenu();var c=document.getElementById("leftarrow"),d=document.getElementById("rightarrow"),e=document.getElementById("innertabarea"),f=parseInt(e.style.left.replace("px",""))+a,g=parseInt(e.style.width.replace("px",""));if(g>TABAREA_WIDTH){c.style.opacity=1;d.style.opacity=1}else{c.style.opacity=0.5;d.style.opacity=0.5}if(f<TABAREA_WIDTH-g){f=TABAREA_WIDTH-g;d.style.opacity=0.5}if(f>=0){f=0;c.style.opacity=0.5}e.style.left=f+"px";b!=0&&setTimeout(function(){moveInnerArea(a,
b-1)},50)}function mouseWheelMoveInnerArea(a){smallMode!=true&&moveInnerArea(a.wheelDelta/10,4)}
function moveTMTArea(a,b){cancelTMTContextMenu();var c=document.getElementById("uparrow"),d=document.getElementById("downarrow"),e=document.getElementById("innertmtarea"),f=parseInt(e.style.top.replace("px",""))+a,g=parseInt(document.defaultView.getComputedStyle(e).getPropertyValue("height").replace("px",""));if(g>TMTAREA_HEIGHT){c.style.opacity=1;d.style.opacity=1}else{c.style.opacity=0.5;d.style.opacity=0.5}if(f<TMTAREA_HEIGHT-g){f=TMTAREA_HEIGHT-g;d.style.opacity=0.5}if(f>=0){f=0;c.style.opacity=
0.5}e.style.top=f+"px";b!=0&&setTimeout(function(){moveTMTArea(a,b-1)},50)}function mouseWheelMoveTMTArea(a){moveTMTArea(a.wheelDelta/10,4)}
function changeBackground(a){var b=document.getElementById("basebox");if(a==0)b.setAttribute("style","background:-webkit-gradient(linear, left top, left bottom, from(#00abeb), to(rgba(45,72,101,1)));");else if(a==1)b.setAttribute("style","background:-webkit-gradient(linear, left top, left bottom, from(#CCCCCC), to(#4F6D80));");else if(a==2)b.setAttribute("style","background:-webkit-gradient(linear, left top, left bottom, from(#f8ae32), to(#Af6e00));");else if(a==3)b.setAttribute("style","background:#E6E6E6");
else a==4&&b.setAttribute("style","background:-webkit-gradient(linear, left top, left bottom, from(#444455), to(#000000));");chrome.extension.getBackgroundPage().setThemeColor(a)};
