(function(){var e=devhd.pkg("control");var G=e.BaseControl.prototype;var h=e.createClass("EntryControl",e.BaseControl);var l=devhd.log.get("control.entry");var w=devhd.i18n.L;h.initialize=function(){G.initialize.call(this)};h.setEntryId=function(H){this.entryId=H};h.setWidth=function(H){this.width=H};h.setSelectedEntryId=function(H){this.selectedEntryId=H
};h.setReader=function(H){this.reader=H;this.reader.registerObserver(this)};h.setAnnotator=function(H){this.annotator=H;this.annotator.registerObserver(this)};h.setPreferences=function(H){this.preferences=H};h.setSigns=function(H){this.signs=H};h.setFriendfeed=function(H){this.friendfeed=H};h.setDigg=function(H){this.digg=H};h.setTumblr=function(H){this.tumblr=H
};h.setFeedly=function(H){this.feedly=H};h.setSearchTerm=function(H){this.searchTerm=H};h.setReco=function(H){this.reco=H};h.setPopup=function(H){this.popup=H};h.setProfile=function(H){this.profile=H};h.setTwitter=function(H){this.twitter=H};h.setTinyURL=function(H){this.tinyURL=H};h.setAnalytics=function(H){this.analytics=H};h.setCalais=function(H){this.calais=H
};h.setAmazon=function(H){this.amazon=H};h.setShowSourceTitle=function(H){this.showSourceTitle=H};h.setOnLayoutReady=function(H){this.onLayoutReady=H};h.setIo=function(H){this.io=H};h.setBack=function(H){this.back=H};h.destroy=function(){if(this.postProcessingTimer!=null){this.home.getDocument().defaultView.clearTimeout(this.postProcessingTimer);this.postProcessingTimer=null
}if(this.annotator!=null){this.annotator.unregisterObserver(this);this.annotator=null}if(this.reader!=null){this.reader.unregisterObserver(this);this.reader=null}if(this.wall!=null){this.wall.destroy();this.wall=null}this.preferences=null;this.signs=null;this.friendfeed=null;this.digg=null;this.tumblr=null;this.feedly=null;this.searchTerm=null;this.reco=null;
this.popup=null;this.profile=null;this.analytics=null;this.calais=null;this.amazon=null;this.io=null;this.twitter=null;this.tinyURL=null;this.back=null;this.onLayoutReady=null;this.part.innerHTML="";G.destroy.call(this);this.entry=null};h.display=function(){var H=this;this.bind(this.part,"mouseup",h.processSelection);this.bind(this.part,"click",h.processClick);
this.reader.askStreamContent([H.entryId],function(){if(H.isDestroyed()){return true}z.call(H)},function(){if(H.isDestroyed()){return true}t.call(H)})};function t(){this.part.innerHTML=w(w(299),this.entryId);return}function z(){if(this.part==null){return}this.reader.markEntryAsRead(this.entryId);this.entry=this.reader.lookupEntry(this.entryId);var I=v(this.entry);
var H=this;I.call(this,function(){if(H.isDestroyed()==true){return}var K=H.element(H.entryId+"_entryHolder");devhd.utils.ArrayUtils.forEach(K.getElementsByTagName("a"),function(L){L.target="_blank"});var J=H.element(H.entry.getId()+"_entryContent");devhd.utils.ArrayUtils.forEach(J.getElementsByTagName("img"),function(L){H.bind(L,"load",y)});devhd.utils.ArrayUtils.forEach(J.getElementsByTagName("iframe"),function(L){L.style.display="none"
});if(H.onLayoutReady!=null){devhd.fn.callback(H.onLayoutReady)}H.postProcessingTimer=H.home.getDocument().defaultView.setTimeout(function(){if(H.postProcessingTimer==null){return}if(H.isDestroyed()==true){return}H.home.getDocument().defaultView.clearTimeout(H.postProcessingTimer);H.postProcessingTimer=null;c.call(H)},100)})}function y(K){if(this.isDestroyed()==true){return
}var L=K.target;if(L.src.indexOf("http://api.tweetmeme.com")>-1){L.style.display="none";return}if(this.comments!=null){this.comments.reflow()}var H=Math.min(this.width-40,731);var I=parseInt(L.width);var J=parseInt(L.height);if(!isNaN(I)&&!isNaN(J)&&I>0){L.style.maxHeight=(H*J/I)+"px"}L.style.maxWidth=H+"px"}function v(H){var I=H.getAlternateLink();
if(I.indexOf("www.charlierose.com")!=-1){return k}if(I.indexOf("hulu.com")!=-1){return E}if(I.indexOf("www.thedailyshow.com")!=-1){return u}if(I.indexOf("www.ted.com")!=-1){return f}if(I.indexOf("/TED")!=-1){return f}if(I.indexOf("collegehumor.com")!=-1){return q}return D}function D(I){var H={subscription:this.reader.lookupSimilarSubscription(this.entry.getFeedInfo()),searchTerm:this.searchTerm,maxWidth:this.width-40,showSourceTitle:this.showSourceTitle};
this.part.innerHTML=templates.control.entry.layout(this.entry,H,this.width,this.home);devhd.fn.callback(I)}var r=/rel="video_src" href="([^"]*)"/i;function k(J){var I=this;var H={subscription:I.reader.lookupSimilarSubscription(I.entry.getFeedInfo()),searchTerm:I.searchTerm,maxWidth:I.width-30,showSourceTitle:I.showSourceTitle};I.part.innerHTML=templates.control.entry.customizable(templates.control.entry.charlieRoseFrame,I.entry,H,I.width,I.home);
this.io.get(this.entry.getAlternateLink(),function(K){if(I.isDestroyed()==true){return}var L=devhd.utils.RegExUtils.select(r,K).split("?");if(L.length!=2){D.call(I,J);return}I.entry.charlieRose={playerURL:L[0],videoId:L[1]};I.element(I.entry.getId()+"_cr").innerHTML=templates.control.entry.charlieRoseVideo(I.entry);devhd.fn.callback(J)},function(K){if(I.isDestroyed()==true){return
}I.element(I.entry.getId()+"_cr").innerHTML="Error:"+K})}var C=/rel="video_src" href="([^"]*)"/i;function E(J){var I=this;var H={subscription:I.reader.lookupSimilarSubscription(I.entry.getFeedInfo()),searchTerm:I.searchTerm,maxWidth:I.width-30,showSourceTitle:I.showSourceTitle};I.part.innerHTML=templates.control.entry.customizable(templates.control.entry.huluFrame,I.entry,H,I.width,I.home);
this.io.get(this.entry.getAlternateLink(),function(K){if(I.isDestroyed()==true){return}I.entry.hulu=devhd.utils.RegExUtils.select(C,K);I.element(I.entry.getId()+"_hu").innerHTML=templates.control.entry.huluVideo(I.entry);devhd.fn.callback(J)},function(K){I.element(I.entry.getId()+"_hu").innerHTML="Error:"+K})}var g=/addVariable\("fms","([^"]*)"/i;var n=/addVariable\("hs","([^"]*)"/i;
var B=/addVariable\("ls","([^"]*)"/i;var b=/addVariable\("vw","([^"]*)"/i;var m=/addVariable\("vh","([^"]*)"/i;var x=/addVariable\("ti","([^"]*)"/i;var a=/addVariable\("fd","([^"]*)"/i;var p=/addVariable\("pd","([^"]*)"/i;var j=/var moduleName = "([^"]*)"/i;var A=/(<embed[^>]*>)/i;var o=/var topicID = ([^;]*);/i;function f(J){var I=this;var H={subscription:I.reader.lookupSimilarSubscription(I.entry.getFeedInfo()),searchTerm:I.searchTerm,maxWidth:I.width-30,showSourceTitle:I.showSourceTitle};
I.part.innerHTML=templates.control.entry.customizable(templates.control.entry.tedFrame,I.entry,H,I.width,I.home);this.io.get(this.entry.getAlternateLink(),function(N){if(I.isDestroyed()==true){return}if(N.indexOf(".addVariable")!=-1){I.entry.ted={fms:devhd.utils.RegExUtils.select(g,N),hs:devhd.utils.RegExUtils.select(n,N),ls:devhd.utils.RegExUtils.select(B,N),vw:devhd.utils.RegExUtils.select(b,N),vh:devhd.utils.RegExUtils.select(m,N),ti:devhd.utils.RegExUtils.select(x,N),fd:devhd.utils.RegExUtils.select(a,N),pd:devhd.utils.RegExUtils.select(p,N)};
I.element(I.entry.getId()+"_ted").innerHTML=templates.control.entry.tedVideo(I.entry);devhd.fn.callback(J)}else{if(N.indexOf("<embed")!=-1){var M=devhd.utils.RegExUtils.select(A,N);I.element(I.entry.getId()+"_ted").innerHTML=templates.control.entry.embeddedTedVideo(M,I.entry);devhd.fn.callback(J)}else{D.call(I,J)}}var L=devhd.utils.RegExUtils.select(j,N);
var K=devhd.utils.RegExUtils.select(o,N);I.io.get("http://www.ted.com/comments/viewRPC/modulename/"+L+"/topicID/"+K+"/page/1/limit/30",function(P){try{var O=devhd.utils.JSONUtils.decode(P);if(O.resultSet!=null&&O.resultSet.result!=null){I.element(I.entry.getId()+"_ted_comments").innerHTML=templates.control.entry.tedComments(O.resultSet.result)}}catch(Q){}},function(){})
},function(K){if(I.isDestroyed()==true){return}I.element(I.entry.getId()+"_ted").innerHTML="Error:"+K})}var F=/videoId=([^&]*)&/i;function u(J){var I=this;I.entry.dailyShow=devhd.utils.RegExUtils.select(F,I.entry.getAlternateLink()).split("?");var H={subscription:I.reader.lookupSimilarSubscription(I.entry.getFeedInfo()),searchTerm:I.searchTerm,maxWidth:I.width-30,showSourceTitle:I.showSourceTitle};
I.part.innerHTML=templates.control.entry.customizable(templates.control.entry.dailyShow,I.entry,H,I.width,I.home);devhd.fn.callback(J)}var d=/video:(.*)/i;function q(J){var I=this;I.entry.collegeHumor=devhd.utils.RegExUtils.select(d,I.entry.getAlternateLink());var H={subscription:I.reader.lookupSimilarSubscription(I.entry.getFeedInfo()),searchTerm:I.searchTerm,maxWidth:I.width-30,showSourceTitle:I.showSourceTitle};
I.part.innerHTML=templates.control.entry.customizable(templates.control.entry.collegeHumor,I.entry,H,I.width,I.home);devhd.fn.callback(J)}function c(){if(this.entry.getAlternateLink()!=null){var H=this;this.home.askIncludeControl("wall",function(){H.wall=new devhd.control.WallControl();H.wall.setHome(H.home);H.wall.setPreferences(H.preferences);H.wall.setDigg(H.digg);
H.wall.setTwitter(H.twitter);H.wall.setTinyURL(H.tinyURL);H.wall.setFriendfeed(H.friendfeed);H.wall.setAnnotator(H.annotator);H.wall.setContext({entry:H.entry,entryId:H.entry.getId(),feedId:H.entry.getFeedId()});H.wall.setReadOnly(false);H.wall.setPart(H.element(H.entryId+"_wallHolder"));H.wall.display()})}if(this.preferences.get("autoTag")=="yes"){i.call(this)
}}function i(){try{var K=this.entry.listGoodTags();K=K.sort(function(S,R){return R.length-S.length});var N=[];for(var L=0;L<K.length;L++){var P=K[L].toLowerCase();var M=false;for(var J=0;J<N.length;J++){if(N[J].toLowerCase().indexOf(P)>-1){M=true;break}}if(!M){N.push(P)}}var Q=[];for(var L=0;L<N.length;L++){if(N[L].length<4){continue}var H={text:N[L],css:"microformat taggedMicroformat",title:"tag",data:{"data-mf-text":N[L],"data-mf-type":"tag"}};
Q.push(H)}var I=this.element(this.entry.getId()+"_entryContent");devhd.utils.HTMLUtils.highlightText(I,"tags",Q,1)}catch(O){}}h.processClick=function(I){var J=I.target;var H=J.getAttribute("data-mf-text");if(H!=null){this.feedly.search(H)}return false};h.processSelection=function(L){try{if(L.target.tagName.toLowerCase()=="embed"){return}if(L.target.className=="action"){return
}var H=devhd.utils.HTMLUtils.getSelection(this.home.getDocument());if(H==null||H==""){return}var K=devhd.utils.HTMLUtils.grabRangeContext(this.home.getDocument().defaultView);if(K==null){return}this.signs.hide(0);l.trace(740,"range present, will process selection");var J=this;var I={altKey:L.altKey,pageX:L.pageX,pageY:L.pageY};J.home.getDocument().defaultView.setTimeout(function(){s.call(J,I)
},5)}catch(M){$debug(devhd.utils.ExceptionUtils.formatError("process section",M))}};function s(K){if(this.home==null){return}var H=devhd.utils.HTMLUtils.getSelection(this.home.getDocument());if(H==null||H==""){return}var J=devhd.utils.HTMLUtils.grabRangeContext(this.home.getDocument().defaultView);if(J==null){return}l.trace(767,"showing selection popup ...");
this.popup.show0(templates.control.entry.toolsPopup(this.entry.getId(),H.length,this.home),{minWidth:40,deltaTop:15,deltaLeft:-19,pageX:K.pageX,pageY:K.pageY},this,true);var I=this;this.bind(this.element("tp_tweet"),"mousedown",function(){I.feedly.tweetEntry(I.entry.getId())});this.bind(this.element("tp_translate"),"mousedown",function(){I.feedly.translateSelection()
});this.bind(this.element("tp_related"),"mousedown",h.showRelatedArticles);this.bind(this.element("tp_sources"),"mousedown",h.showRelatedSources);this.bind(this.element("tp_amazon"),"mousedown",h.showAmazonProducts);this.bind(this.element("tp_google"),"mousedown",h.showGoogleResults);this.bind(this.element("tp_twitter"),"mousedown",h.showTwitterResults);
this.bind(this.element("tp_youtube"),"mousedown",h.showYouTubeResults);this.popup.armAutoHideAfterDelay(14000)}h.showRelatedArticles=function(){var H=devhd.utils.HTMLUtils.getSelection(this.home.getDocument());if(H==null||H==""){this.signs.setMessage(w(285));return}this.feedly.loadPage("search/"+H)};h.showRelatedSources=function(){var H=devhd.utils.HTMLUtils.getSelection(this.home.getDocument());
if(H==null||H==""){this.signs.setMessage(w(285));return}this.feedly.loadPage("explore/"+H)};h.showAmazonProducts=function(){var H=devhd.utils.HTMLUtils.getSelection(this.home.getDocument());if(H==null||H==""){this.signs.setMessage(w(285));return}this.home.getDocument().location.href=this.amazon.buildSearchURL(H)};h.showGoogleResults=function(){var H=devhd.utils.HTMLUtils.getSelection(this.home.getDocument());
if(H==null||H==""){this.signs.setMessage(w(285));return}this.home.getDocument().location.href="http://www.google.com/search?q="+encodeURIComponent(H)};h.showTwitterResults=function(){var H=devhd.utils.HTMLUtils.getSelection(this.home.getDocument());if(H==null||H==""){this.signs.setMessage(w(285));return}this.home.getDocument().location.href="http://search.twitter.com/search?q="+encodeURIComponent(H)
};h.showYouTubeResults=function(){var H=devhd.utils.HTMLUtils.getSelection(this.home.getDocument());if(H==null||H==""){this.signs.setMessage(w(285));return}this.home.getDocument().location.href="http://www.youtube.com/results?search_query="+encodeURIComponent(H)};h.loadEntry=function(J,H,I){if(this.entry.getId()==J){return true}else{return this.feedly.loadEntry(J,I)
}}})();