(function(){var g=devhd.pkg("control");var y=g.BaseControl.prototype;var z=g.createClass("WelcomeControl",g.BaseControl);z.setIo=function(A){this.io=A};z.setReader=function(A){this.reader=A};z.setPreferences=function(A){this.preferences=A};z.setDisco=function(A){this.disco=A};z.setFeedly=function(A){this.feedly=A};z.setRepo=function(A){this.repo=A};
z.setReco=function(A){this.reco=A};z.setProfile=function(A){this.profile=A};z.setTrends=function(A){this.trends=A};z.setSigns=function(A){this.signs=A};z.setAnalytics=function(A){this.analytics=A};z.setMode=function(A){this.mode=A};z.destroy=function(){this.subscriptions=null;this.existingGR=null;this.agents=null;this.selectedAgent=null;this.agentIndex=null;
this.io=null;this.reader=null;this.preferences=null;this.disco=null;this.feedly=null;this.repo=null;this.reco=null;this.profile=null;this.trends=null;this.signs=null;this.analytics=null;y.destroy.call(this)};z.version="1.1";function i(A){this.element("status").innerHTML=templates.control.welcome.status(A,this.home)}z.track=function(B){var A=this.home.getEnvironment()+"/"+(this.mode||"welcome")+".v9/"+B;
var C=this.getBucket(B);if(C!=null){A+="/"+C}A+="/"+this.home.getFLID();this.analytics.trackPageView(A);$debug("[welcome-process]"+A)};z.getBucket=function(A){if(A=="end"&&this.selectedAgent==null){return"empty"}if(this.selectedAgent==null){return null}if(A!="end"){return this.selectedAgent.getSymbol()}else{var B=this.reader.listSubscriptions("#all").length;
var C="M";if(B>50){C="XL"}else{if(B>20){C="L"}else{C="M"}}return this.selectedAgent.getSymbol()+"/"+C}};z.display=function(){this.subscriptions=this.reader.listSubscriptions("#all");this.initialCount=this.subscriptions.length;this.bucket=this.subscriptions.length>0?"existing":"new";this.existingGR=this.subscriptions.length>0;this.agents=this.disco.listAgents();
this.agentIndex={};for(var D=0;D<this.agents.length;D++){this.agentIndex[this.agents[D].getSymbol()]=this.agents[D]}var B=0;var A=0;var E=this;var C={};var F=0;devhd.utils.FlowUtils.parallelForEach({},E.agents,function(G,H,K,I,J){G.askPrepare(function(M){if(E.isDestroyed()==true){return}F++;E.part.innerHTML=templates.control.welcome.loading(F,E.agents.length);
for(var L in M){C[L]=M[L]}devhd.fn.callback(K)})},{onSuccess:function(){e.call(E,C)},onError:function(){E.part.innerHTML="error!"}})};function e(C){this.track("enter");var B=this.preferences.get("googType");if(B==null||B==""||B=="0"||C["goog.initial"]==0){if(C["goog.initial"]==0){B="feedly"}else{B="goog"}this.preferences.set("googType",B,null,true)}this.googType=B;
if(this.mode=="welcome"&&C["goog.initial"]!=0){this.part.innerHTML=templates.control.welcome.choices(this.mode,true);d.call(this,this.agentIndex.google,true)}else{if(this.mode=="welcome"&&C["netv.feedCount"]>30&&C["netv.feedCount"]>C["blog.feedCount"]){this.part.innerHTML=templates.control.welcome.choices(this.mode,true);d.call(this,this.agentIndex.netvibes,true)
}else{if(this.mode=="welcome"&&C["blog.feedCount"]>30&&C["blog.feedCount"]>=C["netv.feedCount"]){this.part.innerHTML=templates.control.welcome.choices(this.mode,true);d.call(this,this.agentIndex.bloglines,true)}else{this.part.innerHTML=templates.control.welcome.choices(this.mode,false,this.agents,C["goog.initial"]);for(var A=0;A<this.agents.length-1;
A++){l.call(this,this.agents[A])}}}}}function l(A){var B=this;this.bind(this.element(A.id+"_card"),"click",function(){d.call(B,A,false)})}function d(B,C){this.selectedAgent=B;if(this.selectedAgent.getSymbol()=="google"||C){p.call(this)}else{this.signs.setMessage("Initiating interaction with "+this.selectedAgent.getSymbol()+". Please wait...",0,false);
var A=this;this.selectedAgent.askCanParticipate(function(E){A.signs.hide(0);if(E==false){A.signs.setMessage("Please <a href='"+A.selectedAgent.getLoginURL()+"' target='_blank'>login</a> to "+A.selectedAgent.getTitle()+" first please")}else{var D=A.preferences.get("confirmApply");if(A.googType=="goog"&&A.selectedAgent.getSymbol()!="google"){A.element("actions").style.display="none";
A.element("warning").style.display="block";A.bind("warningYes","click",function F(){p.call(A)});A.bind("confirmationOff","click",function(){A.preferences.set("confirmApply","no",null,true);A.element("confirmationOff").style.visibility="hidden";return false})}else{p.call(A)}}})}}function a(){q.call(this)}function p(){this.track("start");try{var D=this.element("warning");
if(D!=null){D.style.display="none"}var A=this.element("actions");if(A!=null){A.style.display="none"}var C=this.element("formErrorMsg");if(C!=null){C.style.display="none"}i.call(this,"Processing...");m.call(this,0)}catch(B){$debug("[welcomeArea][apply] "+devhd.utils.ExceptionUtils.formatError("do apply",B))}}function q(){this.element("actions").style.display="none";
i.call(this,"Skiping personalization step...");m.call(this,3)}function j(){this.track("start/empty");i.call(this,"Finalizing...");this.emptyMode=true;m.call(this,7)}var u=0;function m(A){u=A-1;c.call(this)}function c(){u++;switch(u){case 0:i.call(this,"Backing up your OPML file");k.call(this);return;case 1:i.call(this,"Discovering feeds. Could take a minute or two");
r.call(this);return;case 2:i.call(this,"Adding subscriptions");s.call(this);return;case 3:i.call(this,"Updating favorites");f.call(this);return;case 4:i.call(this,"Preparing Magazine");x.call(this);return;default:v.call(this)}}function k(){var A=this;this.io.get("http://www.google.com/reader/subscriptions/export",function(C){try{var B=Components.classes["@mozilla.org/file/directory_service;1"].getService(Components.interfaces.nsIProperties).get("ProfD",Components.interfaces.nsIFile);
B.append("feedly.backup-"+new Date().getTime()+".opml");if(B.exists()==false){var D=Components.classes["@mozilla.org/network/file-output-stream;1"].createInstance(Components.interfaces.nsIFileOutputStream);D.init(B,2|8|32,438,0);D.write(C,C.length);D.close();$debug("[welcomeArea][opmlBackup]saved as "+B.path)}}catch(E){}c.call(A)},function(B,C){$debug("[welcomeArea][opmlBackup] failed because: "+B+" -- "+C);
c.call(A)})}function r(){var B=0;var A=0;var C=this;this.selectedAgent.askSuggestFeeds(function(D){B=D},function(D){A++;i.call(C,templates.control.welcome.discovering(D,A,B,C.home))},function(D){i.call(C,"Discovered "+D.length+" subscriptions.");C.seeds=[];try{var J={},E={};var I="user/"+C.reader.getUserId()+"/state/com.google/broadcast";for(var F=0;
F<D.length;F++){var H=D[F];if(C.reader.lookupSimilarSubscription(D[F])!=null){continue}if(H.id==I){continue}if(H.id!=null){if(J[H.id]==true){continue}else{J[H.id]=true}}if(H.website!=null){if(E[H.website]==true){continue}else{E[H.website]=true}}C.seeds.push(H)}}catch(G){}c.call(C)})}function s(){i.call(this,"Updating subscription list");b.call(this,this.seeds,0)
}function b(A,E){if(A==null||A.length==null||E>=A.length){c.call(this);return}var B=A[E];i.call(this,"Adding building block ("+E+" of "+A.length+"):"+B.title);var D=this.preferences.has("entryOverviewSize","subscription/"+B.id);if(D==false&&B.view!=null){this.reader.setFeedPreference(B.id,"entryOverviewSize",B.view)}var C=this;this.reader.askAddSubscription(B.id,B.title,B.categories,{favorite:B.favorite,seeded:true},function(){if(B.view!=null){C.reader.setFeedPreference(B.id,"entryOverviewSize",B.view)
}b.call(C,A,E+1)},true)}var t=[];function f(){var A=this.reader.listSubscriptions("#all",null,false,true);if(A.length>0){i.call(this,"Determining favorite subscriptions");c.call(this);return}else{t=[];o.call(this)}}var h=200;var w=200;function o(){i.call(this,"Determining favorite subscriptions (part I)");var A=this;this.reader.askEntries(this.reader.formatTerm("broadcast"),{},h,function(B){t=B;
n.call(A)},function(C,B){c.call(A)},true)}function n(){i.call(this,"Determining favorite subscriptions (part II)");var A=this;this.reader.askEntries(this.reader.formatTerm("broadcast"),{},w,function(C){try{t=devhd.utils.EntryIdListUtils.merge(t,C);var B=A.trends.computeTopXFeeds(t);var D=Math.max(5,Math.floor(A.reader.listSubscriptions("#all").length*0.2));
var F=0;for(var E=0;E<B.length&&F<D;E++){if(B[E].unreadCount>150){continue}var G=A.reader.lookupSubscription(B[E].id);if(G==null){continue}A.reader.markSubscriptionAsFavorite(B[E].id);F++}$debug("[welcome] marking "+F+" subscriptions as favorites.")}catch(H){}c.call(A)},function(C,B){c.call(A)})}function x(){this.reader.reset();this.reco.reset();c.call(this)
}function v(){if(this.mode=="add"){this.part.innerHTML=templates.control.welcome.done(this.mode,this.googType,this.emptyMode,this.home);this.feedly.updateTabs()}else{this.track("end");this.preferences.set("welcomed",this.version,null,true);this.part.innerHTML=templates.control.welcome.done(this.mode,this.googType,this.emptyMode,this.home);this.feedly.updateTabs()
}if(this.reader.listSubscriptions("#all").length>3){var B=this.googType=="goog"?"my":"cover";var A=this.reader.listRankedCategories({excludeEmpty:true});if(A.length==1){B="category/"+A[0].label}this.feedly.loadPage(B,{forceRecreate:true})}this.reader.syncSubscriptions(function(){},true)}})();