/*
 Copyright 2009 Google Inc.  All Rights Reserved.
 Your use of this software is subject to the Terms of Service located
 at https://chrome.google.com/extensions/intl/en/gallery_tos.html.
*/
var e=true,g=null,h=window,i=Object,k=chrome,l=Array;function m(a,b){return a.next=b}function n(a,b){return a.prev=b}var o="push",p="tabs",r="i18n",s="replace",t="extension",u="getMessage",w="pageAction",x="length",y="prototype",z="next",B="localStorage",C="hasOwnProperty",D="call",E="prev",F="href",G="apply",H;var I=this,J=function(a,b){var c=b||I;if(arguments[x]>2){var d=l[y].slice[D](arguments,2);return function(){var f=l[y].slice[D](arguments);l[y].unshift[G](f,d);return a[G](c,f)}}else return function(){return a[G](c,arguments)}};Function[y].bind=function(a){if(arguments[x]>1){var b=l[y].slice[D](arguments,1);b.unshift(this,a);return J[G](g,b)}else return J(this,a)};var aa=/&/g,ba=/</g,ca=/>/g,da=/\"/g;function K(a){if(!a)return"";return a[s](aa,"&amp;")[s](ba,"&lt;")[s](ca,"&gt;")[s](da,"&quot;")}String.fromCharCode(160);function ea(a){var b=l[y].splice[D](arguments,1,arguments[x]);return Function[y].bind[G](a,b)};function L(a,b,c){if(!(h[B].enableGen204Logging!="true"||a==g||b==g)){a=["atyp=i","ei="+a.ei,"ved="+a.ved,"oi=findy","ct="+b];c=c||{};c.seq=(new Date).getTime();b=[];for(var d in c)b[o](d+":"+encodeURIComponent(c[d]));d="http://www.google.com/gen_204?"+a.join("&")+"&cad="+b.join(";");try{var f=new XMLHttpRequest;f.open("GET",d,e);f.send()}catch(j){}}};var M="StopIteration"in I?I.StopIteration:Error("StopIteration"),N=function(){};m(N[y],function(){throw M;});N[y].__iterator__=function(){return this};var O=function(a){this.map_={};this.keys_=[];var b=arguments[x];if(b>1){if(b%2)throw Error("Uneven number of arguments");for(var c=0;c<b;c+=2)this.set(arguments[c],arguments[c+1])}else if(a){var d;if(a instanceof O){d=a.getKeys();c=a.getValues()}else{b=[];var f=0;for(d in a)b[f++]=d;d=b;b=[];f=0;for(c in a)b[f++]=a[c];c=b}for(b=0;b<d[x];b++)this.set(d[b],c[b])}};H=O[y];H.count_=0;H.version_=0;H.getCount=function(){return this.count_};
H.getValues=function(){P(this);for(var a=[],b=0;b<this.keys_[x];b++)a[o](this.map_[this.keys_[b]]);return a};H.getKeys=function(){P(this);return this.keys_.concat()};H.remove=function(a){if(i[y][C][D](this.map_,a)){delete this.map_[a];this.count_--;this.version_++;this.keys_[x]>2*this.count_&&P(this);return e}return false};
var P=function(a){if(a.count_!=a.keys_[x]){for(var b=0,c=0;b<a.keys_[x];){var d=a.keys_[b];if(i[y][C][D](a.map_,d))a.keys_[c++]=d;b++}a.keys_.length=c}if(a.count_!=a.keys_[x]){var f={};for(c=b=0;b<a.keys_[x];){d=a.keys_[b];if(!i[y][C][D](f,d)){a.keys_[c++]=d;f[d]=1}b++}a.keys_.length=c}};O[y].get=function(a,b){if(i[y][C][D](this.map_,a))return this.map_[a];return b};O[y].set=function(a,b){if(!i[y][C][D](this.map_,a)){this.count_++;this.keys_[o](a);this.version_++}this.map_[a]=b};
O[y].__iterator__=function(a){P(this);var b=0,c=this.keys_,d=this.map_,f=this.version_,j=this,q=new N;m(q,function(){for(;;){if(f!=j.version_)throw Error("The map has changed since the iterator was created");if(b>=c[x])throw M;var v=c[b++];return a?v:d[v]}});return q};var R=function(a,b){this.maxCount_=a||g;this.cache_=!!b;this.map_=new O;this.head_=new Q("",undefined);m(this.head_,n(this.head_,this.head_))},T=function(a,b){var c=a.map_.get(b);if(c)if(a.cache_){c.remove();S(a,c)}return c};H=R[y];H.get=function(a,b){var c=T(this,a);return c?c.value:b};H.set=function(a,b){var c=T(this,a);if(c)c.value=b;else{c=new Q(a,b);this.map_.set(a,c);S(this,c)}};H.remove=function(a){if(a=this.map_.get(a)){this.removeNode(a);return e}return false};
H.removeNode=function(a){a.remove();this.map_.remove(a.key)};H.getCount=function(){return this.map_.getCount()};H.getKeys=function(){return this.map(function(a,b){return b})};H.getValues=function(){return this.map(function(a){return a})};H.map=function(a,b){for(var c=[],d=this.head_[z];d!=this.head_;d=d[z])c[o](a[D](b,d.value,d.key,this));return c};
var S=function(a,b){if(a.cache_){m(b,a.head_[z]);n(b,a.head_);m(a.head_,b);n(b[z],b)}else{n(b,a.head_[E]);m(b,a.head_);n(a.head_,b);m(b[E],b)}if(a.maxCount_!=g)for(var c=a.maxCount_,d=a.map_.getCount();d>c;d--)a.removeNode(a.cache_?a.head_[E]:a.head_[z])},Q=function(a,b){this.key=a;this.value=b};Q[y].remove=function(){m(this[E],this[z]);n(this[z],this[E]);delete this[E];delete this[z]};var U=function(a,b,c){a=a.map_.get(b);if(!a||c==g)return g;if(c=="")return a[a[x]-1];for(b=0;b<a[x];b++){var d=a[b];if(d.query==c||d.ei==c)return d}return g};var fa=/https?:\/\/(?:.+\.)?google\.[a-z]{2,3}(?:\.[a-z]{2})?(?:\:[0-9]+)?\/search.*[?|&]q=([^&]+)/;k[t].getVersion=function(){if(!k[t].version_){var a=new XMLHttpRequest;a.open("GET",k[t].getURL("manifest.json"),false);a.onreadystatechange=function(){if(this.readyState==4){var b=JSON.parse(this.responseText);k[t].version_=b.version}};a.send()}return k[t].version_};var V=function(){this.lastInterval_=g};V[y].setImage_=function(a){k[w].setIcon({tabId:a,path:"images/page-action-animated_"+this.step_+".png"});this.step_=(this.step_+1)%8};V[y].stop=function(){this.lastInterval_&&h.clearInterval(this.lastInterval_)};var W={"search-results":ga,"landing-page":ha,"found-tidbits":ia,"log-event":ja,"minimized-state":ka,"open-link":la,"get-more-tidbits":ma},X=new function(){this.map_=new R(100,e)},Y=new V;function na(a){a.onMessage.addListener(function(b){W[a.name]&&W[a.name](a,b)})}
function ga(a,b){for(var c=X,d=b.results,f=0;f<d[x];f++){var j=d[f];if(j[F])a:{var q=c.map_.get(j[F]);if(q){for(var v=0;v<q[x];v++){var A=q[v];if(A.query==j.query||A.ei==j.ei){A.ei=j.ei;A.tidbits=j.tidbits;A.htmlTidbits=j.htmlTidbits;q.splice(v,1);q[o](A);break a}}q[o](j)}else c.map_.set(j[F],[j])}}}
function ha(a,b){var c=a.sender.tab.id,d=U(X,b[F],b.subkey);if(d&&d.tidbits[x]>0&&(d.hasEbmTidbits||0)){d.debug=d.debug||{};d.debug.version=k[t].getVersion();d.hasEbmTidbits&&Z(c,{title:"running",active:e});k[p].executeScript(c,{code:"window.qs_result = "+JSON.stringify(d)},function(){oa(c,"in-document_content_script.js",function(){d.seen=e})})}else{var f;if(d)f=k[r][u]("qs_info_non_annotated_result",K(d.query));else if(fa.test(b[F])&&/[?&](esrch=FT|qscrl=)/.test(b[F]))f=k[r][u]("qs_info_on_search");
if(f){Z(c,{active:false});pa(c,f)}}}function ia(a,b){var c=a.sender.tab.id;if(b.foundTidbits){Z(c,{active:b.result.hasEbmTidbits});L(b.result,"found-tidbits",b.logParams)}else{Z(c,{active:false});pa(c,k[r][u]("qs_info_no_tidbits_found",K(b.result.query)));L(b.result,"no-tidbits-found")}}function ja(a,b){var c=b.params||{};c.ver=k[t].getVersion();L(b.result,b.action,c)}function ka(a,b){if(b.result)U(X,b.result[F],b.result.query).minimized=b.minimized}function la(a,b){qa(b.url)}
function qa(a){k[p].getAllInWindow(g,function(b){for(var c=0;c<b[x];c++)if(b[c].url==a){k[p].update(b[c].id,{selected:e});return}k[p].create({url:a,selected:e})})}function ma(a,b){try{var c=new XMLHttpRequest;c.open("GET",b.url,e);c.onreadystatechange=function(){this.readyState==4&&a.postMessage({content:this.responseText})};c.send()}catch(d){a.postMessage({content:""})}}
function ra(a){var b=k[t].getURL("about.html");(a.url.indexOf("chrome")==0||a.url.indexOf("chrome.google.com/extensions")!=-1)&&a.url!=b?qa(b):k[p].sendRequest(a.id,{toggle:e})}
function Z(a,b){if(b.title=="running"){var c=Y;c.stop();c.step_=1;c.lastInterval_=h.setInterval(ea(c.setImage_,c,a),300)}else{Y.stop();k[w].setIcon({tabId:a,path:"images/page-action-"+((b.active?"active":"inactive")+".png")})}c=k[r][u]("qs_page_action_"+(b.title||(b.active?"active":"inactive")));k[w].setTitle({tabId:a,title:c});k[w].show(a)}
function oa(a,b,c){var d=k[r][u]("direction");k[p].executeScript(a,{file:"jquery_do_not_compile.js"},function(){var f="in-document_"+d+"_css.css";k[p].insertCSS(a,{file:f},function(){f=""+b;k[p].executeScript(a,{file:f},function(){c()})})})}function pa(a,b){oa(a,"in-document-message_content_script.js",function(){k[p].sendRequest(a,{text:b})})}function sa(){if(h[B]&&!h[B].welcome){h[B].enableGen204Logging="false";k[p].getSelected(g,function(a){k[p].update(a.id,{url:k[t].getURL("about.html")})})}}
function ta(){if(h[B]&&!h[B].welcome)h[B].welcome="true"}function _QS_initBackgroundPage(){k[t].onConnect.addListener(na);k[w].onClicked.addListener(ra);sa();h.setInterval(ta,6E5)};
