var KEY_UP=38;var KEY_DOWN=40;var KEY_ENTER=13;var ELEMENT_NODE=1;var KEY_ESCAPE=27;var KEY_F4=115;function openCombo(E,D,C){var F=document.getElementById(D);if(F.disabled){return}if(gComboEx==null){gComboEx=document.getElementById(C)}var B=gComboEx;var A=B.style.display=="block";if(!A){showCombo(F,B);
gItemNum=-1}else{setStyle(B,"display","none","");gItemNum=-1}gFocusItem=F;setTimeout("doFocus();",0)}function showCombo(G,A){var F=0,E=0;var C=G;do{F+=C.offsetTop;E+=C.offsetLeft;C=C.offsetParent}while(C);var B=(F+G.offsetHeight)+"px";var D=E+"px";setStyle(A,"top",B,"");setStyle(A,"left",D,"");setStyle(A,"display","block","");
return}var gItemNum=0;var gComboEx=null;function focusCombo(A,H,B){var I=A.keyCode;var J=true;if(gComboEx==null){gComboEx=document.getElementById(B)}var E=gComboEx;if(I==KEY_DOWN||I==KEY_F4){J=false;var C=E.getAttribute("style.display")=="block";if(!C){showCombo(H,E)}var G=E.childNodes;var D=G.length;
var F=0;while(G[F]!=null&&F<D){if(G[F].nodeType==ELEMENT_NODE&&G[F].className=="item"){gFocusItem=G[F];break}F++}gItemNum=0;setTimeout("doFocus();",0);J=false}else{if(I==KEY_ENTER){}else{if(I==KEY_ESCAPE){if(H.value!=null&&H.value.length>0){J=true}else{J=false;setStyle(gComboEx,"display","none","");gItemNum=-1
}}}}return J}function focusItem(B,D,J){var H=J.value;var A=null;var C=getItems(D);var E=C.length;var K=false;for(var I=0;I<E;I++){if(C[I].hasChildNodes()&&C[I].firstChild.nodeValue==H){K=true;A=C[I];gItemNum=I;break}}if(!K){A=addItem(D,H,C.length);gItemNum=C.length}if(A!=null){gFocusItem=A;if(gComboEx.getAttribute("style.display")!="block"){var G=(J.offsetTop+J.offsetHeight)+"px";
var F=J.offsetLeft+"px";setStyle(D,"top",G,"");setStyle(D,"left",F,"")}else{setStyle(D,"display","none","")}setStyle(D,"display","block","");setTimeout("doFocus();",0)}}function addItem(E,D,B){var A=document.createElement("div");var C=document.createTextNode(D);A.appendChild(C);A.setAttribute("tabindex","-1");
A.setAttribute("class","item");A.setAttribute("onclick","gItemNum="+B+";");A.setAttribute("onmouseover","gFocusItem = this; doFocus();");A.setAttribute("role","listitem");A.style.overflow="hidden";E.appendChild(A);return A}function doComboNav(B,D,J){var K=B.keyCode;var L=true;if(gComboEx==null){gComboEx=D
}if(K==KEY_UP||K==KEY_DOWN){L=false;var H=0;var C=getItems(gComboEx);var E=C.length;if(K==KEY_UP){H=gItemNum-1}else{H=(gItemNum+1);if(H==E){H=-1}}gItemNum=H;if(gItemNum==-1){gFocusItem=document.getElementById(J)}else{gFocusItem=C[H]}setTimeout("doFocus();",0)}else{if(K==KEY_ENTER||(!B.keyCode&&B.button>=0)){var C=getItems(gComboEx);
var A=C[gItemNum];if(A!=null&&A.getAttribute("aria-disabled")!="true"){var F=A.firstChild;var G=F.nodeValue;var I=document.getElementById(J);I.value=G;if(I.onchange){I.onchange()}setStyle(gComboEx,"display","none","");gItemNum=0;gFocusItem=I;setTimeout("doFocus();",0)}}else{if(K==KEY_ESCAPE){L=false;
setStyle(D,"display","none","");gItemNum=0;gFocusItem=document.getElementById(J);setTimeout("doFocus();",0)}}}return L}function getItems(E){var C=new Array();var C=new Array();var B=E.childNodes;var A=B.length;for(var D=0;D<A;D++){if(B[D].nodeType==ELEMENT_NODE&&(B[D].getAttribute("class")=="item"||B[D].getAttribute("class")=="item focus")){C[C.length]=B[D]
}}return C}function setStyle(C,F,B,E){var A=false;try{if(C.style&&C.style.setProperty){C.style.setProperty(F,B,E);A=true}}catch(D){alert("exception caught setting style: "+D.message)}if(!A){try{C.style[F]=B;A=true}catch(G){alert("exception caught setting direct style: "+G.message)}}return A}gFocusItem=null;
gLastFocusItem=null;function doFocus(){if(gFocusItem!=null){gFocusItem.focus();if(gLastFocusItem&&gLastFocusItem.className=="item focus"){gLastFocusItem.className="item"}if(gFocusItem&&gFocusItem.className=="item"){gFocusItem.className="item focus"}gLastFocusItem=gFocusItem;gFocusItem=null}}function create_combo(D,J){var F=document.getElementById(D);
var E=D+"_combo";F.setAttribute("onkeydown","return focusCombo(event, this, '"+E+"');");F.setAttribute("role","textfield");F.setAttribute("aria-haspopup","true");F.setAttribute("autocomplete","off");F.style.marginRight="0px";var A=F.style.width.replace(/px/,"");if(A==""){try{var C=F.ownerDocument.defaultView.getComputedStyle(F,"");
A=C.width.replace(/px/,"")}catch(I){}}var B=document.createElement("div");B.setAttribute("role","list");B.setAttribute("style","display: none;");B.setAttribute("id",E);B.setAttribute("class","dropStyle");B.setAttribute("onkeydown","return doComboNav(event, this, '"+D+"');");B.setAttribute("onclick","doComboNav(event, this, '"+D+"');");
B.style.width=(parseInt(A)+4)+"px";B.style.paddingLeft="6px";B.style.paddingRight="6px";if(F.nextSibling){F.parentNode.insertBefore(B,F.nextSibling)}else{F.parentNode.appendChild(B)}window.addEventListener("click",function(){close_combo(D)},false);for(var G=0;G<J.length;G++){addItem(B,J[G],G)}var H=document.createElement("img");
H.setAttribute("onclick","openCombo(event, '"+D+"', '"+E+"'); event.cancelBubble = true;");H.setAttribute("src","dropdown.png");H.setAttribute("valign","middle");F.parentNode.insertBefore(H,B)}function delete_combo_item(G,D){var F=G+"_combo";var E=document.getElementById(F);if(E){var A=getItems(E);for(var C=0;
C<A.length;C++){if(A[C].innerHTML==D){A.splice(C,1);while(E.hasChildNodes()){E.removeChild(E.firstChild)}for(var B=0;B<A.length;B++){addItem(E,A[B].innerHTML,B)}break}}}}function close_combo(D){var C=D+"_combo";var B=document.getElementById(C);if(B){var A=B.style.display=="block";if(A){setStyle(B,"display","none","");
gItemNum=-1}}}function repopulate_combo(E,A){var D=E+"_combo";var C=document.getElementById(D);if(C){while(C.hasChildNodes()){C.removeChild(C.firstChild)}for(var B=0;B<A.length;B++){addItem(C,A[B],B)}}};
