function hasNeverAutologin(B,A){var E=lpcanonizeUrl(B);if(g_neverurls.onlyautologins&&g_neverurls.onlyautologins.length>0){var F=false;for(var D=0;g_neverurls.onlyautologins&&D<g_neverurls.onlyautologins.length;D++){var C=g_neverurls.onlyautologins[D];if(C==A||C==E){F=true;break}}if(!F){return true}}for(var D=0;
g_neverurls.neverautologins&&D<g_neverurls.neverautologins.length;D++){var C=g_neverurls.neverautologins[D];if(C==A||C==E){return true}}return false}function hasNeverGenerate(B,A){var E=lpcanonizeUrl(B);if(g_neverurls.onlygenerates&&g_neverurls.onlygenerates.length>0){var F=false;for(var D=0;g_neverurls.onlygenerates&&D<g_neverurls.onlygenerates.length;
D++){var C=g_neverurls.onlygenerates[D];if(C==A||C==E){F=true;break}}if(!F){return true}}for(var D=0;g_neverurls.nevergenerates&&D<g_neverurls.nevergenerates.length;D++){var C=g_neverurls.nevergenerates[D];if(C==A||C==E){return true}}return false}function hasNeverFormFill(B,A){var E=lpcanonizeUrl(B);
if(g_neverurls.onlyformfills&&g_neverurls.onlyformfills.length>0){var F=false;for(var D=0;g_neverurls.onlyformfills&&D<g_neverurls.onlyformfills.length;D++){var C=g_neverurls.onlyformfills[D];if(C==A||C==E){F=true;break}}if(!F){return true}}for(var D=0;g_neverurls.neverformfills&&D<g_neverurls.neverformfills.length;
D++){var C=g_neverurls.neverformfills[D];if(C==A||C==E){return true}}return false}function handleFill(A,H){var E=false;if(!lploggedin||grid_getdata("active")!=null){return}if(H.cmd=="autofillaid"||H.cmd=="autologinaid"){var C=H.aid;if(typeof(g_sites[C])!="undefined"){var I=H.cmd=="autologinaid";fill(A,g_sites[C],null,I,!I,"all",true,false,true)
}return}if(typeof(H)=="undefined"||!H||typeof(H.url)=="undefined"){return}var B=H.url;console.log("request to fill "+B);if(lp_url_is_lastpass(B)){return}if(typeof(g_launches[A])!="undefined"){var C=g_launches[A];if(check_ident_aid(C)){g_launches[A]=null;if(typeof(g_sites[C])!="undefined"){fill(A,g_sites[C],null,true,false,H.docnum,false,true)
}}}var D=lp_gettld_url(B);var J=getsites(D);J=reorderOnURL(J,B,true);if(hasNeverAutologin(B,D)){J=new Array()}var M=(H.force==0&&H.topurl!=B?lp_gettld_url(H.topurl):"");if(M!=""&&hasNeverAutologin(H.topurl,M)){J=new Array()}for(var G in J){var L=false;var C=J[G]["aid"];if(!check_ident_aid(C)){continue
}if(typeof(g_sites[C])=="undefined"){continue}var K=g_sites[C];if(K.never_autofill){L=true}if(K.pwprotect||g_prompts.login_site_prompt){L=true}if(K.genpw){continue}if(K.fields.length==0&&K.username==""){continue}if(K.url.indexOf("https://")==0&&B.indexOf("https://")!=0){L=true}if(lpGetPref("automaticallyFill",1)==0){L=true
}if(!L){var F=!K.save_all;if(F){g_fillfieldsmatches[B]=J}fill(A,K,H.docid,null,F,H.docnum,null,true)}if(lpGetPref("showFillNotificationBar",1)!=0){sendCS(A,{cmd:"showfillnotification",text:gs("LastPass has filled your login information into the form on this page."),sites:cache_usernames(J),docnum:H.docnum});
E=true}break}if(!E){checkgenpwfillforms(A,B)}}function checkgenpwfillforms(A,G){var F=lp_gettld_url(G);var E=lpGetPref("showGenerateNotifications",1)!=1||hasNeverGenerate(G,F);var D=lpGetPref("showFormFillNotifications",1)!=1||hasNeverFormFill(G,F);var B=new Array();if(!D){for(var C=0;C<g_formfills.length;
C++){if(check_ident_ffid(g_formfills[C].ffid)){B[B.length]=g_formfills[C]}}if(B.length==0){D=true}}if(!E||!D){sendCS(A,{cmd:"checkgenpwfillforms",nevergenerate:E,neverformfill:D,sites:cache_usernames(reorderOnURL(getsites(F),G,true,true)),formfills:B})}}function cache_usernames(A){for(var B in A){A[B]["useusername"]=getusernamefromacct(A[B])
}return A}function hasNeverSave(B,A){var E=lpcanonizeUrl(B);console.log("num: "+g_neverurls.onlyaccounts.length);if(g_neverurls.onlyaccounts&&g_neverurls.onlyaccounts.length>0){var F=false;for(var D=0;g_neverurls.onlyaccounts&&D<g_neverurls.onlyaccounts.length;D++){var C=g_neverurls.onlyaccounts[D];if(C==A||C==E){F=true;
break}}if(!F){return true}}console.log("num: "+g_neverurls.neveraccounts.length);for(var D=0;g_neverurls.neveraccounts&&D<g_neverurls.neveraccounts.length;D++){var C=g_neverurls.neveraccounts[D];if(C==A||C==E){return true}}return false}function handleNever(A,E){if(E.cmd=="neverautofill"){var D=E.aid;
if(typeof(g_sites[D])=="undefined"){return}g_sites[D]["never_autofill"]=true;g_sites[D]["autologin"]=false;var C="aid="+en(D);lpMakeRequest(base_url+"set_never_autofill.php",C,null,null)}else{if(E.cmd=="neverdomain"||E.cmd=="neverpage"){var B=E.cmd=="neverdomain"?lp_gettld_url(E.url):lpcanonizeUrl(E.url);
var C="url="+en(AES.bin2hex(B));if(typeof(E.fromsave)!="undefined"){g_neverurls.neveraccounts.push(B)}else{if(typeof(E.fromgenerate)!="undefined"){C+="&type=1";g_neverurls.nevergenerates.push(B)}else{if(typeof(E.fromformfill)!="undefined"){C+="&type=2";g_neverurls.neverformfills.push(B)}else{C+="&type=3";
g_neverurls.neverautologins.push(B)}}}lpMakeRequest(base_url+"add_never.php",C,null,null)}}g_local_accts_version++;rewritelocalfile()}function handleSave(Q,S){if(!lploggedin){return}var C=S.formdata.split("\n");var R=false,H=false;var M="",D="";var A=new Array();for(var O=0;O<C.length;O++){var K=C[O];
var L=K.split("\t");if(L.length!=4){continue}var T=decodeURIComponent(L[2]);var E=L[3];if(!R&&E=="text"&&T.length){M=T;R=true}if(E=="password"){A[A.length]=T;if(!H&&T.length){D=T;H=true}}}if(H){S.username=M;S.password=D;if(!R&&A.length>1){S.username=A[0];S.password=A[1]}var P=lp_gettld_url(S.url);S.tld=P;
var N=false;var I="";if(A[A.length-1]==A[A.length-2]&&A[A.length-1]!=""){N=true;I=A[A.length-1]}else{if(A[0]==A[1]&&A[0]!=""){N=true;I=A[0]}}if(N&&array_length(getsites(P,true))>0){g_notification_type="change";S.newpw=I;g_notification_data=S;sendTS({cmd:"notification",type:"change"});if(lpGetPref("showChangeNotificationBar",1)!=0){var B=getsites(P,true);
var F;S.sitecount=array_length(B);if(array_length(B)==1){for(var O in B){S.singleaid=O;F=gs("LastPass detected a password change for user:")+" "+getusernamefromacct(g_sites[O]);break}}else{F=gs("LastPass detected a password change for domain:")+" "+P}sendCS(Q,{cmd:"showchangenotification",text:F,notificationdata:S});
g_persistent_notifications[Q]={cmd:"showchangenotification",text:F,notificationdata:S}}}else{if(hasNeverSave(S.url,P)){return}var B=typeof(g_tlds[P])!="undefined"?g_tlds[P]:new Array();for(var G in B){if(!check_ident_aid(G)){continue}if(typeof(g_sites[G])=="undefined"){continue}var J=g_sites[G];if(((!R||M==lpmdec(J.username,true))&&(D==lpmdec(J.password,true)))||(J.save_all&&isMatch(J,R,M,D))){return
}}g_notification_type="save";g_notification_data=S;if(lpGetPref("showSaveSiteNotifications",1)!=0){sendTS({cmd:"notification",type:"save"})}if(lpGetPref("showSaveNotificationBar",1)!=0){if(lpCheckAddSite(S.username,S.password,P)){sendCS(Q,{cmd:"showaddnotification",text:gs("Should LastPass remember this password?"),notificationdata:S});
g_persistent_notifications[Q]={cmd:"showaddnotification",text:gs("Should LastPass remember this password?."),notificationdata:S}}}}}}function lpCheckAddSite(H,C,B){var G=lpenc(C);var A=lp_get_gmt_timestamp();var E=new Array();for(var D in g_rejectedaddsites){var F=g_rejectedaddsites[D];if(A>(F.rejectedTime+60*10)){E[E.length]=D
}}for(var D=E.length-1;D>=0;D--){g_rejectedaddsites.splice(E[D],1)}for(var D in g_rejectedaddsites){var F=g_rejectedaddsites[D];if(F.username==H&&F.encryptedPassword==G&&compare_tlds(F.tld,B)){return false}}return true}function handleUpdateFields(A,C){try{var B=C.aid;var G=g_sites[B];var E=new Array();
var I=updateAndEncryptData(C.formdata,E);update_username_from_fields_if(G,E);for(var D=G.fields.length-1;D>=0;D--){if(!G.fields[D].otherfield&&G.fields[D].otherlogin!="1"){G.fields.splice(D,1)}}for(var D=0;D<E.length;D++){G.fields[G.fields.length]=E[D]}g_local_accts_version++;rewritelocalfile();var H="data="+en(bin2hex(I))+"&ref="+en(bin2hex(C.url))+"&updatefields=1&aid="+en(B);
updateFieldsFromSubmit(H,G)}catch(F){alert(F.message)}}function update_username_from_fields_if(B,A){var E=0,C="";for(var D=0;D<A.length;D++){if(A[D].type=="text"){C=A[D].value;if(++E>=2){break}}}if(E==1&&C!=""){var F=0;for(var D=0;D<B.fields.length;D++){if(!B.fields[D].otherfield&&B.fields[D].type=="text"){F++;
break}}if(F==0){B.username=C;B.unencryptedUsername=lpdec(btoa(B.username))}}}function updateAndEncryptData(L,F){var H="";var O=typeof(L)!="undefined"?L.split("\n"):new Array();for(var D=0;D<O.length;D++){var P=O[D];var E=P.split("\t");if(E.length!=4){continue}var G="0";var A=decodeURIComponent(E[1]);
var C=decodeURIComponent(E[2]);var I=E[3];var N=false;var B=C;var M=false;if(I=="text"||I=="password"||I=="hidden"||I=="textarea"){var K=lpenc(C);H+=G+"\t"+en(A)+"\t"+en(K)+"\t"+en(I)+"\n";if(I!="hidden"){N=true;B=atob(K)}}else{if(I=="action"){H+=G+"\taction\t"+en(lpcanonizeUrl(C))+"\taction\n"}else{if(I=="method"){H+=G+"\tmethod\t"+en(C)+"\tmethod\n"
}else{H+=G+"\t"+en(A)+"\t"+en(C)+"\t"+en(I)+"\n";if(I=="radio"||I=="checkbox"){M=C.substring(C.length-2)=="-1";if(I!="radio"||M){N=true;B=C.substring(0,C.length-2)}}else{if(I=="select-one"){N=true}}}}}if(N){var J=new Array();J.otherfield=false;J.name=A;J.type=I;J.value=B;J.checked=M;J.formname="";J.urid="0";
J.otherlogin="0";J.url="";F[F.length]=J}}return H}function handleSaveAll(A,B){B.save_all=1;g_site_data=B;chrome.tabs.create({url:getchromeurl("site.html")})}function isMatch(H,G,F,B){var E=G?false:true;var A=false;for(var C=0;C<H.fields.length;C++){if(H.fields[C]["type"]!="text"&&H.fields[C]["type"]!="password"){continue
}var D=lpmdec(H.fields[C]["value"],true);if(H.fields[C]["type"]=="text"&&F==D){E=true}if(H.fields[C]["type"]=="password"&&B==D){A=true}}if(E&&A){return true}return false}function fill(R,I,M,K,H,Q,C,L,G){if(!G){G=false}if(!L&&(I.pwprotect||g_prompts.login_site_prompt)){console.log("FILL : Showing Security Prompt");
security_prompt(function(){fill(R,I,M,K,H,Q,C,true,G)});return}var N=I.fields;var S=N.length;H=H==1?1:0;C=C?1:0;var F=I.sharedfromaid!=null&&I.sharedfromaid!=""&&I.sharedfromaid!="0"&&I.sharedfromaid!="null"?1:0;if(S!=0){for(var P=0;P<N.length;P++){if(H&&N[P]["type"]!="password"){continue}var A=N[P];
var U=A.value;var E=A.type;if(E=="text"||E=="password"||E=="textarea"){U=lpmdec(U,true)}if(U==""){continue}var T={cmd:"fillfield",manualfill:G,name:A.name,value:U,formname:A.formname,type:E,docid:M,aid:I.aid,checked:A.checked,doconfirm:H||(I.save_all&&E=="password")?1:0,tabid:R,allowforce:C,custom_js:I.custom_js,sharedsite:F};
if(I.custom_js!=""){T.username=I.unencryptedUsername;T.password=lpmdec(I.password,true);T.onlyfill=K?1:0}sendCS(R,T,Q)}}else{if(C){console.log("no fields. finding best match "+lpmdec(I.username,true)+" and <hidden>");sendCS(R,{cmd:"fillbest",username:lpmdec(I.username,true),password:lpmdec(I.password,true),docid:M,aid:I.aid,custom_js:I.custom_js,updatefields:1,sharedsite:F},Q)
}}if(H){return}if(K){var J=typeof(I.submit_id)!="undefined"?I.submit_id:"";sendCS(R,{cmd:"submit",docid:M,submit_id:J},Q)}else{if(I.autologin){var B=(new Date()).getTime();var D=parseInt(lpGetPref("autoautoVal",25));if(isNaN(D)||D==""||D<=0){D=25}var O=(B-(D*1000));if(typeof(I.last_auto_login)=="undefined"||isNaN(I.last_auto_login)||I.last_auto_login<O){console.log("Launching autologin");
I.last_auto_login=B;var J=typeof(I.submit_id)!="undefined"?I.submit_id:"";sendCS(R,{cmd:"submit",docid:M,submit_id:J},Q)}}}if(g_loglogins||LPISLOC){if(typeof(g_loggedLogins[I.aid])=="undefined"){g_loggedLogins[I.aid]="1";loglogin(I.aid)}}}function fillfieldsconfirm(G){var B=G.url;var M=G.result;var D=G.aid;
var L=G.docid;var A=G.tabid;var K=G.manualfill;var J=g_sites[D];var C=J.sharedfromaid!=null&&J.sharedfromaid!=""&&J.sharedfromaid!="0"&&J.sharedfromaid!="null"?1:0;if(J.save_all){if(!M||K){sendCS(A,{cmd:"fillbest",username:getusernamefromacct(J),password:getpasswordfromacct(J),docid:L,aid:J.aid,updatefields:0,sharedsite:C},G.docnum)
}}else{if(M){var J=g_sites[D];if(J){fill(A,J,L,null,false,G.docnum,null,true)}delete g_fillfieldsmatches[B]}else{if(G.allowforce){sendCS(A,{cmd:"fillbest",username:getusernamefromacct(J),password:getpasswordfromacct(J),docid:L,aid:J.aid,updatefields:0,sharedsite:C},G.docnum)}else{var H=g_fillfieldsmatches[B];
if(H){var I=false;for(var F=0;F<H.length;F++){var E=H[F]["aid"];if(I){var J=g_sites[E];if(J){fill(A,J,L,null,true,G.docnum,null,true)}return}if(E==D){I=true}}}delete g_fillfieldsmatches[B]}}}}function web2plug(B){if(B.rsa=="2"){g_local_key=AES.hex2bin(B.key);rsa_userchangedpassword();var A=opendb();createDataTable(A);
if(A&&!LPISLOC){A.transaction(function(C){C.executeSql("DELETE FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"accts"],function(D,E){},function(D,E){console.log(E)})})}lpWriteKeyFile()}else{if(g_username!=""&&g_username!=B.username){if(B.rsa=="1"){g_local_key=AES.hex2bin(B.key);
lpWriteKeyFile();lplogincheck(true)}else{loggedOut()}}else{g_local_key=AES.hex2bin(B.key);lpWriteKeyFile()}}}function recover(A,B,E,H){var D=lpParseUri(B);var G=D.directory;var C=D.file;G=G.replace(new RegExp("^/~[^/]*"),"");if(G!=""&&G!="/"&&G!="/sso/"){return}if(C!="recover.php"){return}var F=GetOTPHash(null,A,E,H);
var I="nouser";if(F!=""&&F!=null){I=AES.bin2hex(F)}console.log("hash after GetOTPHash for "+E+" is: "+I);sendCS(A,{cmd:"recover",otp:I},H)}function loginfromwebsite(C){if(C.wxusername!=""&&C.keyhex!=""){var B=opendb();createSavedLoginsTable(B);if(B){B.transaction(function(E){var F=new Date().getTime();
E.executeSql("UPDATE LastPassSavedLogins2 SET last_login = ? WHERE username = ?",[F,C.wxusername],function(G,H){if(H.rowsAffected==0){G.executeSql("INSERT INTO LastPassSavedLogins2 (username, password, last_login) VALUES (?, '', ?)",[C.wxusername,F])}},function(G,H){console.log(H)})})}var D=AES.hex2bin(C.keyhex);
var A=g_local_key!=null?AES.bin2hex(g_local_key):"";if(lploggedin&&g_username==C.wxusername&&A==C.keyhex){}else{if(lploggedin&&g_username==C.wxusername){g_local_key=D}else{if(lploggedin&&g_username!=""){loggedOut()}if(C.wxsessid!=""){lp_phpsessid=C.wxsessid}g_local_key=D;lpWriteKeyFile();LP.lplogincheck(true,null,C.wxusername,C.wxhash)
}}}else{if(!lploggedin){LP.lplogincheck(true)}}}function reorderOnURL(K,A,E,J){var H=lpParseUri(A);var I=lpcanonizeUrl(A,H);var B=typeof(H.path)=="string"?H.path.split("/"):new Array();var G=lp_gettld_url(A);var M=new Array();for(var D in K){if(!check_ident_aid(D)){continue}var L=g_sites[D];if(typeof(L)=="undefined"||typeof(L.url)=="undefined"){continue
}if(!L.save_all&&E&&L.unencryptedUsername==""&&L.password==""){continue}if(J&&!accthaspassword(L)){continue}var C=lpParseUri(L.url);L.realmmatch=0;L.servermatch=H.host==C.host;L.serverportmatch=(L.servermatch&&H.port==C.port?1:0);L.urlmatch=lpcanonizeUrl(L.url)==I?true:false;var N=typeof(C.path)=="string"?C.path.split("/"):new Array();
var F;for(F=0;F<B.length&&F<N.length;F++){if(N[F]!=B[F]){break}}L.pathlevelmatch=F;L.fieldmatchcount=0;M.push(L)}M.sort(lp_aids_sort_func);var O=typeof(H.path)=="string"?H.path:"";M=checkurlrules(g_urlrules,M,G,O,H.host,g_sites);return M}function lp_aids_sort_func(B,A){if(B.realmmatch!=A.realmmatch){return B.realmmatch?-1:1
}else{if(B.urlmatch!=A.urlmatch){return B.urlmatch?-1:1}else{if(B.serverportmatch&&A.serverportmatch&&B.pathlevelmatch!=A.pathlevelmatch){return B.pathlevelmatch>A.pathlevelmatch?-1:1}else{if(B.serverportmatch!=A.serverportmatch){return B.serverportmatch?-1:1}else{if(B.servermatch!=A.servermatch){return B.servermatch?-1:1
}else{if(B.fieldmatchcount!=A.fieldmatchcount){return B.fieldmatchcount>A.fieldmatchcount?-1:1}else{if(B.last_touch!=A.last_touch){return B.last_touch>A.last_touch?-1:1}else{if(B.name!=A.name){return B.name<A.name?-1:1}}}}}}}}return 0}function lp_sort_case_insensitive_name(B,A){B=B.name.toLowerCase();
A=A.name.toLowerCase();return B<A?-1:1}function launchautologin(A,C){if(!check_ident_aid(A)){return}var B=g_sites[A];if(!B){return}if(!C&&(B.pwprotect||g_prompts.login_site_prompt)){security_prompt(function(){launchautologin(A,true)});return}chrome.tabs.create({url:B.url},function(D){g_launches[D.id]=B.aid
})};
