(function(B){B.tree={datastores:{},plugins:{},defaults:{data:{async:false,type:"html",opts:{method:"GET",url:false}},selected:false,opened:[],languages:[],ui:{dots:true,animation:0,scroll_spd:4,theme_path:false,theme_name:"default",selected_parent_close:"select_parent",selected_delete:"select_previous"},types:{"default":{clickable:true,renameable:true,deletable:true,creatable:true,draggable:false,max_children:-1,max_depth:-1,valid_children:"all",icon:{image:false,position:false}}},rules:{multiple:false,multitree:"none",type_attr:"rel",createat:"bottom",drag_copy:"ctrl",drag_button:"left",use_max_children:true,use_max_depth:true,max_children:-1,max_depth:-1,valid_children:"all"},lang:{new_node:"New folder",loading:"Loading ..."},callback:{beforechange:function(C,D){return true
},beforeopen:function(C,D){return true},beforeclose:function(C,D){return true},beforemove:function(C,E,F,D){return true},beforecreate:function(C,E,F,D){return true},beforerename:function(C,E,D){return true},beforedelete:function(C,D){return true},beforedata:function(C,D){return{id:B(C).attr("id")||0}
},ondata:function(C,D){return C},onparse:function(D,C){return D},onhover:function(C,D){},onselect:function(C,D){},ondeselect:function(C,D){},onchange:function(C,D){},onrename:function(C,D,E){},onmove:function(C,E,G,D,F){},oncopy:function(C,E,G,D,F){},oncreate:function(C,E,G,D,F){},ondelete:function(C,D,E){},onopen:function(C,D){if(typeof(lponopen)=="function"){lponopen(C,D)
}},onopen_all:function(C){},onclose_all:function(C){},onclose:function(C,D){if(typeof(lponclose)=="function"){lponclose(C,D)}},error:function(D,C){},ondblclk:function(C,D){D.toggle_branch.call(D,C);D.select_branch.call(D,C)},onrgtclk:function(C,D,E){},onload:function(C){},oninit:function(C){},onfocus:function(C){},ondestroy:function(C){},onsearch:function(C,D){C.addClass("search")
},ondrop:function(C,E,F,D){},check:function(D,C,F,E){return F},check_move:function(C,E,F,D){return true}},plugins:{}},create:function(){return new A()},focused:function(){return A.inst[A.focused]},reference:function(C){var D=B(C);if(!D.size()){D=B("#"+C)}if(!D.size()){return null}D=(D.is(".tree"))?D.attr("id"):D.parents(".tree:eq(0)").attr("id");
return A.inst[D]||null},rollback:function(F){for(var E in F){if(!F.hasOwnProperty(E)){continue}var D=A.inst[E];var C=!D.locked;if(C){D.lock(true)}D.inp=false;D.container.html(F[E].html).find(".dragged").removeClass("dragged").end().find(".hover").removeClass("hover");if(F[E].selected){D.selected=B("#"+F[E].selected);
D.selected_arr=[];D.container.find("a.clicked").each(function(){D.selected_arr.push(D.get_node(this))})}if(C){D.lock(false)}delete C;delete D}},drop_mode:function(C){C=B.extend(C,{show:false,type:"default",str:"Foreign node"});A.drag_drop.foreign=true;A.drag_drop.isdown=true;A.drag_drop.moving=true;A.drag_drop.appended=false;
A.drag_drop.f_type=C.type;A.drag_drop.f_data=C;if(!C.show){A.drag_drop.drag_help=false;A.drag_drop.drag_node=false}else{A.drag_drop.drag_help=B("<div id='jstree-dragged' class='tree tree-default'><ul><li class='last dragged foreign'><a href='#'><ins>&nbsp;</ins>"+C.str+"</a></li></ul></div>");A.drag_drop.drag_node=A.drag_drop.drag_help.find("li:eq(0)")
}if(B.tree.drag_start!==false){B.tree.drag_start.call(null,false)}},drag_start:false,drag:false,drag_end:false};B.fn.tree=function(C){return this.each(function(){var D=B.extend({},C);if(A.inst&&A.inst[B(this).attr("id")]){A.inst[B(this).attr("id")].destroy()}if(D!==false){new A().init(this,D)}})};function A(){return{cntr:++A.cntr,settings:B.extend({},B.tree.defaults),init:function(H,E){var J=this;
this.container=B(H);if(this.container.size==0){return false}A.inst[this.cntr]=this;if(!this.container.attr("id")){this.container.attr("id","jstree_"+this.cntr)}A.inst[this.container.attr("id")]=A.inst[this.cntr];A.focused=this.cntr;this.settings=B.extend(true,{},this.settings,E);if(this.settings.languages&&this.settings.languages.length){this.current_lang=this.settings.languages[0];
var D=false;var I="#"+this.container.attr("id");for(var G=0;G<this.settings.languages.length;G++){D=A.add_css(I+" ."+this.settings.languages[G]);if(D!==false){D.style.display=(this.settings.languages[G]==this.current_lang)?"":"none"}}}else{this.current_lang=false}this.container.addClass("tree");if(this.settings.ui.theme_name!==false){if(this.settings.ui.theme_path===false){B("script").each(function(){if(this.src.toString().match(/jquery\.tree.*?js$/)){J.settings.ui.theme_path=this.src.toString().replace(/jquery\.tree.*?js$/,"")+"treestyle.css";
return false}})}if(this.settings.ui.theme_path!=""&&B.inArray(this.settings.ui.theme_path,A.themes)==-1){A.add_sheet({url:this.settings.ui.theme_path});A.themes.push(this.settings.ui.theme_path)}this.container.addClass("tree-"+this.settings.ui.theme_name)}var C="";for(var F in this.settings.types){if(!this.settings.types.hasOwnProperty(F)){continue
}if(!this.settings.types[F].icon){continue}if(this.settings.types[F].icon.image||this.settings.types[F].icon.position){if(F=="default"){C+="#"+this.container.attr("id")+" li > a ins { "}else{C+="#"+this.container.attr("id")+" li[rel="+F+"] > a ins { "}if(this.settings.types[F].icon.image){C+=" background-image:url("+this.settings.types[F].icon.image+"); "
}if(this.settings.types[F].icon.position){C+=" background-position:"+this.settings.types[F].icon.position+"; "}C+="} "}}if(C!=""){A.add_sheet({str:C})}if(this.settings.rules.multiple){this.selected_arr=[]}this.offset=false;this.hovered=false;this.locked=false;if(A.drag_drop.marker===false){A.drag_drop.marker=B("<div>").attr({id:"jstree-marker"}).hide().appendTo("body")
}this.callback("oninit",[this]);this.refresh();this.attach_events();this.focus()},refresh:function(D){if(this.locked){return this.error("LOCKED")}var F=this;if(D&&!this.settings.data.async){D=false}this.is_partial_refresh=D?true:false;this.opened=Array();if(this.settings.opened!=false){B.each(this.settings.opened,function(G,H){if(this.replace(/^#/,"").length>0){F.opened.push("#"+this.replace(/^#/,""))
}});this.settings.opened=false}else{this.container.find("li.open").each(function(G){if(this.id){F.opened.push("#"+this.id)}})}if(this.selected){this.settings.selected=Array();if(D){B(D).find("li:has(a.clicked)").each(function(){if(this.id){F.settings.selected.push("#"+this.id)}})}else{if(this.selected_arr){B.each(this.selected_arr,function(){if(this.attr("id")){F.settings.selected.push("#"+this.attr("id"))
}})}else{if(this.selected.attr("id")){this.settings.selected.push("#"+this.selected.attr("id"))}}}}else{if(this.settings.selected!==false){var C=Array();if((typeof this.settings.selected).toLowerCase()=="object"){B.each(this.settings.selected,function(){if(this.replace(/^#/,"").length>0){C.push("#"+this.replace(/^#/,""))
}})}else{if(this.settings.selected.replace(/^#/,"").length>0){C.push("#"+this.settings.selected.replace(/^#/,""))}}this.settings.selected=C}}if(D&&this.settings.data.async){this.opened=Array();D=this.get_node(D);D.find("li.open").each(function(G){F.opened.push("#"+this.id)});if(D.hasClass("open")){D.removeClass("open").addClass("closed")
}if(D.hasClass("leaf")){D.removeClass("leaf")}D.children("ul:eq(0)").html("");return this.open_branch(D,true,function(){F.reselect.apply(F)})}var F=this;var E=new B.tree.datastores[this.settings.data.type]();if(this.container.children("ul").size()==0){this.container.html("<ul class='ltr' style='direction:ltr;'><li class='last'><a class='loading' href='#'><ins>&nbsp;</ins>"+(this.settings.lang.loading||"Loading ...")+"</a></li></ul>")
}E.load(this.callback("beforedata",[false,this]),this,this.settings.data.opts,function(G){G=F.callback("ondata",[G,F]);E.parse(G,F,F.settings.data.opts,function(H){H=F.callback("onparse",[H,F]);F.container.empty().append(B("<ul class='ltr'>").html(H));F.container.find("li:last-child").addClass("last").end().find("li:has(ul)").not(".open").addClass("closed");
F.container.find("li").not(".open").not(".closed").addClass("leaf");F.reselect()})})},reselect:function(E){var G=this;if(!E){this.cl_count=0}else{this.cl_count--}if(this.opened&&this.opened.length){var F=false;for(var C=0;this.opened&&C<this.opened.length;C++){if(this.settings.data.async){var D=this.get_node(this.opened[C]);
if(D.size()&&D.hasClass("closed")>0){F=true;var D=this.opened[C].toString().replace("/","\\/");delete this.opened[C];this.open_branch(D,true,function(){G.reselect.apply(G,[true])});this.cl_count++}}else{this.open_branch(this.opened[C],true)}}if(this.settings.data.async&&F){return}if(this.cl_count>0){return
}delete this.opened}if(this.cl_count>0){return}this.container.css("direction","ltr").children("ul:eq(0)").addClass("ltr");if(this.settings.ui.dots==false){this.container.children("ul:eq(0)").addClass("no_dots")}if(this.scrtop){this.container.scrollTop(G.scrtop);delete this.scrtop}if(this.settings.selected!==false){B.each(this.settings.selected,function(H){if(G.is_partial_refresh){G.select_branch(B(G.settings.selected[H].toString().replace("/","\\/"),G.container),(G.settings.rules.multiple!==false))
}else{G.select_branch(B(G.settings.selected[H].toString().replace("/","\\/"),G.container),(G.settings.rules.multiple!==false&&H>0))}});this.settings.selected=false}this.callback("onload",[G])},get:function(E,D,C){if(!D){D=this.settings.data.type}if(!C){C=this.settings.data.opts}return new B.tree.datastores[D]().get(E,this,C)
},attach_events:function(){var C=this;this.container.bind("mousedown.jstree",function(D){if(A.drag_drop.isdown){A.drag_drop.move_type=false;D.preventDefault();D.stopPropagation();D.stopImmediatePropagation();return false}}).bind("mouseup.jstree",function(D){setTimeout(function(){C.focus.apply(C)},5)}).bind("click.jstree",function(D){return true
});B("li",this.container.get(0)).live("click",function(D){if(D.target.tagName!="LI"){return true}C.off_height();if(D.pageY-B(D.target).offset().top>C.li_height){return true}C.toggle_branch.apply(C,[D.target]);D.stopPropagation();return false});B("a",this.container.get(0)).live("click",function(D){if(D.which&&D.which==3){return true
}if(C.locked){D.preventDefault();D.target.blur();return C.error("LOCKED")}C.select_branch.apply(C,[D.target,D.ctrlKey||C.settings.rules.multiple=="on"]);if(C.inp){C.inp.blur()}D.preventDefault();D.target.blur();return false}).live("dblclick",function(D){if(C.locked){D.preventDefault();D.stopPropagation();
D.target.blur();return C.error("LOCKED")}C.callback("ondblclk",[C.get_node(D.target).get(0),C]);D.preventDefault();D.stopPropagation();D.target.blur()}).live("contextmenu",function(D){if(C.locked){D.target.blur();return C.error("LOCKED")}return C.callback("onrgtclk",[C.get_node(D.target).get(0),C,D])
}).live("mouseover",function(D){if(C.locked){D.preventDefault();D.stopPropagation();return C.error("LOCKED")}if(C.hovered!==false&&(D.target.tagName=="A"||D.target.tagName=="INS")){C.hovered.children("a").removeClass("hover");C.hovered=false}C.callback("onhover",[C.get_node(D.target).get(0),C])}).live("mousedown",function(G){if(C.settings.rules.drag_button=="left"&&G.which&&G.which!=1){return true
}if(C.settings.rules.drag_button=="right"&&G.which&&G.which!=3){return true}C.focus.apply(C);if(C.locked){return C.error("LOCKED")}var H=C.get_node(G.target);if(C.settings.rules.multiple!=false&&C.selected_arr.length>1&&H.children("a:eq(0)").hasClass("clicked")){var D=0;for(var F in C.selected_arr){if(!C.selected_arr.hasOwnProperty(F)){continue
}if(C.check("draggable",C.selected_arr[F])){C.selected_arr[F].addClass("dragged");A.drag_drop.origin_tree=C;D++}}if(D>0){if(C.check("draggable",H)){A.drag_drop.drag_node=H}else{A.drag_drop.drag_node=C.container.find("li.dragged:eq(0)")}A.drag_drop.isdown=true;A.drag_drop.drag_help=B("<div id='jstree-dragged' class='tree "+(C.settings.ui.theme_name!=""?" tree-"+C.settings.ui.theme_name:"")+"' />").append("<ul class='"+C.container.children("ul:eq(0)").get(0).className+"' />");
var E=A.drag_drop.drag_node.clone();if(C.settings.languages.length>0){E.find("a").not("."+C.current_lang).hide()}A.drag_drop.drag_help.children("ul:eq(0)").append(E);A.drag_drop.drag_help.find("li:eq(0)").removeClass("last").addClass("last").children("a").html("<ins>&nbsp;</ins>Multiple selection").end().children("ul").remove();
A.drag_drop.dragged=C.container.find("li.dragged")}}else{if(C.check("draggable",H)){A.drag_drop.drag_node=H;A.drag_drop.drag_help=B("<div id='jstree-dragged' class='tree "+(C.settings.ui.theme_name!=""?" tree-"+C.settings.ui.theme_name:"")+"' />").append("<ul class='"+C.container.children("ul:eq(0)").get(0).className+"' />");
var E=H.clone();if(C.settings.languages.length>0){E.find("a").not("."+C.current_lang).hide()}A.drag_drop.drag_help.children("ul:eq(0)").append(E);A.drag_drop.drag_help.find("li:eq(0)").removeClass("last").addClass("last");A.drag_drop.isdown=true;A.drag_drop.foreign=false;A.drag_drop.origin_tree=C;H.addClass("dragged");
A.drag_drop.dragged=C.container.find("li.dragged")}}A.drag_drop.init_x=G.pageX;A.drag_drop.init_y=G.pageY;H.blur();G.preventDefault();G.stopPropagation();return false})},focus:function(){if(this.locked){return false}if(A.focused!=this.cntr){A.focused=this.cntr;this.callback("onfocus",[this])}},off_height:function(){if(this.offset===false){this.container.css({position:"relative"});
this.offset=this.container.offset();var C=0;C=parseInt(B.curCSS(this.container.get(0),"paddingTop",true),10);if(C){this.offset.top+=C}C=parseInt(B.curCSS(this.container.get(0),"borderTopWidth",true),10);if(C){this.offset.top+=C}this.container.css({position:""})}if(typeof(LPFromWebsite)!="undefined"&&!this.li_height){this.li_height=20
}else{if(!this.li_height){var C=this.container.find("ul li.closed, ul li.leaf").eq(0);this.li_height=C.height();if(C.children("ul:eq(0)").size()){this.li_height-=C.children("ul:eq(0)").height()}if(!this.li_height){this.li_height=18}}}},scroll_check:function(D,J){var I=this;var F=I.container;var H=I.container.offset();
var E=F.scrollTop();var C=F.scrollLeft();var G=(F.get(0).scrollWidth>F.width())?40:20;if(J-H.top<20){F.scrollTop(Math.max((E-I.settings.ui.scroll_spd),0))}if(F.height()-(J-H.top)<G){F.scrollTop(E+I.settings.ui.scroll_spd)}if(D-H.left<20){F.scrollLeft(Math.max((C-I.settings.ui.scroll_spd),0))}if(F.width()-(D-H.left)<40){F.scrollLeft(C+I.settings.ui.scroll_spd)
}if(F.scrollLeft()!=C||F.scrollTop()!=E){A.drag_drop.move_type=false;A.drag_drop.ref_node=false;A.drag_drop.marker.hide()}A.drag_drop.scroll_time=setTimeout(function(){I.scroll_check(D,J)},50)},scroll_into_view:function(G){G=G?this.get_node(G):this.selected;if(!G){return false}var D=G.offset().top;var C=this.container.offset().top;
var E=C+this.container.height();var F=(this.container.get(0).scrollWidth>this.container.width())?40:20;if(D+5<C){this.container.scrollTop(this.container.scrollTop()-(C-D+5))}if(D+F>E){this.container.scrollTop(this.container.scrollTop()+(D+F-E))}},get_node:function(C){return B(C).closest("li")},get_type:function(D){D=!D?this.selected:this.get_node(D);
if(!D){return}var C=D.attr(this.settings.rules.type_attr);return C||"default"},set_type:function(D,C){C=!C?this.selected:this.get_node(C);if(!C||!D){return}C.attr(this.settings.rules.type_attr,D)},get_text:function(C,E){C=this.get_node(C);if(!C||C.size()==0){return""}if(this.settings.languages&&this.settings.languages.length){E=E?E:this.current_lang;
C=C.children("a."+E)}else{C=C.children("a:visible")}var D="";C.contents().each(function(){if(this.nodeType==3){D=this.data;return false}});return D},check:function(F,E){if(this.locked){return false}var C=false;if(E===-1){if(typeof this.settings.rules[F]!="undefined"){C=this.settings.rules[F]}}else{E=!E?this.selected:this.get_node(E);
if(!E){return}var D=this.get_type(E);if(typeof this.settings.types[D]!="undefined"&&typeof this.settings.types[D][F]!="undefined"){C=this.settings.types[D][F]}else{if(typeof this.settings.types["default"]!="undefined"&&typeof this.settings.types["default"][F]!="undefined"){C=this.settings.types["default"][F]
}}}if(typeof C=="function"){C=C.call(null,E,this)}C=this.callback("check",[F,E,C,this]);return C},check_move:function(P,J,K){if(this.locked){return false}if(B(J).closest("li.dragged").size()){return false}var N=P.parents(".tree:eq(0)").get(0);var L=J.parents(".tree:eq(0)").get(0);if(N&&N!=L){var F=B.tree.reference(L.id).settings.rules.multitree;
if(F=="none"||(B.isArray(F)&&B.inArray(N.id,F)==-1)){return false}}var E=(K!="inside")?this.parent(J):this.get_node(J);P=this.get_node(P);if(E==false){return false}var C={max_depth:this.settings.rules.use_max_depth?this.check("max_depth",E):-1,max_children:this.settings.rules.use_max_children?this.check("max_children",E):-1,valid_children:this.check("valid_children",E)};
var I=(typeof P=="string")?P:this.get_type(P);if(typeof C.valid_children!="undefined"&&(C.valid_children=="none"||(typeof C.valid_children=="object"&&B.inArray(I,B.makeArray(C.valid_children))==-1))){return false}if(this.settings.rules.use_max_children){if(typeof C.max_children!="undefined"&&C.max_children!=-1){if(C.max_children==0){return false
}var H=1;if(A.drag_drop.moving==true&&A.drag_drop.foreign==false){H=A.drag_drop.dragged.size();H=H-E.find("> ul > li.dragged").size()}if(C.max_children<E.find("> ul > li").size()+H){return false}}}if(this.settings.rules.use_max_depth){if(typeof C.max_depth!="undefined"&&C.max_depth===0){return this.error("MOVE: MAX-DEPTH REACHED")
}var M=(C.max_depth>0)?C.max_depth:false;var G=0;var O=E;while(O!==-1){O=this.parent(O);G++;var F=this.check("max_depth",O);if(F>=0){M=(M===false)?(F-G):Math.min(M,F-G)}if(M!==false&&M<=0){return this.error("MOVE: MAX-DEPTH REACHED")}}if(M!==false&&M<=0){return this.error("MOVE: MAX-DEPTH REACHED")}if(M!==false){var D=1;
if(typeof P!="string"){var O=P;while(O.size()>0){if(M-D<0){return this.error("MOVE: MAX-DEPTH REACHED")}O=O.children("ul").children("li");D++}}}}if(this.callback("check_move",[P,J,K,this])==false){return false}return true},hover_branch:function(C){if(this.locked){return this.error("LOCKED")}var D=this;
var C=D.get_node(C);if(!C.size()){return this.error("HOVER: NOT A VALID NODE")}if(!D.check("clickable",C)){return this.error("SELECT: NODE NOT SELECTABLE")}if(this.hovered){this.hovered.children("A").removeClass("hover")}this.hovered=C;this.hovered.children("a").addClass("hover");this.scroll_into_view(this.hovered)
},select_branch:function(E,C){if(this.locked){return this.error("LOCKED")}if(!E&&this.hovered!==false){E=this.hovered}var F=this;E=F.get_node(E);if(!E.size()){return this.error("SELECT: NOT A VALID NODE")}E.children("a").removeClass("hover");if(!F.check("clickable",E)){return this.error("SELECT: NODE NOT SELECTABLE")
}if(F.callback("beforechange",[E.get(0),F])===false){return this.error("SELECT: STOPPED BY USER")}if(this.settings.rules.multiple!=false&&C&&E.children("a.clicked").size()>0){return this.deselect_branch(E)}if(this.settings.rules.multiple!=false&&C){this.selected_arr.push(E)}if(this.settings.rules.multiple!=false&&!C){for(var D in this.selected_arr){if(!this.selected_arr.hasOwnProperty(D)){continue
}this.selected_arr[D].children("A").removeClass("clicked");this.selected_arr[D].removeClass("clicked");this.callback("ondeselect",[this.selected_arr[D].get(0),F])}this.selected_arr=[];this.selected_arr.push(E);if(this.selected&&this.selected.children("A").hasClass("clicked")){this.selected.children("A").removeClass("clicked");
this.selected.removeClass("clicked");this.callback("ondeselect",[this.selected.get(0),F])}}if(!this.settings.rules.multiple){if(this.selected){this.selected.children("A").removeClass("clicked");this.selected.removeClass("clicked");this.callback("ondeselect",[this.selected.get(0),F])}}this.selected=E;
if(this.hovered!==false){this.hovered.children("A").removeClass("hover");this.hovered=E}this.selected.children("a").addClass("clicked").end().parents("li.closed").each(function(){F.open_branch(this,true)});this.selected.addClass("clicked");this.scroll_into_view(this.selected);this.callback("onselect",[this.selected.get(0),F]);
this.callback("onchange",[this.selected.get(0),F])},deselect_branch:function(C){if(this.locked){return this.error("LOCKED")}var D=this;var C=this.get_node(C);if(C.children("a.clicked").size()==0){return this.error("DESELECT: NODE NOT SELECTED")}C.children("a").removeClass("clicked");C.removeClass("clicked");
this.callback("ondeselect",[C.get(0),D]);if(this.settings.rules.multiple!=false&&this.selected_arr.length>1){this.selected_arr=[];this.container.find("a.clicked").filter(":first-child").parent().each(function(){D.selected_arr.push(B(this))});if(C.get(0)==this.selected.get(0)){this.selected=this.selected_arr[0]
}}else{if(this.settings.rules.multiple!=false){this.selected_arr=[]}this.selected=false}this.callback("onchange",[C.get(0),D])},toggle_branch:function(C){if(this.locked){return this.error("LOCKED")}var C=this.get_node(C);if(C.hasClass("closed")){return this.open_branch(C)}if(C.hasClass("open")){return this.close_branch(C)
}},open_branch:function(D,C,G){var F=this;if(this.locked){return this.error("LOCKED")}var D=this.get_node(D);if(!D.size()){return this.error("OPEN: NO SUCH NODE")}if(D.hasClass("leaf")){return this.error("OPEN: OPENING LEAF NODE")}if(this.settings.data.async&&D.find("li").size()==0){if(this.callback("beforeopen",[D.get(0),this])===false){return this.error("OPEN: STOPPED BY USER")
}D.children("ul:eq(0)").remove().end().append("<ul><li class='last'><a class='loading' href='#'><ins>&nbsp;</ins>"+(F.settings.lang.loading||"Loading ...")+"</a></li></ul>");D.removeClass("closed").addClass("open");var E=new B.tree.datastores[this.settings.data.type]();E.load(this.callback("beforedata",[D,this]),this,this.settings.data.opts,function(H){H=F.callback("ondata",[H,F]);
if(!H||H.length==0){D.removeClass("closed").removeClass("open").addClass("leaf").children("ul").remove();if(G){G.call()}return}E.parse(H,F,F.settings.data.opts,function(I){I=F.callback("onparse",[I,F]);D.children("ul:eq(0)").replaceWith(B("<ul>").html(I));D.find("li:last-child").addClass("last").end().find("li:has(ul)").not(".open").addClass("closed");
D.find("li").not(".open").not(".closed").addClass("leaf");F.open_branch.apply(F,[D]);if(G){G.call()}})});return true}else{if(!this.settings.data.async){if(this.callback("beforeopen",[D.get(0),this])===false){return this.error("OPEN: STOPPED BY USER")}}if(parseInt(this.settings.ui.animation)>0&&!C){D.children("ul:eq(0)").css("display","none");
D.removeClass("closed").addClass("open");D.children("ul:eq(0)").slideDown(parseInt(this.settings.ui.animation),function(){B(this).css("display","");if(G){G.call()}})}else{D.removeClass("closed").addClass("open");if(G){G.call()}}this.callback("onopen",[D.get(0),this]);return true}},close_branch:function(D,C){if(this.locked){return this.error("LOCKED")
}var E=this;var D=this.get_node(D);if(!D.size()){return this.error("CLOSE: NO SUCH NODE")}if(E.callback("beforeclose",[D.get(0),E])===false){return this.error("CLOSE: STOPPED BY USER")}if(parseInt(this.settings.ui.animation)>0&&!C&&D.children("ul:eq(0)").size()==1){D.children("ul:eq(0)").slideUp(parseInt(this.settings.ui.animation),function(){if(D.hasClass("open")){D.removeClass("open").addClass("closed")
}B(this).css("display","")})}else{if(D.hasClass("open")){D.removeClass("open").addClass("closed")}}if(this.selected&&this.settings.ui.selected_parent_close!==false&&D.children("ul:eq(0)").find("a.clicked").size()>0){D.find("li:has(a.clicked)").each(function(){E.deselect_branch(this)});if(this.settings.ui.selected_parent_close=="select_parent"&&D.children("a.clicked").size()==0){this.select_branch(D,(this.settings.rules.multiple!=false&&this.selected_arr.length>0))
}}this.callback("onclose",[D.get(0),this])},open_all:function(D,F){if(this.locked){return this.error("LOCKED")}var E=this;D=D?this.get_node(D):this.container;var C=D.find("li.closed").size();if(!F){this.cl_count=0}else{this.cl_count--}if(C>0){this.cl_count+=C;D.find("li.closed").each(function(){var G=this;
E.open_branch.apply(E,[this,true,function(){E.open_all.apply(E,[G,true])}])})}else{if(this.cl_count==0){this.callback("onopen_all",[this])}}},close_all:function(C){if(this.locked){return this.error("LOCKED")}var D=this;C=C?this.get_node(C):this.container;C.find("li.open").each(function(){D.close_branch(this,true)
});this.callback("onclose_all",[this])},set_lang:function(D){if(!B.isArray(this.settings.languages)||this.settings.languages.length==0){return false}if(this.locked){return this.error("LOCKED")}if(!B.inArray(D,this.settings.languages)&&typeof this.settings.languages[D]!="undefined"){D=this.settings.languages[D]
}if(typeof D=="undefined"){return false}if(D==this.current_lang){return true}var C=false;var E="#"+this.container.attr("id");C=A.get_css(E+" ."+this.current_lang);if(C!==false){C.style.display="none"}C=A.get_css(E+" ."+D);if(C!==false){C.style.display=""}this.current_lang=D;return true},get_lang:function(){if(!B.isArray(this.settings.languages)||this.settings.languages.length==0){return false
}return this.current_lang},create:function(H,D,T){if(this.locked){return this.error("LOCKED")}var N=false;if(D==-1){N=true;D=this.container}else{D=D?this.get_node(D):this.selected}if(!N&&(!D||!D.size())){return this.error("CREATE: NO NODE SELECTED")}var E=T;var R=D;if(T=="before"){T=D.parent().children().index(D);
D=D.parents("li:eq(0)")}if(T=="after"){T=D.parent().children().index(D)+1;D=D.parents("li:eq(0)")}if(!N&&D.size()==0){N=true;D=this.container}if(!N){if(!this.check("creatable",D)){return this.error("CREATE: CANNOT CREATE IN NODE")}if(D.hasClass("closed")){if(this.settings.data.async&&D.children("ul").size()==0){var O=this;
return this.open_branch(D,true,function(){O.create.apply(O,[H,D,T])})}else{this.open_branch(D,true)}}}var C=false;if(!H){H={}}else{H=B.extend(true,{},H)}if(!H.attributes){H.attributes={}}if(!H.attributes[this.settings.rules.type_attr]){H.attributes[this.settings.rules.type_attr]=this.get_type(R)||"default"
}if(this.settings.languages.length){if(!H.data){H.data={};C=true}for(var P=0;P<this.settings.languages.length;P++){if(!H.data[this.settings.languages[P]]){H.data[this.settings.languages[P]]=((typeof this.settings.lang.new_node).toLowerCase()!="string"&&this.settings.lang.new_node[P])?this.settings.lang.new_node[P]:this.settings.lang.new_node
}}}else{if(!H.data){H.data=this.settings.lang.new_node;C=true}}H=this.callback("ondata",[H,this]);var L=B.tree.datastores.json().parse(H,this);L=this.callback("onparse",[L,this]);var G=B(L);if(G.children("ul").size()){if(!G.is(".open")){G.addClass("closed")}}else{G.addClass("leaf")}G.find("li:last-child").addClass("last").end().find("li:has(ul)").not(".open").addClass("closed");
G.find("li").not(".open").not(".closed").addClass("leaf");var K={max_depth:this.settings.rules.use_max_depth?this.check("max_depth",(N?-1:D)):-1,max_children:this.settings.rules.use_max_children?this.check("max_children",(N?-1:D)):-1,valid_children:this.check("valid_children",(N?-1:D))};var F=this.get_type(G);
if(typeof K.valid_children!="undefined"&&(K.valid_children=="none"||(B.isArray(K.valid_children)&&B.inArray(F,K.valid_children)==-1))){return this.error("CREATE: NODE NOT A VALID CHILD")}if(this.settings.rules.use_max_children){if(typeof K.max_children!="undefined"&&K.max_children!=-1&&K.max_children>=this.children(D).size()){return this.error("CREATE: MAX_CHILDREN REACHED")
}}if(this.settings.rules.use_max_depth){if(typeof K.max_depth!="undefined"&&K.max_depth===0){return this.error("CREATE: MAX-DEPTH REACHED")}var J=(K.max_depth>0)?K.max_depth:false;var P=0;var I=D;while(I!==-1&&!N){I=this.parent(I);P++;var M=this.check("max_depth",I);if(M>=0){J=(J===false)?(M-P):Math.min(J,M-P)
}if(J!==false&&J<=0){return this.error("CREATE: MAX-DEPTH REACHED")}}if(J!==false&&J<=0){return this.error("CREATE: MAX-DEPTH REACHED")}if(J!==false){var Q=1;var I=G;while(I.size()>0){if(J-Q<0){return this.error("CREATE: MAX-DEPTH REACHED")}I=I.children("ul").children("li");Q++}}}if((typeof T).toLowerCase()=="undefined"||T=="inside"){T=(this.settings.rules.createat=="top")?0:D.children("ul:eq(0)").children("li").size()
}if(D.children("ul").size()==0||(N==true&&D.children("ul").children("li").size()==0)){if(!N){var S=this.moved(G,D.children("a:eq(0)"),"inside",true)}else{var S=this.moved(G,this.container.children("ul:eq(0)"),"inside",true)}}else{if(E=="before"&&D.children("ul:eq(0)").children("li:nth-child("+(T+1)+")").size()){var S=this.moved(G,D.children("ul:eq(0)").children("li:nth-child("+(T+1)+")").children("a:eq(0)"),"before",true)
}else{if(E=="after"&&D.children("ul:eq(0)").children("li:nth-child("+(T)+")").size()){var S=this.moved(G,D.children("ul:eq(0)").children("li:nth-child("+(T)+")").children("a:eq(0)"),"after",true)}else{if(D.children("ul:eq(0)").children("li:nth-child("+(T+1)+")").size()){var S=this.moved(G,D.children("ul:eq(0)").children("li:nth-child("+(T+1)+")").children("a:eq(0)"),"before",true)
}else{var S=this.moved(G,D.children("ul:eq(0)").children("li:last").children("a:eq(0)"),"after",true)}}}}if(S===false){return this.error("CREATE: ABORTED")}if(C){this.select_branch(G.children("a:eq(0)"));this.rename()}return G},rename:function(H,E){if(this.locked){return this.error("LOCKED")}H=H?this.get_node(H):this.selected;
var I=this;if(!H||!H.size()){return this.error("RENAME: NO NODE SELECTED")}if(!this.check("renameable",H)){return this.error("RENAME: NODE NOT RENAMABLE")}if(!this.callback("beforerename",[H.get(0),I.current_lang,I])){return this.error("RENAME: STOPPED BY USER")}H.parents("li.closed").each(function(){I.open_branch(this)
});if(this.current_lang){H=H.find("a."+this.current_lang)}else{H=H.find("a:first")}var G={};G[this.container.attr("id")]=this.get_rollback();var F=H.children("ins").clone();if((typeof E).toLowerCase()=="string"){H.text(E).prepend(F);I.callback("onrename",[I.get_node(H).get(0),I,G])}else{var C="";H.contents().each(function(){if(this.nodeType==3){C=this.data;
return false}});I.inp=B("<input type='text' autocomplete='off' />");I.inp.val(C.replace(/&amp;/g,"&").replace(/&gt;/g,">").replace(/&lt;/g,"<")).bind("mousedown",function(J){J.stopPropagation()}).bind("mouseup",function(J){J.stopPropagation()}).bind("click",function(J){J.stopPropagation()}).bind("keyup",function(K){var J=K.keyCode||K.which;
if(J==27){this.value=C;this.blur();return}if(J==13){this.blur();return}});I.inp.blur(function(J){if(this.value==""){this.value=C}H.text(this.value).prepend(F);H.get(0).style.display="";H.prevAll("span").remove();I.inp=false;I.callback("onrename",[I.get_node(H).get(0),I,G])});var D=B("<span />").addClass(H.attr("class")).append(F).append(I.inp);
H.get(0).style.display="none";H.parent().prepend(D);I.inp.get(0).focus();I.inp.get(0).select()}},remove:function(G){if(this.locked){return this.error("LOCKED")}var H=this;var F={};F[this.container.attr("id")]=this.get_rollback();if(G&&(!this.selected||this.get_node(G).get(0)!=this.selected.get(0))){G=this.get_node(G);
if(G.size()){if(!this.check("deletable",G)){return this.error("DELETE: NODE NOT DELETABLE")}if(!this.callback("beforedelete",[G.get(0),H])){return this.error("DELETE: STOPPED BY USER")}$parent=G.parent();if(G.find("a.clicked").size()){var E=false;H.selected_arr=[];this.container.find("a.clicked").filter(":first-child").parent().each(function(){if(!E&&this==H.selected.get(0)){E=true
}if(B(this).parents().index(G)!=-1){return true}H.selected_arr.push(B(this))});if(E){this.selected=this.selected_arr[0]||false}}G=G.remove();$parent.children("li:last").addClass("last");if($parent.children("li").size()==0){$li=$parent.parents("li:eq(0)");$li.removeClass("open").removeClass("closed").addClass("leaf").children("ul").remove()
}this.callback("ondelete",[G.get(0),this,F])}}else{if(this.selected){if(!this.check("deletable",this.selected)){return this.error("DELETE: NODE NOT DELETABLE")}if(!this.callback("beforedelete",[this.selected.get(0),H])){return this.error("DELETE: STOPPED BY USER")}$parent=this.selected.parent();var G=this.selected;
if(this.settings.rules.multiple==false||this.selected_arr.length==1){var D=true;var C=this.settings.ui.selected_delete=="select_previous"?this.prev(this.selected):false}G=G.remove();$parent.children("li:last").addClass("last");if($parent.children("li").size()==0){$li=$parent.parents("li:eq(0)");$li.removeClass("open").removeClass("closed").addClass("leaf").children("ul").remove()
}if(!D&&this.settings.rules.multiple!=false){var H=this;this.selected_arr=[];this.container.find("a.clicked").filter(":first-child").parent().each(function(){H.selected_arr.push(B(this))});if(this.selected_arr.length>0){this.selected=this.selected_arr[0];this.remove()}}if(D&&C){this.select_branch(C)}this.callback("ondelete",[G.get(0),this,F])
}else{return this.error("DELETE: NO NODE SELECTED")}}},next:function(D,C){D=this.get_node(D);if(!D.size()){return false}if(C){return(D.nextAll("li").size()>0)?D.nextAll("li:eq(0)"):false}if(D.hasClass("open")){return D.find("li:eq(0)")}else{if(D.nextAll("li").size()>0){return D.nextAll("li:eq(0)")}else{return D.parents("li").next("li").eq(0)
}}},prev:function(D,C){D=this.get_node(D);if(!D.size()){return false}if(C){return(D.prevAll("li").size()>0)?D.prevAll("li:eq(0)"):false}if(D.prev("li").size()){var D=D.prev("li").eq(0);while(D.hasClass("open")){D=D.children("ul:eq(0)").children("li:last")}return D}else{return D.parents("li:eq(0)").size()?D.parents("li:eq(0)"):false
}},parent:function(C){C=this.get_node(C);if(!C.size()){return false}return C.parents("li:eq(0)").size()?C.parents("li:eq(0)"):-1},children:function(C){if(C===-1){return this.container.children("ul:eq(0)").children("li")}C=this.get_node(C);if(!C.size()){return false}return C.children("ul:eq(0)").children("li")
},toggle_dots:function(){if(this.settings.ui.dots){this.settings.ui.dots=false;this.container.children("ul:eq(0)").addClass("no_dots")}else{this.settings.ui.dots=true;this.container.children("ul:eq(0)").removeClass("no_dots")}},callback:function(C,D){var G=false;var F=null;for(var E in this.settings.plugins){if(typeof B.tree.plugins[E]!="object"){continue
}G=B.tree.plugins[E];if(G.callbacks&&typeof G.callbacks[C]=="function"){F=G.callbacks[C].apply(this,D)}if(typeof F!=="undefined"&&F!==null){if(C=="ondata"||C=="onparse"){D[0]=F}else{return F}}}G=this.settings.callback[C];if(typeof G=="function"){return G.apply(null,D)}},get_rollback:function(){var C={};
C.html=this.container.html();C.selected=this.selected?this.selected.attr("id"):false;return C},moved:function(O,J,P,C,Q,D){var O=B(O);var F=B(O).parents("ul:eq(0)");var G=B(J);if(G.is("ins")){G=G.parent()}if(!D){var D={};D[this.container.attr("id")]=this.get_rollback();if(!C){var I=O.size()>1?O.eq(0).parents(".tree:eq(0)"):O.parents(".tree:eq(0)");
if(I.get(0)!=this.container.get(0)){I=A.inst[I.attr("id")];D[I.container.attr("id")]=I.get_rollback()}delete I}}if(P=="inside"&&this.settings.data.async){var K=this;if(this.get_node(G).hasClass("closed")){return this.open_branch(this.get_node(G),true,function(){K.moved.apply(K,[O,J,P,C,Q,D])})}if(this.get_node(G).find("> ul > li > a.loading").size()==1){setTimeout(function(){K.moved.apply(K,[O,J,P,C,Q])
},200);return}}if(O.size()>1){var K=this;var I=this.moved(O.eq(0),J,P,false,Q,D);O.each(function(R){if(R==0){return}if(I){I=K.moved(this,I.children("a:eq(0)"),"after",false,Q,D)}});return O}if(Q){_what=O.clone();_what.each(function(R){this.id=this.id+"_copy";B(this).find("li").each(function(){this.id=this.id+"_copy"
});B(this).removeClass("dragged").find("a.clicked").removeClass("clicked").end().find("li.dragged").removeClass("dragged");B(this).removeClass("dragged").find("li.clicked").removeClass("clicked").end().find("li.dragged").removeClass("dragged")})}else{_what=O}if(C){if(!this.callback("beforecreate",[this.get_node(O).get(0),this.get_node(J).get(0),P,this])){return false
}}else{if(!this.callback("beforemove",[this.get_node(O).get(0),this.get_node(J).get(0),P,this])){return false}}if(!C){var I=O.parents(".tree:eq(0)");if(I.get(0)!=this.container.get(0)){I=A.inst[I.attr("id")];if(I.settings.languages.length){var M=[];if(this.settings.languages.length==0){M.push("."+I.current_lang)
}else{for(var H in this.settings.languages){if(!this.settings.languages.hasOwnProperty(H)){continue}for(var E in I.settings.languages){if(!I.settings.languages.hasOwnProperty(E)){continue}if(this.settings.languages[H]==I.settings.languages[E]){M.push("."+this.settings.languages[H])}}}}if(M.length==0){return this.error("MOVE: NO COMMON LANGUAGES")
}_what.find("a").not(M.join(",")).remove()}_what.find("a.clicked").removeClass("clicked");_what.find("li.clicked").removeClass("clicked")}}O=_what;switch(P){case"before":G.parents("ul:eq(0)").children("li.last").removeClass("last");G.parent().before(O.removeClass("last"));G.parents("ul:eq(0)").children("li:last").addClass("last");
break;case"after":G.parents("ul:eq(0)").children("li.last").removeClass("last");G.parent().after(O.removeClass("last"));G.parents("ul:eq(0)").children("li:last").addClass("last");break;case"inside":if(G.parent().children("ul:first").size()){if(this.settings.rules.createat=="top"){G.parent().children("ul:first").prepend(O.removeClass("last")).children("li:last").addClass("last");
var L=G.parent().children("ul:first").children("li:first");if(L.size()){P="before";J=L}}else{var L=G.parent().children("ul:first").children(".last");if(L.size()){P="after";J=L}G.parent().children("ul:first").children(".last").removeClass("last").end().append(O.removeClass("last")).children("li:last").addClass("last")
}}else{O.addClass("last");G.parent().removeClass("leaf").append("<ul/>");if(!G.parent().hasClass("open")){G.parent().addClass("closed")}G.parent().children("ul:first").prepend(O)}if(G.parent().hasClass("closed")){this.open_branch(G)}break;default:break}if(F.find("li").size()==0){var N=F.parent();N.removeClass("open").removeClass("closed").addClass("leaf");
if(!N.is(".tree")){N.children("ul").remove()}N.parents("ul:eq(0)").children("li.last").removeClass("last").end().children("li:last").addClass("last")}else{F.children("li.last").removeClass("last");F.children("li:last").addClass("last")}if(Q){this.callback("oncopy",[this.get_node(O).get(0),this.get_node(J).get(0),P,this,D])
}else{if(C){this.callback("oncreate",[this.get_node(O).get(0),(G.is("ul")?-1:this.get_node(J).get(0)),P,this,D])}else{this.callback("onmove",[this.get_node(O).get(0),this.get_node(J).get(0),P,this,D])}}return O},error:function(C){this.callback("error",[C,this]);return false},lock:function(C){this.locked=C;
if(this.locked){this.container.children("ul:eq(0)").addClass("locked")}else{this.container.children("ul:eq(0)").removeClass("locked")}},cut:function(C){if(this.locked){return this.error("LOCKED")}C=C?this.get_node(C):this.container.find("a.clicked").filter(":first-child").parent();if(!C||!C.size()){return this.error("CUT: NO NODE SELECTED")
}A.cut_copy.copy_nodes=false;A.cut_copy.cut_nodes=C},copy:function(C){if(this.locked){return this.error("LOCKED")}C=C?this.get_node(C):this.container.find("a.clicked").filter(":first-child").parent();if(!C||!C.size()){return this.error("COPY: NO NODE SELECTED")}A.cut_copy.copy_nodes=C;A.cut_copy.cut_nodes=false
},paste:function(G,C){if(this.locked){return this.error("LOCKED")}var E=false;if(G==-1){E=true;G=this.container}else{G=G?this.get_node(G):this.selected}if(!E&&(!G||!G.size())){return this.error("PASTE: NO NODE SELECTED")}if(!A.cut_copy.copy_nodes&&!A.cut_copy.cut_nodes){return this.error("PASTE: NOTHING TO DO")
}var I=this;var H=C;if(C=="before"){C=G.parent().children().index(G);G=G.parents("li:eq(0)")}else{if(C=="after"){C=G.parent().children().index(G)+1;G=G.parents("li:eq(0)")}else{if((typeof C).toLowerCase()=="undefined"||C=="inside"){C=(this.settings.rules.createat=="top")?0:G.children("ul:eq(0)").children("li").size()
}}}if(!E&&G.size()==0){E=true;G=this.container}if(A.cut_copy.copy_nodes&&A.cut_copy.copy_nodes.size()){var F=true;if(!E&&!this.check_move(A.cut_copy.copy_nodes,G.children("a:eq(0)"),"inside")){return false}if(G.children("ul").size()==0||(E==true&&G.children("ul").children("li").size()==0)){if(!E){var D=this.moved(A.cut_copy.copy_nodes,G.children("a:eq(0)"),"inside",false,true)
}else{var D=this.moved(A.cut_copy.copy_nodes,this.container.children("ul:eq(0)"),"inside",false,true)}}else{if(H=="before"&&G.children("ul:eq(0)").children("li:nth-child("+(C+1)+")").size()){var D=this.moved(A.cut_copy.copy_nodes,G.children("ul:eq(0)").children("li:nth-child("+(C+1)+")").children("a:eq(0)"),"before",false,true)
}else{if(H=="after"&&G.children("ul:eq(0)").children("li:nth-child("+(C)+")").size()){var D=this.moved(A.cut_copy.copy_nodes,G.children("ul:eq(0)").children("li:nth-child("+(C)+")").children("a:eq(0)"),"after",false,true)}else{if(G.children("ul:eq(0)").children("li:nth-child("+(C+1)+")").size()){var D=this.moved(A.cut_copy.copy_nodes,G.children("ul:eq(0)").children("li:nth-child("+(C+1)+")").children("a:eq(0)"),"before",false,true)
}else{var D=this.moved(A.cut_copy.copy_nodes,G.children("ul:eq(0)").children("li:last").children("a:eq(0)"),"after",false,true)}}}}A.cut_copy.copy_nodes=false}if(A.cut_copy.cut_nodes&&A.cut_copy.cut_nodes.size()){var F=true;G.parents().andSelf().each(function(){if(A.cut_copy.cut_nodes.index(this)!=-1){F=false;
return false}});if(!F){return this.error("Invalid paste")}if(!E&&!this.check_move(A.cut_copy.cut_nodes,G.children("a:eq(0)"),"inside")){return false}if(G.children("ul").size()==0||(E==true&&G.children("ul").children("li").size()==0)){if(!E){var D=this.moved(A.cut_copy.cut_nodes,G.children("a:eq(0)"),"inside")
}else{var D=this.moved(A.cut_copy.cut_nodes,this.container.children("ul:eq(0)"),"inside")}}else{if(H=="before"&&G.children("ul:eq(0)").children("li:nth-child("+(C+1)+")").size()){var D=this.moved(A.cut_copy.cut_nodes,G.children("ul:eq(0)").children("li:nth-child("+(C+1)+")").children("a:eq(0)"),"before")
}else{if(H=="after"&&G.children("ul:eq(0)").children("li:nth-child("+(C)+")").size()){var D=this.moved(A.cut_copy.cut_nodes,G.children("ul:eq(0)").children("li:nth-child("+(C)+")").children("a:eq(0)"),"after")}else{if(G.children("ul:eq(0)").children("li:nth-child("+(C+1)+")").size()){var D=this.moved(A.cut_copy.cut_nodes,G.children("ul:eq(0)").children("li:nth-child("+(C+1)+")").children("a:eq(0)"),"before")
}else{var D=this.moved(A.cut_copy.cut_nodes,G.children("ul:eq(0)").children("li:last").children("a:eq(0)"),"after")}}}}A.cut_copy.cut_nodes=false}},search:function(I,C){var H=this;if(!I||(this.srch&&I!=this.srch)){this.srch="";this.srch_opn=false;this.container.find("a.search").removeClass("search")}this.srch=I;
if(!I){return}if(!C){C="contains"}if(this.settings.data.async){if(!this.srch_opn){var J=B.extend({search:I},this.callback("beforedata",[false,this]));B.ajax({type:this.settings.data.opts.method,url:this.settings.data.opts.url,data:J,dataType:"text",success:function(L){H.srch_opn=B.unique(L.split(","));
H.search.apply(H,[I,C])}})}else{if(this.srch_opn.length){if(this.srch_opn&&this.srch_opn.length){var E=false;for(var F=0;F<this.srch_opn.length;F++){if(this.get_node("#"+this.srch_opn[F]).size()>0){E=true;var G="#"+this.srch_opn[F];delete this.srch_opn[F];this.open_branch(G,true,function(){H.search.apply(H,[I,C])
})}}if(!E){this.srch_opn=[];H.search.apply(H,[I,C])}}}else{this.srch_opn=false;var D="a";if(this.settings.languages.length){D+="."+this.current_lang}this.callback("onsearch",[this.container.find(D+":"+C+"('"+I+"')"),this])}}}else{var D="a";if(this.settings.languages.length){D+="."+this.current_lang}var K=this.container.find(D+":"+C+"('"+I+"')");
K.parents("li.closed").each(function(){H.open_branch(this,true)});this.callback("onsearch",[K,this])}},add_sheet:A.add_sheet,destroy:function(){this.callback("ondestroy",[this]);this.container.unbind(".jstree");B("#"+this.container.attr("id")).die("click.jstree").die("dblclick.jstree").die("mouseover.jstree").die("mouseout.jstree").die("mousedown.jstree");
this.container.removeClass("tree ui-widget ui-widget-content tree-default tree-"+this.settings.ui.theme_name).children("ul").removeClass("no_dots ltr locked").find("li").removeClass("leaf").removeClass("open").removeClass("closed").removeClass("last").children("a").removeClass("clicked hover search");
if(this.cntr==A.focused){for(var C in A.inst){if(C!=this.cntr&&C!=this.container.attr("id")){A.inst[C].focus();break}}}A.inst[this.cntr]=false;A.inst[this.container.attr("id")]=false;delete A.inst[this.cntr];delete A.inst[this.container.attr("id")];A.cntr--}}}A.cntr=0;A.inst={};A.themes=[];A.drag_drop={isdown:false,drag_node:false,drag_help:false,dragged:false,init_x:false,init_y:false,moving:false,origin_tree:false,marker:false,move_type:false,ref_node:false,appended:false,foreign:false,droppable:[],open_time:false,scroll_time:false};
A.mouseup=function(E){var D=A.drag_drop;if(D.open_time){clearTimeout(D.open_time)}if(D.scroll_time){clearTimeout(D.scroll_time)}if(D.moving&&B.tree.drag_end!==false){B.tree.drag_end.call(null,E,D)}if(D.foreign===false&&D.drag_node&&D.drag_node.size()){D.drag_help.remove();if(D.move_type){var C=A.inst[D.ref_node.parents(".tree:eq(0)").attr("id")];
if(C){C.moved(D.dragged,D.ref_node,D.move_type,false,(D.origin_tree.settings.rules.drag_copy=="on"||(D.origin_tree.settings.rules.drag_copy=="ctrl"&&E.ctrlKey)))}}D.move_type=false;D.ref_node=false}if(D.foreign!==false){if(D.drag_help){D.drag_help.remove()}if(D.move_type){var C=A.inst[D.ref_node.parents(".tree:eq(0)").attr("id")];
if(C){C.callback("ondrop",[D.f_data,C.get_node(D.ref_node).get(0),D.move_type,C])}}D.foreign=false;D.move_type=false;D.ref_node=false}if(A.drag_drop.marker){A.drag_drop.marker.hide()}if(D.dragged&&D.dragged.size()){D.dragged.removeClass("dragged")}D.dragged=false;D.drag_help=false;D.drag_node=false;D.f_type=false;
D.f_data=false;D.init_x=false;D.init_y=false;D.moving=false;D.appended=false;D.origin_tree=false;if(D.isdown){D.isdown=false;E.preventDefault();E.stopPropagation();return false}};A.mousemove=function(C){var G=A.drag_drop;var L=false;if(G.isdown){if(!G.moving&&Math.abs(G.init_x-C.pageX)<5&&Math.abs(G.init_y-C.pageY)<5){C.preventDefault();
C.stopPropagation();return false}else{if(!G.moving){A.drag_drop.moving=true;L=true}}if(G.open_time){clearTimeout(G.open_time)}if(G.drag_help!==false){if(!G.appended){if(G.foreign!==false){G.origin_tree=B.tree.focused()}B("body").append(G.drag_help);G.w=G.drag_help.width();G.appended=true}G.drag_help.css({left:(C.pageX+5),top:(C.pageY+15)})
}if(L&&B.tree.drag_start!==false){B.tree.drag_start.call(null,C,G)}if(B.tree.drag!==false){B.tree.drag.call(null,C,G)}if(C.target.tagName=="DIV"&&C.target.id=="jstree-marker"){return false}var J=B(C.target);if(J.is("ins")){J=J.parent()}var E=J.is(".tree")?J:J.parents(".tree:eq(0)");if(E.size()==0||!A.inst[E.attr("id")]){if(G.scroll_time){clearTimeout(G.scroll_time)
}if(G.drag_help!==false){G.drag_help.find("li:eq(0) ins").addClass("forbidden")}G.move_type=false;G.ref_node=false;A.drag_drop.marker.hide();return false}var K=A.inst[E.attr("id")];K.off_height();if(G.scroll_time){clearTimeout(G.scroll_time)}G.scroll_time=setTimeout(function(){K.scroll_check(C.pageX,C.pageY)
},50);var N=false;var O=E.scrollTop();if(C.target.tagName=="A"||C.target.tagName=="INS"){if(J.is("#jstree-dragged")){return false}if(K.get_node(C.target).hasClass("closed")){G.open_time=setTimeout(function(){K.open_branch(J)},500)}var F=J.offset();var D={x:(F.left-1),y:(C.pageY-F.top)};var H=[];if(D.y<K.li_height/3+1){H=["before","inside","after"]
}else{if(D.y>K.li_height*2/3-1){H=["after","inside","before"]}else{if(D.y<K.li_height/2){H=["inside","before","after"]}else{H=["inside","after","before"]}}}var I=false;var M=(G.foreign==false)?G.origin_tree.container.find("li.dragged"):G.f_type;B.each(H,function(P,Q){if(K.check_move(M,J,Q)){N=Q;I=true;
return false}});if(I){switch(N){case"before":D.y=F.top-2;A.drag_drop.marker.attr("class","marker");break;case"after":D.y=F.top-2+K.li_height;A.drag_drop.marker.attr("class","marker");break;case"inside":D.x-=2;D.y=F.top-2+K.li_height/2;A.drag_drop.marker.attr("class","marker_plus");break}G.move_type=N;
G.ref_node=B(C.target);if(G.drag_help!==false){G.drag_help.find(".forbidden").removeClass("forbidden")}A.drag_drop.marker.css({left:D.x,top:D.y}).show()}}if((J.is(".tree")||J.is("ul"))&&J.find("li:eq(0)").size()==0){var F=J.offset();G.move_type="inside";G.ref_node=E.children("ul:eq(0)");if(G.drag_help!==false){G.drag_help.find(".forbidden").removeClass("forbidden")
}A.drag_drop.marker.attr("class","marker_plus");A.drag_drop.marker.css({left:(F.left+10),top:F.top+15}).show()}else{if((C.target.tagName!="A"&&C.target.tagName!="INS")||!I){if(G.drag_help!==false){G.drag_help.find("li:eq(0) ins").addClass("forbidden")}G.move_type=false;G.ref_node=false;A.drag_drop.marker.hide()
}}C.preventDefault();C.stopPropagation();return false}return true};B(function(){B(document).bind("mousemove.jstree",A.mousemove);B(document).bind("mouseup.jstree",A.mouseup)});A.cut_copy={copy_nodes:false,cut_nodes:false};A.css=false;A.get_css=function(F,D){F=F.toLowerCase();var E=A.css.cssRules||A.css.rules;
var C=0;do{if(E.length&&C>E.length+5){return false}if(E[C].selectorText&&E[C].selectorText.toLowerCase()==F){if(D==true){if(A.css.removeRule){document.styleSheets[i].removeRule(C)}if(A.css.deleteRule){document.styleSheets[i].deleteRule(C)}return true}else{return E[C]}}}while(E[++C]);return false};A.add_css=function(C){if(A.get_css(C)){return false
}(A.css.insertRule)?A.css.insertRule(C+" { }",0):A.css.addRule(C,null,0);return A.get_css(C)};A.remove_css=function(C){return A.get_css(C,true)};A.add_sheet=function(D){if(D.str){var C=document.createElement("style");C.setAttribute("type","text/css");if(C.styleSheet){document.getElementsByTagName("head")[0].appendChild(C);
C.styleSheet.cssText=D.str}else{C.appendChild(document.createTextNode(D.str));document.getElementsByTagName("head")[0].appendChild(C)}return C.sheet||C.styleSheet}if(D.url){if(document.createStyleSheet){try{document.createStyleSheet(D.url)}catch(F){}}else{var E=document.createElement("link");E.rel="stylesheet";
E.type="text/css";E.media="all";E.href=D.url;document.getElementsByTagName("head")[0].appendChild(E);return E.styleSheet}}};B(function(){var D=navigator.userAgent.toLowerCase();var C=(D.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1];var E='/* TREE LAYOUT */ .tree ul { margin:0 0 0 5px; padding:0 0 0 0; list-style-type:none; } .tree li { display:block; min-height:18px; line-height:18px; padding:0 0 0 15px; margin:0 0 0 0; /* Background fix */ clear:both; } .tree li ul { display:none; } .tree li a, .tree li span { display:inline-block;line-height:16px;height:16px;color:black;white-space:nowrap;text-decoration:none;padding:1px 2px 1px 2px;margin:0; } .tree li a:focus { outline: none; } .tree li a input, .tree li span input { margin:0;padding:0 0;display:inline-block;height:12px !important;border:1px solid white;background:white;font-size:10px;font-family:Verdana; } .tree li a input:not([class="xxx"]), .tree li span input:not([class="xxx"]) { padding:1px 0; } /* FOR DOTS */ .tree .ltr li.last { float:left; } .tree > ul li.last { overflow:hidden; } /* OPEN OR CLOSE */ .tree li.open ul { display:block; } .tree li.closed ul { display:none !important; } /* FOR DRAGGING */ #jstree-dragged { position:absolute; top:-10px; left:-10px; margin:0; padding:0; } #jstree-dragged ul ul ul { display:none; } #jstree-marker { padding:0; margin:0; line-height:5px; font-size:1px; overflow:hidden; height:5px; position:absolute; left:-45px; top:-30px; z-index:1000; background-color:transparent; background-repeat:no-repeat; display:none; } #jstree-marker.marker { width:45px; background-position:-32px top; } #jstree-marker.marker_plus { width:5px; background-position:right top; } /* BACKGROUND DOTS */ .tree li li { overflow:hidden; } .tree > .ltr > li { display:table; } /* ICONS */ .tree ul ins { display:inline-block; text-decoration:none; width:16px; height:16px; } .tree .ltr ins { margin:0 4px 0 0px; } ';
if(B.browser.msie){if(B.browser.version==6){E+='.tree li { height:18px; zoom:1; } .tree li li { overflow:visible; } .tree .ltr li.last { margin-top: expression( (this.previousSibling && /open/.test(this.previousSibling.className) ) ? "-2px" : "0"); } .marker { width:45px; background-position:-32px top; } .marker_plus { width:5px; background-position:right top; }'
}if(B.browser.version==7){E+='.tree li li { overflow:visible; } .tree .ltr li.last { margin-top: expression( (this.previousSibling && /open/.test(this.previousSibling.className) ) ? "-2px" : "0"); }'}}if(B.browser.opera){E+='.tree > ul > li.last:after { content:"."; display: block; height:1px; clear:both; visibility:hidden; }'
}if(B.browser.mozilla&&B.browser.version.indexOf("1.8")==0){E+=".tree .ltr li a { display:inline; float:left; } .tree li ul { clear:both; }"}A.css=A.add_sheet({str:E})})})(jQuery);(function(A){A.extend(A.tree.datastores,{html:function(){return{get:function(D,B,C){return D&&A(D).size()?A("<div>").append(B.get_node(D).clone()).html():B.container.children("ul:eq(0)").html()
},parse:function(D,B,C,E){if(E){E.call(null,D)}return D},load:function(D,B,C,E){if(C.url){A.ajax({type:C.method,url:C.url,data:D,dataType:"html",success:function(F,G){E.call(null,F)},error:function(G,H,F){E.call(null,false);B.error(F+" "+H)}})}else{E.call(null,C["static"]||B.container.children("ul:eq(0)").html())
}}}},json:function(){return{get:function(E,K,B){var H=this;if(!E||A(E).size()==0){E=K.container.children("ul").children("li")}else{E=A(E)}if(!B){B={}}if(!B.outer_attrib){B.outer_attrib=["id","rel","class"]}if(!B.inner_attrib){B.inner_attrib=[]}if(E.size()>1){var G=[];E.each(function(){G.push(H.get(this,K,B))
});return G}if(E.size()==0){return[]}var J={attributes:{},data:{}};if(E.hasClass("open")){J.data.state="open"}if(E.hasClass("closed")){J.data.state="closed"}for(var F in B.outer_attrib){if(!B.outer_attrib.hasOwnProperty(F)){continue}var C=(B.outer_attrib[F]=="class")?E.attr(B.outer_attrib[F]).replace(/(^| )last( |$)/ig," ").replace(/(^| )(leaf|closed|open)( |$)/ig," "):E.attr(B.outer_attrib[F]);
if(typeof C!="undefined"&&C.toString().replace(" ","").length>0){J.attributes[B.outer_attrib[F]]=C}delete C}if(K.settings.languages.length){for(var F in K.settings.languages){if(!K.settings.languages.hasOwnProperty(F)){continue}var I=E.children("a."+K.settings.languages[F]);if(B.force||B.inner_attrib.length||I.children("ins").get(0).style.backgroundImage.toString().length||I.children("ins").get(0).className.length){J.data[K.settings.languages[F]]={};
J.data[K.settings.languages[F]].title=K.get_text(E,K.settings.languages[F]);if(I.children("ins").get(0).style.className.length){J.data[K.settings.languages[F]].icon=I.children("ins").get(0).style.className}if(I.children("ins").get(0).style.backgroundImage.length){J.data[K.settings.languages[F]].icon=I.children("ins").get(0).style.backgroundImage.replace("url(","").replace(")","")
}if(B.inner_attrib.length){J.data[K.settings.languages[F]].attributes={};for(var D in B.inner_attrib){if(!B.inner_attrib.hasOwnProperty(D)){continue}var C=I.attr(B.inner_attrib[D]);if(typeof C!="undefined"&&C.toString().replace(" ","").length>0){J.data[K.settings.languages[F]].attributes[B.inner_attrib[D]]=C
}delete C}}}else{J.data[K.settings.languages[F]]=K.get_text(E,K.settings.languages[F])}}}else{var I=E.children("a");J.data.title=K.get_text(E);if(I.children("ins").size()&&I.children("ins").get(0).className.length){J.data.icon=I.children("ins").get(0).className}if(I.children("ins").size()&&I.children("ins").get(0).style.backgroundImage.length){J.data.icon=I.children("ins").get(0).style.backgroundImage.replace("url(","").replace(")","")
}if(B.inner_attrib.length){J.data.attributes={};for(var D in B.inner_attrib){if(!B.inner_attrib.hasOwnProperty(D)){continue}var C=I.attr(B.inner_attrib[D]);if(typeof C!="undefined"&&C.toString().replace(" ","").length>0){J.data.attributes[B.inner_attrib[D]]=C}delete C}}}if(E.children("ul").size()>0){J.children=[];
E.children("ul").children("li").each(function(){J.children.push(H.get(this,K,B))})}return J},parse:function(D,J,B,H){if(Object.prototype.toString.apply(D)==="[object Array]"){var G="";for(var E=0;E<D.length;E++){if(typeof D[E]=="function"){continue}G+=this.parse(D[E],J,B)}if(H){H.call(null,G)}return G
}if(!D||!D.data){if(H){H.call(null,false)}return""}var G="";G+="<li ";var I=false;if(D.attributes){for(var E in D.attributes){if(!D.attributes.hasOwnProperty(E)){continue}if(E=="class"){G+=" class='"+D.attributes[E]+" ";if(D.state=="closed"||D.state=="open"){G+=" "+D.state+" "}G+="' ";I=true}else{G+=" "+E+"='"+D.attributes[E]+"' "
}}}if(!I&&(D.state=="closed"||D.state=="open")){G+=" class='"+D.state+"' "}G+=">";if(J.settings.languages.length){for(var E=0;E<J.settings.languages.length;E++){var F={};F.href="";F.style="";F["class"]=J.settings.languages[E];if(D.data[J.settings.languages[E]]&&(typeof D.data[J.settings.languages[E]].attributes).toLowerCase()!="undefined"){for(var C in D.data[J.settings.languages[E]].attributes){if(!D.data[J.settings.languages[E]].attributes.hasOwnProperty(C)){continue
}if(C=="style"||C=="class"){F[C]+=" "+D.data[J.settings.languages[E]].attributes[C]}else{F[C]=D.data[J.settings.languages[E]].attributes[C]}}}G+="<a";for(var C in F){if(!F.hasOwnProperty(C)){continue}G+=" "+C+'="'+F[C]+'" '}G+=">";if(D.data[J.settings.languages[E]]&&D.data[J.settings.languages[E]].icon){G+="<ins "+(D.data[J.settings.languages[E]].icon.indexOf("/")==-1?" class='"+D.data[J.settings.languages[E]].icon+"' ":" style='background-image:url(\""+D.data[J.settings.languages[E]].icon+"\");' ")+">&nbsp;</ins>"
}else{G+="<ins>&nbsp;</ins>"}G+=((typeof D.data[J.settings.languages[E]].title).toLowerCase()!="undefined"?D.data[J.settings.languages[E]].title:D.data[J.settings.languages[E]])+"</a>"}}else{var F={};F.href="";F.style="";F["class"]="";if((typeof D.data.attributes).toLowerCase()!="undefined"){for(var E in D.data.attributes){if(!D.data.attributes.hasOwnProperty(E)){continue
}if(E=="style"||E=="class"){F[E]+=" "+D.data.attributes[E]}else{F[E]=D.data.attributes[E]}}}G+="<a";for(var E in F){if(!F.hasOwnProperty(E)){continue}G+=" "+E+'="'+F[E]+'" '}G+=">";if(D.data.icon){G+="<ins "+(D.data.icon.indexOf("/")==-1?" class='"+D.data.icon+"' ":" style='background-image:url(\""+D.data.icon+"\");' ")+">&nbsp;</ins>"
}else{G+="<ins>&nbsp;</ins>"}G+=((typeof D.data.title).toLowerCase()!="undefined"?D.data.title:D.data)+"</a>"}if(D.children&&D.children.length){G+="<ul>";for(var E=0;E<D.children.length;E++){G+=this.parse(D.children[E],J,B)}G+="</ul>"}G+="</li>";if(H){H.call(null,G)}return G},load:function(D,B,C,E){if(C["static"]){E.call(null,C["static"])
}else{A.ajax({type:C.method,url:C.url,data:D,dataType:"json",success:function(F,G){E.call(null,F)},error:function(G,H,F){E.call(null,false);B.error(F+" "+H)}})}}}}})})(jQuery);
