function lplogincheck(F,D,A,C){yubikey_cleardata();sesame_cleardata();grid_cleardata();multifactor_cleardata();loginoffline(true,"logincheck");var B="method=cr&version="+lpversion;if(D){B+="&sessionid="+LP.en(D)}if(A){B+="&wxusername="+LP.en(A)}if(C){B+="&wxhash="+LP.en(C)}var E=lpGetPref("logoffWhenCloseBrowser",0)==1&&lpGetPref("logoffWhenCloseBrowserVal",0)==0?"1":"0";
B+="&sessonly="+en(E);B+="&uuid="+en(getuuid());sesame_setdata("logincheckpostdata",B);lpMakeRequest(base_url+"login_check.php",B,lpLoginCheckResponse,lpLoginCheckError,F)}function LP_do_login(G,A,H,F,C,B){if(!C){var I=opendb();createSavedLoginsTable(I);if(I){I.transaction(function(J){var M=F?A:"";savedp_protected=protect_data(M,false,G);
if(H){var K=savedp_protected!=M?1:0;J.executeSql("REPLACE INTO LastPassSavedLogins2 (username, password, last_login, protected) VALUES(?, ?, ?, ?)",[G,savedp_protected,new Date().getTime(),K],function(N,O){},function(N,O){console.log(O)})}else{J.executeSql("DELETE FROM LastPassSavedLogins2 WHERE username=?",[G])
}})}lpPutGblPref("rememberemail",H?1:0);lpPutGblPref("rememberpassword",F?1:0);lpPutGblPref("showvault",B?1:0);lpWriteAllPrefs()}yubikey_cleardata();sesame_cleardata();grid_cleardata();if(!C){multifactor_cleardata()}G=fix_username(G);g_local_hash=make_lp_hash(G,A);g_local_key=make_lp_key(G,A);g_username=G;
g_username_hash=SHA256(g_username);if(!lploggedinoffline){loginoffline(true,"pluginlogin")}var E="xml=2&username="+en(G)+"&method=cr&hash="+en(g_local_hash)+"&version="+lpversion;E+="&encrypted_username="+en(lpenc(g_username));E+="&uuid="+en(getuuid());var D=lpGetPref("logoffWhenCloseBrowser",0)==1&&lpGetPref("logoffWhenCloseBrowserVal",0)==0?"1":"0";
E+="&sessonly="+en(D);sesame_cleardata();sesame_setdata("postdata",E);sesame_setdata("from","login");yubikey_cleardata();yubikey_setdata("postdata",E);yubikey_setdata("from","login");grid_cleardata();grid_setdata("postdata",E);grid_setdata("from","login");if(!C){multifactor_cleardata()}multifactor_setdata("postdata",E);
multifactor_setdata("from","login");E+="&otp=";E+="&sesameotp=";E+="&multifactorresponse=";GetOTPHash(E)}function loginoffline(C,B){if(g_local_key==null||g_username==null||g_username_hash==null){if(B=="frompipes"){return}var A=opendb();createSavedLoginsTable(A);if(A){A.transaction(function(D){D.executeSql("SELECT * FROM LastPassSavedLogins2 order by last_login desc",[],function(E,F){var H="";
var G="";if(F.rows.length>0){H=F.rows.item(0)["username"];G=F.rows.item(0)["password"];if(F.rows.item(0)["protected"]){G=unprotect_data(G)}}if(H.length>0&&G.length>0){g_username=H.toLowerCase().replace(/\s*/g,"");g_username_hash=SHA256(H);g_local_hash=make_lp_hash(g_username,G);g_local_key=make_lp_key(g_username,G);
loginoffline1(C,B);return}else{if(LPISLOC){A.transaction(function(I){I.executeSql("SELECT prefvalue FROM LastPassPreferences where username_hash=? and prefname=?",["","openloginstart"],function(J,K){if(LPISUPEK||(K.rows.length==1&&K.rows.item(0)["prefvalue"])){if(lpGetPref("openloginstart",LPISUPEK?1:0)==1){g_reprompt_callback=null;
open_login()}}},function(J,K){console.log(K)})})}}lpdbg("login","Trying to log in offline1: skipping because we dont have the user's key");return},function(E,F){lpdbg("login","Trying to log in offline2: skipping because we dont have the user's key");return})})}}else{loginoffline1(C,B)}}function read_key_from_file(){var A="";
if(have_nplastpass()&&typeof(g_nplastpass.read_file)=="function"){A=g_nplastpass.read_file(db_prepend(g_username_hash+"_lpall.slps"));if(typeof(A)!="string"){A=""}else{A=unprotect_data(A,true)}}return A}function read_accts_from_file(){var A="";if(have_nplastpass()&&typeof(g_nplastpass.read_file)=="function"){A=g_nplastpass.read_file(db_prepend(g_username_hash+"_lps.act.sxml"));
if(typeof(A)!="string"){A=""}else{A=unprotect_data(A,true);A=lpdec(A)}}return A}function loginoffline1(D,C,A){if(D){if(g_loggedinoffline){return}var B=opendb();createDataTable(B);if(B){B.transaction(function(E){var I=function(J,M){if(M.rows.length!=2){if(LPISLOC){if(A||g_username==""||AES.hex2bin(SHA256(g_username+""))==g_local_key){lpshowError("LoginError",false,true)
}else{g_pwdeckey=g_local_key;lpWriteKeyFile();g_local_accts_version=0;if(LPISUPEK){g_prompts.login_site_prompt=true;g_prompts.edit_site_prompt=true;g_prompts.edit_sn_prompt=true;g_prompts.view_pw_prompt=true;g_prompts.view_ff_prompt=true;g_prompts.switch_identity_prompt=true;g_prompts.switch_f_prompt=true;
g_prompts.multifactor_reprompt=true}rewritelocalfile();loginoffline1(D,C,true)}}lpdbg("login","Trying to log in offline : offline before online failed : could not read keyfile or accts");return}else{var N=(M.rows.item(0)["type"]=="key"?0:1);var Q=M.rows.item(N)["data"];var K=false;var O=Q.split("\n");
if(O.length==2){var P=AES.Decrypt({pass:g_local_key,data:O[1],b64:true,mode:"ecb",bits:256},true);if(P=="lastpass rocks"){K=true}}if(!K){if(LPISLOC){lpshowError("LoginError",false,true)}lpdbg("login","Trying to log in offline: skipping because we have an incorrect user's key");return}N=(M.rows.item(0)["type"]=="accts"?0:1);
Q=M.rows.item(N)["data"];Q=Q.substring(0,200);if(Q.indexOf("type=sesameoffline\ndata=")>=0||Q.indexOf("type=yubikeyoffline\ndata=")>=0||Q.indexOf("type=trueapioffline\ndata=")>=0){lpdbg("login","Data is encoded with multifactor key, bailing on loginoffline");return}offlineloginsuccessful(C,true);lpdbg("login","Trying to log in offline : offline before online successful")
}};var F=function(J,K){lpdbg("login","Trying to log in offline3: skipping because we dont have the user's key");return};if(LPISLOC){var G=read_key_from_file();var H=read_accts_from_file();if(G!=""||H!=""){I(E,{rows:{length:2,item:function(J){if(J==0){return{type:"key",data:G}}else{return{type:"accts",data:H}
}}}})}else{I(E,{rows:{length:0}})}}else{E.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND (type=? OR type=?)",[db_prepend(g_username_hash),"key","accts"],I,F)}})}return}if(g_loggedinoffline){return}var B=opendb();createDataTable(B);if(B){B.transaction(function(E){var H=function(I,K){if(K.rows.length!=2){lpdbg("login","Trying to log in offline : offline before online failed : could not read keyfile or accts");
return}else{var M=(K.rows.item(0)["type"]=="key"?0:1);var P=K.rows.item(M)["data"];var J=false;var N=P.split("\n");if(N.length==2){var O=AES.Decrypt({pass:g_local_key,data:N[1],b64:true,mode:"ecb",bits:256},true);if(O=="lastpass rocks"){J=true}}if(!J){lpdbg("login","Trying to log in offline: skipping because we have an incorrect user's key");
return}M=(K.rows.item(0)["type"]=="accts"?0:1);P=K.rows.item(M)["data"];P=P.substring(0,200);if(P.indexOf("type=sesameoffline\ndata=")>=0){lpdbg("sesame","Logging in offline and existing file is protected by sesameoffline => asking user for offline password");sesame_setdata("offline",1);sesame_getotp(null);
return}else{if(P.indexOf("type=trueapioffline\ndata=")>=0){lpdbg("multifactor","Logging in offline and existing file is protected by trueapioffline => asking user for offline password");multifactor_setdata("offline",1);multifactor_setdata("type","trueapi");multifactor_getresponse(g_username);return}else{if(P.indexOf("type=yubikeyoffline\ndata=")>=0){yubikey_setdata("offline",1);
yubikey_getotp(null);return}}}offlineloginsuccessful(C,false);lpdbg("login","Trying to log in offline : offline after online successful")}};if(LPISLOC){var F=read_key_from_file();var G=read_accts_from_file();if(F!=""||G!=""){H(E,{rows:{length:2,item:function(I){if(I==0){return{type:"key",data:F}}else{return{type:"accts",data:G}
}}}})}else{H(E,{rows:{length:0}})}}else{E.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND (type=? OR type=?)",[db_prepend(g_username_hash),"key","accts"],H)}})}}function offlineloginsuccessful(D,C){if(LPISLOC&&D=="pluginlogin"){if(lpGetPref("showvault",0)==1){openvault(1)}}console.log("offlineloginsuccessful!");
if(!g_loggedinonline){g_loggedinoffline=true}lploggedin=true;lpReadAllPrefs();loggedIn(D=="pluginlogin");if(D!="offline"){get_accts_local(true)}if(g_notifytimerid){clearTimeout(g_notifytimerid);g_notifytimerid=null}var B=C?30000:0;g_notifytimerid=setTimeout('notifyoffline("'+D+'");',B);if(g_retryonlinetimerid){clearTimeout(g_retryonlinetimerid);
g_retryonlinetimerid=null}var A=30000;g_retryonlinetimerid=setTimeout("retryonlinelogin("+A+");",A)}function notifyoffline(A){if(!lploggedin||!g_loggedinoffline){return}lpdbg("login","Trying to log in offline : notify user that they are logged in offline");if(!LPISLOC){lpshowError("LoggedInOffline")}}function retryonlinelogin(B){if(!lploggedin||!g_loggedinoffline){return
}var C=(B/(60*1000));lpdbg("login","We're still logged in offline => retrying to login online.  retryinterval="+C+" minutes");lplogincheck("retryonline");var A=2*B;if(A>20*60000){A=20*60000}setTimeout("retryonlinelogin("+A+");",A)}function lpTurnOffIcon(){lploggedin=false;drawIconAtRotation(0)}function lpLoginCheckResponse(B,G,F){try{if(B&&B.readyState==4&&typeof(G)=="function"&&(B.status!=200||B.responseXML==null||B.responseXML.documentElement==null)){G();
return}if(B.readyState==4&&B.status==200&&B.responseXML!=null&&B.responseXML.documentElement!=null){var D=B.responseXML.documentElement;var A=D.getElementsByTagName("ok");if(A.length>0){var E=A[0].getAttribute("lpusername");g_username=E;g_username_hash=SHA256(g_username);if(F!="retryonline"&&F!=true){lpReadAllPrefs(function(){lpLoginCheckResponseStep2(B,E,F)
});return}}}lpLoginResponse_win(B,F,true)}catch(C){L("loginresponse: "+C)}}function lpLoginCheckResponseStep2(A,D,R){try{var K=A.responseXML.documentElement;var J=K.getElementsByTagName("ok");var G=(J[0].getAttribute("sesamepassword")!=null&&J[0].getAttribute("sesamepassword")!="")?true:false;var F=(J[0].getAttribute("yubikeyhash")!=null&&J[0].getAttribute("yubikeyhash")!="")?true:false;
var H=(J[0].getAttribute("gridenabled")!=null&&J[0].getAttribute("gridenabled")!="")?true:false;var Q=(J[0].getAttribute("multifactorenabled")!=null&&J[0].getAttribute("multifactorenabled")!="")?true:false;var M=(J[0].getAttribute("sesameotpok")!=null&&J[0].getAttribute("sesameotpok")!="")?true:false;
var E=(J[0].getAttribute("yubikeyotpok")!=null&&J[0].getAttribute("yubikeyotpok")!="")?true:false;var O=(J[0].getAttribute("gridresponseok")!=null&&J[0].getAttribute("gridresponseok")!="")?true:false;var B=(J[0].getAttribute("multifactorresponseok")!=null&&J[0].getAttribute("multifactorresponseok")!="")?true:false;
var C=(R=="websitelogin"||R=="webrootwebsitelogin"||R=="websiterefresh"||R=="websiterefreshrsa"||R=="2ndfactorok"||R=="frompipes")?true:false;if(!C&&(g_local_key==null||g_local_key=="")&&lpGetPref("logoffWhenCloseBrowser",0)==1){var P=lpGetPref("lastpollcheck",0);var N=lpGetPref("logoffWhenCloseBrowserVal",0);
var I=lp_get_gmt_timestamp()*1000-P;console.log(P+" "+N+" "+I);if(I>=N*60000){loggedOut();return}}if(G){if(M){R="2ndfactorok";lpdbg("login","LoginCheck : sesame reprompt-rerequest succeeded!")}else{lpdbg("login","LoginCheck : Asking for sesame OTP and reissuing request to login_check.php");lpdbg("sesame","LOGIN CHECK RESPONSE: sesameenabled => Asking user for OTP and then reissuing the login_check request");
sesame_setdata("fromwebsite",R);sesame_getotp(D);return}}if(F){if(E){R="2ndfactorok";lpdbg("login","LoginCheck : yubikey reprompt-rerequest succeeded!")}else{lpdbg("login","LoginCheck : Asking for yubikey OTP and reissuing request to login_check.php");lpdbg("yubikey","LOGIN CHECK RESPONSE: yubikeyenabled => Asking user for OTP and then reissuing the login_check request");
yubikey_setdata("fromwebsite",R);yubikey_getotp(D);return}}if(H){if(O){R="2ndfactorok";lpdbg("login","LoginCheck : grid reprompt-rerequest succeeded!")}else{lpdbg("login","LoginCheck : Asking for grid response and reissuing request to login_check.php");lpdbg("yubikey","LOGIN CHECK RESPONSE: gridenabled => Asking user for coordinates and then reissuing the login_check request");
grid_setdata("fromwebsite",R);grid_setdata("wxsessid",J[0].getAttribute("wxsessid"));grid_getvalues(D,J[0].getAttribute("challenge"));return}}if(Q){if(B){R="2ndfactorok";lpdbg("login","LoginCheck : multifactor reprompt-rerequest succeeded!")}else{lpdbg("login","LoginCheck : Asking for multifactor response and reissuing request to login_check.php");
lpdbg("yubikey","LOGIN CHECK RESPONSE: multifactorenabled => Asking user for coordinates and then reissuing the login_check request");multifactor_setdata("fromwebsite",R);multifactor_setdata("wxsessid",J[0].getAttribute("wxsessid"));multifactor_setdata("type",J[0].getAttribute("type"));multifactor_getresponse(D,J[0].getAttribute("challenge"));
return}}lpLoginResponse_win(A,R,true)}catch(S){console.log(S)}}function lpLoginResponse(A,D,C){try{if(A&&A.readyState==4&&typeof(D)=="function"&&(A.status!=200||A.responseXML==null||A.responseXML.documentElement==null)){D();return}lpLoginResponse_win(A,C,false);if(lpGetPref("showvault",0)==1){openvault(1)
}}catch(B){L("loginresponse: "+B)}}function lp_login_from_saved(){try{var A=opendb();createSavedLoginsTable(A);if(A){A.transaction(function(C){C.executeSql("SELECT * FROM LastPassSavedLogins2 order by last_login desc",[],function(D,E){if(E.rows.length>0){var G=E.rows.item(0)["password"];if(E.rows.item(0)["protected"]){G=unprotect_data(G)
}if(G!=""){console.log("Logging in from saved");var F=E.rows.item(0)["username"];LP_do_login(F,G,true,true);return}}A.transaction(function(H){H.executeSql("SELECT prefvalue FROM LastPassPreferences where username_hash=? and prefname=?",["","openloginstart"],function(I,J){if(LPISUPEK||(J.rows.length==1&&J.rows.item(0)["prefvalue"])){if(lpGetPref("openloginstart",LPISUPEK?1:0)==1){g_reprompt_callback=null;
open_login()}}},function(I,J){console.log(J)})})},function(D,E){console.log(E)})})}}catch(B){console.log(B)}}function lpLoginCommon(A){g_loggedinonline=true;g_loggedinoffline=false;if(g_notifytimerid){clearTimeout(g_notifytimerid);g_notifytimerid=null}if(g_retryonlinetimerid){clearTimeout(g_retryonlinetimerid);
g_retryonlinetimerid=null}}var lploginerrorhandlercalled=0;function lpLoginError(){var A=(new Date()).getTime();if((A-lploginerrorhandlercalled)<1000){return}lploginerrorhandlercalled=A;lpdbg("login","Login via login.php failed => try logging in offline using saved credentials -- if not already logged in offline --");
loginoffline(false,"ErrorHandler")}function lpLoginCheckError(){if(!g_loggedinoffline){lpshowError("ErrorLoginMsg");loggedOut();lp_login_from_saved()}}function lpLoginResponse_win(I,F,B){if(!I){return}if(I.readyState==4&&I.status==200&&I.responseXML!=null&&I.responseXML.documentElement!=null){var D=I.responseXML.documentElement;
var J=D.getElementsByTagName("ok");var A=true;var G=false;if(J.length>0){g_pwdeckey=AES.hex2bin(SHA256(J[0].getAttribute("pwdeckey")));g_username=J[0].getAttribute("lpusername");g_username_hash=SHA256(g_username);g_uid=lpuid=J[0].getAttribute("uid");g_logoff_other_ses=(J[0].getAttribute("logoff_other_ses")=="1"?true:false);
countryfromip=J[0].getAttribute("country");g_lastpollcheck=g_lastpoll=(new Date()).getTime();var E=lpGetPref("singlefactortype","");if(J[0].getAttribute("multifactor_singlefactor")=="1"){if(E==""){if(multifactor_getdata("type")=="trueapi"){if(have_nplastpass()&&typeof(g_nplastpass.trueapi_default_login_exists)=="function"){if(g_nplastpass.trueapi_default_login_exists(g_username)){lpPutGblPref("singlefactortype",multifactor_getdata("type"));
lpPutGblPref("openloginstart",1);lpWriteAllPrefs()}}}else{if(J[0].getAttribute("singlefactortype")=="vtapi"){if(have_nplastpass()&&typeof(g_nplastpass.lpvt_has_data)=="function"){if(g_nplastpass.lpvt_has_data()){lpPutGblPref("singlefactortype",J[0].getAttribute("singlefactortype"));lpPutGblPref("openloginstart",1);
lpWriteAllPrefs()}}}}}}else{if(E!=""){disable_single_factor()}}sesame_setdata("password_offline",J[0].getAttribute("sesamepassword"));yubikey_setdata("password_offline",J[0].getAttribute("yubikeyhash"));lpLoginResponse_win1_5(I,F,B);lpLoginCommon(B);lpdisableoffline=J[0].getAttribute("disableoffline")==1?1:0;
if(lpdisableoffline){lpdbg("disableoffline","enabled => clearing sensitive files");clearCache(true,false,false)}}else{var H=D.getElementsByTagName("error");if(H.length>0){if(H[0].hasAttribute("invalidsession")){window.open(base_url+"invalidsession.php");lpshowError(H.length>0&&H[0].getAttribute("message")?H[0].getAttribute("message"):"LoginError",false,true);
clearCache(true,false,false);loggedOut();return}else{G=parseInt(H[0].getAttribute("silent"))==1}if(I.responseText.indexOf("sesameotprequired")>0){lpdbg("sesame","LOGIN RESPONSE: sesameenabled => Asking user for OTP and then reissuing the login request");clearCache(true,false,false);sesame_setdata("fromwebsite",F);
sesame_getotp(g_username);return}if(I.responseText.indexOf("sesameotpfailed")>0){lpshowError(H.length>0&&H[0].getAttribute("message")?H[0].getAttribute("message"):"LoginError",false,true);clearCache(true,false,false);loggedOut();return}if(I.responseText.indexOf("otprequired")>0){lpdbg("yubikey","LOGIN RESPONSE: yubikeyenabled => Asking user for OTP and then reissuing the login request");
clearCache(true,false,false);yubikey_setdata("fromwebsite",F);yubikey_getotp(g_username);return}if(I.responseText.indexOf("otpfailed")>0){lpshowError(H.length>0&&H[0].getAttribute("message")?H[0].getAttribute("message"):"LoginError",false,true);clearCache(true,false,false);loggedOut();return}if(I.responseText.indexOf("gridresponserequired")>0){lpdbg("grid","LOGIN RESPONSE: gridenabled => Asking user for grid response and then reissuing the login request");
clearCache(true,false,false);grid_setdata("fromwebsite",F);grid_setdata("wxsessid",H[0].getAttribute("wxsessid"));grid_getvalues(g_username,H[0].getAttribute("challenge"));return}if(I.responseText.indexOf("gridresponsefailed")>0){lpshowError(H.length>0&&H[0].getAttribute("message")?H[0].getAttribute("message"):"LoginError",false,true);
clearCache(true,false,false);loggedOut();return}if(I.responseText.indexOf("multifactorresponserequired")>0){lpdbg("multifactor","LOGIN RESPONSE: multifactorenabled => Asking user for multifactor response and then reissuing the login request");clearCache(true,false,false);multifactor_setdata("fromwebsite",F);
multifactor_setdata("wxsessid",H[0].getAttribute("wxsessid"));multifactor_setdata("type",H[0].getAttribute("type"));multifactor_getresponse(g_username,H[0].getAttribute("challenge"));return}if(I.responseText.indexOf("multifactorresponsefailed")>0){lpshowError(H.length>0&&H[0].getAttribute("message")?H[0].getAttribute("message"):"LoginError",false,true,false,get_multifactor_disable_url(g_username,multifactor_getdata("type")));
clearCache(true,false,false);loggedOut();return}}loggedOut(G);if(!G){if(I.responseText.indexOf("blacklist")>0){clearCache(true,false,false);lpshowError(H.length>0&&H[0].getAttribute("message")?H[0].getAttribute("message"):"Blacklist",false,true)}else{var C=H.length>0&&H[0].getAttribute("cause")&&H[0].getAttribute("cause")=="unknownemail";
lpshowError(H.length>0&&H[0].getAttribute("message")?H[0].getAttribute("message"):"LoginError",false,true,C)}}else{lp_login_from_saved()}}}else{loggedOut();lpshowError("ErrorLoginMsg")}}function disable_single_factor(){var A=lpGetPref("singlefactortype","");if(A=="trueapi"){if(have_nplastpass()&&typeof(g_nplastpass.trueapi_delete_default_login)=="function"){g_nplastpass.trueapi_delete_default_login()
}}lpPutGblPref("singlefactortype","");lpWriteAllPrefs()}function lpLoginResponse_win1_5(C,F,A){var D=C.responseXML.documentElement;var B=D.getElementsByTagName("ok");if(g_local_key==null||g_local_key==""){var E=(F=="websitelogin"||F=="webrootwebsitelogin"||F=="websiterefresh"||F=="websiterefreshrsa"||F=="2ndfactorok"||F=="frompipes")?true:false;
if(!E&&lpGetPref("logoffWhenCloseBrowser",0)==1){lpReadAllPrefs(function(){lpLoginResponse_win1_75(C,F,A)});return}lpReadKeyFile(C,F,false,A)}else{lpWriteKeyFile();lpReadAllPrefs(function(){lpLoginResponse_win2(C,F,A)})}}function lpLoginResponse_win1_75(E,F,B){var C=lpGetPref("lastpollcheck",0);var A=lpGetPref("logoffWhenCloseBrowserVal",0);
var D=lp_get_gmt_timestamp()*1000-C;if(D>=A*60000){loggedOut();return}lpReadKeyFile(E,F,false,B)}function lpLoginResponse_win2(D,F,A){var E=D.responseXML.documentElement;var B=E.getElementsByTagName("ok");lp_phpsessid=B[0].getAttribute("sessionid");if(B[0].getAttribute("privatekeyenchash")==""){var C=new RSAKey();
generate_key(C,upload_rsa_keys)}else{readrsaprivatekeyhexfromdb(true,true,B[0].getAttribute("privatekeyenchash"))}if(!A||(typeof(F)=="boolean"&&F)){lpnp_notify("internal_logincheck_ack",{data0:lp_phpsessid,data1:g_username,data2:g_identity})}var E=D.responseXML.documentElement;var B=E.getElementsByTagName("ok");
if(lpGetPref("storeLostOTP",1)==1&&B[0].hasAttribute("lostpwotpresult")&&B[0].getAttribute("lostpwotpresult")!="ok"){DeleteOTP();MakeOTP()}loggedIn();g_local_accts_version=-1;g_server_accts_version=parseInt(B[0].getAttribute("accts_version"));g_loglogins=parseInt(B[0].getAttribute("loglogins"))==1;iconsversion=parseInt(B[0].getAttribute("iconsversion"));
get_accts_local();checkIconsVersion(iconsversion);lpretryrequests()}var adminoverride="";var lplastgetaccounts=0;function get_accts(){var B=(new Date()).getTime();if((B-lplastgetaccounts)<1000){return}lplastgetaccounts=B;var A=base_url+"getaccts.php?mobile=1&b64=1";if(adminoverride!=""){A+="&adminoverride="+en(adminoverride)
}lpMakeRequest(A,"",lpAcctsResponse,lpAcctsError)}function get_accts_local(A){lpReadAcctsData(A)}function lpAcctsResponse(J){if(J&&J.readyState==4){var N=atob(J.responseText);var I=new Array(),F=new Array(),G=new Array(),B=new Array(),M=new Array(),H=new Array(),C=new Array(),E=new Array(),A=new Array(),D=new Array(),K=new Array();
lp_premium_exp=0;parsemobile(N,N.length,100,0,postacctsload,I,F,G,B,M,H,C,true,false,null,E,null,A,D,K);g_premium_exp=lp_premium_exp}}function rewritelocalfile(D,C){var B=flattendata(g_local_accts_version,g_sites,g_securenotes,g_prompts,g_formfills,g_identities,g_equivalentdomains,g_neverurls,g_premium_exp,lpenc(g_username),g_pendings,g_shareeautopushes,lpmaxid,g_urlrules);
B=btoa(B);if(LPISLOC){B="LPB64"+B}B=prependOTPAndEncrypt(B);lpSaveData(B,"accts");if(LPISLOC){B=lpenc(B);B=protect_data(B,true);if(have_nplastpass()&&typeof(g_nplastpass.write_file)=="function"){var A="";if(D){A="_"+new Date().toString().replace(" ","_")}g_nplastpass.write_file(db_prepend(g_username_hash+A+"_lps.act.sxml"),B)
}if(!D&&!C){lpnp_notify("refresh_local",{data0:g_username_hash})}}}function prependOTPAndEncrypt(C){var A=null;var B="";if(sesame_getdata("password_offline")&&sesame_getdata("password_offline")!=""){lpdbg("sesame","encrypting accounts file before writing");A=sesame_getdata("password_offline");B="type=sesameoffline\ndata="
}else{if(multifactor_getdata("password_offline")&&multifactor_getdata("password_offline")!=""){lpdbg("multifactor","encrypting accounts file before writing");A=multifactor_getdata("password_offline");B="type=trueapioffline\ndata="}else{if(yubikey_getdata("password_offline")&&yubikey_getdata("password_offline")!=""){lpdbg("yubikey","encrypting accounts file before writing");
A=yubikey_getdata("password_offline");B="type=yubikeyoffline\ndata="}}}if(A){C=enc(C,hex2bin(A));if(!C||C==""){lpdbg("error","Failed to encrypt data in save_accounts_fileraw");return false}C=B+C}return C}function postacctsload(P,X,M,C,F,V,R,K,A,O,D,E,H,Q,G){if(!lploggedin){return}if(!K&&(!O||(O&&P.length==0))){console.log("ERROR: Could not parse accts data!!!");
if(!gPulledInvalidAccts){gPulledInvalidAccts=true;get_accts()}else{lpshowError("ErrorGetAcctsMsg")}return}if(P.length>0&&typeof(D)!="undefined"&&adminoverride==""){if(D!=""&&lpenc(g_username)!=D){lpReportError("Encrypted username check failed: "+lpenc(g_username)+" vs "+D+" for "+g_username+" local "+O,null);
lpshowError("An error has been encountered while loading your sites. Please relogin.");clearAllData();loggedOut();return false}}lpmaxid=Q.maxid;if(!O){g_local_accts_version=get_version(A);var Z=btoa(A);Z=prependOTPAndEncrypt(Z);lpSaveData(Z,"accts")}var N=new Array();g_tlds=new Array();for(var S=0;S<P.length;
S++){P[S]["url"]=AES.hex2bin(P[S]["url"]);P[S]["tld"]=lp_gettld_url(P[S]["url"]);P[S]["unencryptedUsername"]=lpmdec(P[S]["username"],true);if(typeof(g_tlds[P[S]["tld"]])=="undefined"){g_tlds[P[S]["tld"]]=new Array()}g_tlds[P[S]["tld"]][P[S]["aid"]]=true;N[P[S]["aid"]]=P[S]}var Y=new Array();for(var S=0;
S<X.length;S++){X[S]["url"]=AES.hex2bin(X[S]["url"]);Y[X[S]["aid"]]=X[S]}g_sites=N;g_securenotes=Y;g_prompts=M;g_formfills=C;g_identities=F;g_equivalentdomains=V;g_urlrules=G;g_neverurls=R;g_pendings=E;g_shareeautopushes=H;for(var S=0;S<g_formfills.length;S++){g_formfills[S].decprofilename=lpmdec(g_formfills[S].profilename,true)
}g_formfills.sort(function(d,c){return d.decprofilename.toLowerCase()<c.decprofilename.toLowerCase()?-1:1});var B=false;for(var S=0;S<g_identities.length;S++){g_identities[S].deciname=lpdec(g_identities[S].iname);if(g_identities[S].iid==g_identity){B=true}}g_identities.sort(function(d,c){return d.deciname.toLowerCase()<c.deciname.toLowerCase()?-1:1
});if(!B&&g_identity!=""){identityFilter="";switch_identity("",true);clearCache(true,false,false);setTimeout("loggedOut();",500);alert(gs("Your selected Identity no longer exists. Defaulting to 'All' and logging off."));return false}rsa_acceptpendingshares();rsa_acceptshareeautopushes();var T="";if((g_is_win||(g_is_mac&&LPISLOC))&&have_nplastpass()&&typeof(g_nplastpass.read_file)=="function"){T=g_nplastpass.read_file(db_prepend(g_username_hash+"_lt.cac"))
}else{T=localStorage.getItem(db_prepend(g_username_hash+"_lt.cac"))}T=(T==null?"":T);var U=T.split("\n");for(var S=0;S<U.length;S++){var W=U[S].split(" ");if(W.length==2&&W[0]!=""&&W[1]!=""){var I=W[0];var J=W[1];if(g_sites[I]){if(J>g_sites[I].last_touch){g_sites[I].last_touch=J}}}}console.warn("num sites: "+P.length+" num sn: "+X.length+" num ff: "+g_formfills.length+" num identities: "+g_identities.length+" pendings: "+g_pendings.length);
recheckall()}function lpAcctsError(){L("Error xhr_accts")}function checkIconsVersion(B){var A=opendb();createDataTable(A);if(A){A.transaction(function(C){C.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"icons"],function(D,E){var F=true;var G=null;
var I=lpGetPref("icons",-1);if(E.rows.length>0){var H=lpGetPref("icons",-1);if(H==B){F=false;G=E.rows.item(0)["data"]}}if(G==null||F){downloadIcons()}else{processIcons(G)}},function(D,E){console.log(E)})})}else{downloadIcons()}}function processIcons(F){if(!F){return}while(true){if(F.length<10){break}var D=new RegExp("lp([^:]+):([^:]+):");
var A=D.exec(F);if(!A||A.length!=3){break}var G=A[1];var C=A[2];var B=parseInt(C);if(isNaN(B)){break}var E="lp"+G+":"+C+":";g_icons[G]=lpsubstring(F,E.length,E.length+B);g_icons_length++;F=F.substring(E.length+B)}}function lpsubstring(E,F,D){var C="";var A;var B=D-F;for(A=0;A<B;++A){C+=E[A+F]}return C
}function downloadIcons(){lpMakeRequest(base_url+"geticon.php","versionchrome=1&username="+en(g_username),lpIconResponse,null)}function lpIconResponse(B){if(B.readyState==4&&B.status==200&&B.responseText){if(B.responsetext=="latest"||B.responsetext=="nodata"){return}var E=B.responseText.split("\n");var A=E[0];
var D=A.split("=")[1];var C=E[1];lpPutUserPref("icons",D);lpWriteAllPrefs();lpSaveData(C,"icons");processIcons(C)}}function loglogin(B){var A=lp_get_gmt_timestamp();if(typeof(g_sites[B])!="undefined"){if(parseFloat(A)<5+parseFloat(g_sites[B]["last_touch"])){return}g_sites[B]["last_touch"]=A;writenewts(B,A)
}else{if(typeof(g_securenotes[B])!="undefined"){if(A==g_securenotes[B]["last_touch"]){return}g_securenotes[B]["last_touch"]=lp_get_gmt_timestamp();rewritelocalfile()}}if(g_loglogins){lpMakeRequest(base_url+"loglogin.php?id="+en(B)+"&method=cr","",null,null)}}function writenewts(F,E){var B="";if((g_is_win||(g_is_mac&&LPISLOC))&&have_nplastpass()&&typeof(g_nplastpass.read_file)=="function"){B=g_nplastpass.read_file(db_prepend(g_username_hash+"_lt.cac"))
}else{B=localStorage.getItem(db_prepend(g_username_hash+"_lt.cac"))}B=(B==null?"":B);var D=B.split("\n");var A="";for(var C=0;C<D.length;C++){if(D[C].indexOf(F+" ")!=0&&D[C]!=""){A+=D[C]+"\n"}}A+=F+" "+E+"\n";if((g_is_win||(g_is_mac&&LPISLOC))&&have_nplastpass()&&typeof(g_nplastpass.write_file)=="function"){g_nplastpass.write_file(db_prepend(g_username_hash+"_lt.cac"),A)
}localStorage.setItem(db_prepend(g_username_hash+"_lt.cac"),A)}function logformfill(A){if(g_loglogins){lpMakeRequest(base_url+"logformfill.php?ffid="+en(A),"",null,null)}}function lpWriteKeyFile(){var B=AES.bin2hex(g_local_key);if(typeof(g_pwdeckey)!="undefined"&&g_pwdeckey!=null){var A=AES.Encrypt({pass:g_pwdeckey,data:B,b64:true,mode:"ecb",bits:256});
var C=AES.Encrypt({pass:g_local_key,data:"lastpass rocks",b64:true,mode:"ecb",bits:256});var D=A+"\n"+C;lpSaveData(D,"key");if((g_is_win||(g_is_mac&&LPISLOC))&&have_nplastpass()&&typeof(g_nplastpass.write_file)=="function"){D=protect_data(D,true);if(!lpdisableoffline){g_nplastpass.write_file(db_prepend(g_username_hash+"_lpall.slps"),D)
}}}}function lpReadKeyFile(D,E,C,A){var B=opendb();createDataTable(B);if(B){B.transaction(function(F){var I=function(J,K){if(K.rows.length>0){var P=K.rows.item(0)["data"];if(P){var N=P.split("\n");if(N.length==2){var M=null;if(D){M=AES.hex2bin(AES.Decrypt({pass:g_pwdeckey,data:N[0],b64:true,mode:"ecb",bits:256},true))
}else{M=g_local_key}var O=AES.Decrypt({pass:M,data:N[1],b64:true,mode:"ecb",bits:256},true);if(O=="lastpass rocks"){g_local_key=M;if(D){lpLoginResponse_win2(D,E,A);return}else{loggedIn();get_accts_local(true)}}}}}else{lp_login_from_saved()}if(D){loggedOut();if(!C){}}};var G=function(J,K){console.log(K)
};if(LPISLOC){var H=read_key_from_file();if(H!=""){I(F,{rows:{length:1,item:function(J){return{data:H}}}})}else{I(F,{rows:{length:0}})}}else{F.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"key"],I,G)}})}}function lpReadAcctsData(B){if(g_username==null||g_username==""){return
}var A=opendb();createDataTable(A);if(A){A.transaction(function(C){var F=function(N,K){if(K.rows.length>0){data=K.rows.item(0)["data"];if(data&&data!=""){if(B&&((!sesame_getdata("password_offline")||sesame_getdata("password_offline")=="")||(!yubikey_getdata("password_offline")||yubikey_getdata("password_offline")=="")||!multifactor_getdata("password_offline")||multifactor_getdata("password_offline")=="")){if(data.substring(0,30).indexOf("type=sesameoffline\ndata=")==0){sesame_setdata("offline","1");
sesame_getotp(g_username);return}if(data.substring(0,30).indexOf("type=trueapioffline\ndata=")==0){multifactor_setdata("offline","1");multifactor_setdata("type","trueapi");multifactor_getresponse(g_username);return}if(data.substring(0,30).indexOf("type=yubikeyoffline\ndata=")==0){yubikey_setdata("offline","1");
yubikey_getotp(g_username);return}}var J=null;if(sesame_getdata("password_offline")&&sesame_getdata("password_offline")!=""&&data.substring(0,30).indexOf("type=sesameoffline\ndata=")==0){lpdbg("sesame","decrypting accounts file after reading");data=data.substring(24);J=sesame_getdata("password_offline")
}else{if(multifactor_getdata("password_offline")&&multifactor_getdata("password_offline")!=""&&data.substring(0,30).indexOf("type=trueapioffline\ndata=")==0){lpdbg("multifactor","decrypting accounts file after reading");data=data.substring(25);J=multifactor_getdata("password_offline")}else{if(yubikey_getdata("password_offline")&&yubikey_getdata("password_offline")!=""&&data.substring(0,30).indexOf("type=yubikeyoffline\ndata=")==0){lpdbg("yubikey","decrypting accounts file after reading");
data=data.substring(25);J=yubikey_getdata("password_offline")}}}if(J){data=dec(data,hex2bin(J))}}if(LPISLOC&&data.length>=5&&data.substring(0,5)=="LPB64"){data=data.substring(5)}data=atob(data);g_local_accts_version=get_version(data);if(g_local_accts_version!=g_server_accts_version&&g_server_accts_version!=-1){console.log("local accts version is outdated. redownloading");
get_accts()}else{L("using cached accts data");var S=new Array(),Q=new Array(),R=new Array(),H=new Array(),U=new Array(),P=new Array(),I=new Array(),O=new Array(),G=new Array(),M=new Array(),T=new Array();lp_premium_exp=0;parsemobile(data,data.length,100,0,postacctsload,S,Q,R,H,U,P,I,true,true,null,O,G,M,T);
g_premium_exp=lp_premium_exp}}else{if(g_username_hash){get_accts()}}};var D=function(G,H){console.log(H)};if(LPISLOC){var E=read_accts_from_file();if(E!=""){F(C,{rows:{length:1,item:function(G){return{data:E}}}})}else{F(C,{rows:{length:0}})}}else{C.executeSql("SELECT * FROM LastPassData WHERE username_hash=? and type=?",[db_prepend(g_username_hash),"accts"],F,D)
}})}else{get_accts()}}function MakeOTP(){if(g_username==null||g_username.length==0){return}if(g_local_key==null||g_local_key.length==0){return}var D=fix_username(g_username);rng_seed_time();var H=new Array();var K=16;for(var E=0;E<K;E++){H[E]=0}rng_get_bytes(H);var G="";for(var E=0;E<K;E++){G+=String.fromCharCode(H[E])
}var F=enc(AES.bin2hex(G),g_local_key);var B=make_lp_key(g_username,G);var A=enc(AES.bin2hex(g_local_key),B);var C=SHA256(SHA256(D+G)+G);var J=AES.hex2bin(dec(A,B,1));if(g_local_key!=J){console.log("ERROR: Failed to decrypt newly encrypted key: dec_local_key:\n"+AES.bin2hex(J)+" != \n"+AES.bin2hex(g_local_key)+"\nlen: "+J.length+" vs "+g_local_key.length+"\nrand pw:"+AES.bin2hex(G)+"\ng_username:"+g_username+"\nrand key:"+AES.bin2hex(B)+"\nrand_encrypted_key:"+A);
return}var I="newkey=1&xml=1&hash="+LP.en(C);I+="&encrypted_otp="+LP.en(F);I+="&rand_encrypted_key="+LP.en(A);I+="&recovery=1";LP.lpMakeRequest(base_url+"otp.php",I,lpOTPUploadResponse,function(){},G)}function DeleteOTP(){DeleteFromDB("otp")}function DeleteFromDB(B){if(g_username==null||g_username==""){return
}if(LPISLOC&&(B=="key"||B=="accts")){return}var A=opendb();createDataTable(A);if(A){A.transaction(function(C){C.executeSql("DELETE FROM LastPassData WHERE username_hash=? and type=?",[db_prepend(g_username_hash),B],function(D,E){},function(D,E){console.log(E)})})}}function GetOTPHash(E,A,G,F){var C=opendb();
createDataTable(C);if(C){var D=G?SHA256(G):g_username_hash;var B=G?G:g_username;C.transaction(function(H){H.executeSql("SELECT * FROM LastPassData WHERE username_hash=? and type=?",[db_prepend(D),"otp"],function(I,J){var K="";if(J.rows.length>0){K=J.rows.item(0)["data"]}if(E){if(K!=""){K=AES.hex2bin(K);
lostotphash=SHA256(SHA256(fix_username(B)+K)+K)}else{lostotphash=""}if(lpGetPref("storeLostOTP",1)==1){E+="&lostpwotphash="+en(lostotphash)}sesame_setdata("postdata",E);yubikey_setdata("postdata",E);grid_setdata("postdata",E);multifactor_setdata("postdata",E);lpMakeRequest(base_url+"login.php",E,lpLoginResponse,lpLoginError)
}else{if(A){if(K==""){lostotphash="nouser"}else{lostotphash=K}sendCS(A,{cmd:"recover",otp:lostotphash},F)}}},function(I,J){console.log(J)})})}else{lpMakeRequest(base_url+"login.php",E,lpLoginResponse,lpLoginError)}}function lpOTPUploadResponse(D,B,C){if(lpdisableoffline){return}if(D.readyState==4&&D.status==200&&D.responseXML&&D.responseXML.documentElement){var A=opendb();
createDataTable(A);if(A){A.transaction(function(E){E.executeSql("REPLACE INTO LastPassData (username_hash, type, data) VALUES (?, ?, ?)",[db_prepend(g_username_hash),"otp",AES.bin2hex(C)],function(F,G){console.log("inserted")},function(F,G){console.log(G)})})}}}function savePassword(F,C,A,E){var B=gs("Generated Password for")+" "+lp_gettld_url(C);
var D="url="+en(AES.bin2hex(C))+"&password="+en(lpenc(F))+"&name="+en(lpenc(B));D+=get_identity_param();if(E){D+="&nofill=1"}lpMakeRequest(base_url+"save_gen_pw.php",D,lpPopulateGeneratedPassword,null,A)}function lpPopulateGeneratedPassword(J,E,A){if(J.readyState==4&&J.status==200&&J.responseXML&&J.responseXML.documentElement){var D=J.responseXML.documentElement;
var H=D.getElementsByTagName("error");if(H.length>0){var G=H[0].getAttribute("notloggedin");if(G&&G=="1"){loggedOut();return}}var K=D.getElementsByTagName("ok");if(K.length>0){var C=AES.hex2bin(K[0].getAttribute("url"));var M=atob(K[0].getAttribute("password"));sendCS(A,{cmd:"populategeneratedpassword",url:C,password:lpmdec(M,true),nofill:K[0].getAttribute("nofill")});
var I=createNewAcct();I.tld=lp_gettld_url(C);var B=gs("Generated Password for")+" "+I.tld;I.aid=K[0].getAttribute("aid");if(typeof(g_tlds[I.tld])=="undefined"){g_tlds[I.tld]=new Array()}g_tlds[I.tld][I.aid]=true;add_ident_aid(I.aid);I.url=C;I.name=B;I.password=M;I.genpw=1;g_sites[I.aid]=I;g_local_accts_version++;
rewritelocalfile();var F=K[0].getAttribute("accts_version");if(!compare_accounts_versions(F,g_local_accts_version)){get_accts()}refresh_windows()}}}function createNewAcct(){var A=new Array();A.aid="";A.name="";A.group="";A.url="";A.tld="";A.extra="";A.fav="0";A.sharedfromuid="";A.username="";A.unencryptedUsername="";
A.password="";A.pwprotect=0;A.genpw=0;A.sn=0;A.last_touch="";A.autologin=0;A.never_autofill=0;A.realm_data="";A.fiid="";A.custom_js="";A.submit_id="";A.captcha_id="";A.urid="0";A.basic_auth="0";A.method="";A.fields=new Array();return A}function addeditformfill(A,B){var D="";var C;for(C in A){D+=(D==""?"":"&")+C+"="+en(A[C])
}D+=get_identity_param();lpMakeRequest(base_url+"formfill.php",D,lpAddEditFormFillResponse,null,B)}function deleteformfill(A){for(var C=0;C<g_formfills.length;C++){if(g_formfills[C].ffid==A){g_formfills.splice(C,1);break}}g_local_accts_version++;rewritelocalfile();var B="deleteext=1&ffid="+LP.en(A);B+=get_identity_param();
lpMakeRequest(base_url+"formfill.php",B,lpDeleteFormFillResponse,null,A)}function lpAddEditFormFillResponse(P,H,A){if(P.readyState==4&&P.status==200&&P.responseXML&&P.responseXML.documentElement){var G=P.responseXML.documentElement;var O=G.getElementsByTagName("error");if(O.length>0){var M=O[0].getAttribute("notloggedin");
if(M&&M=="1"){loggedOut();return}}var R=G.getElementsByTagName("result");if(R.length>0){var D=R[0].getAttribute("msg");var N=R[0].getAttribute("ffid");var Q=R[0].getAttribute("cfids");var K=R[0].getAttribute("accts_version");var J;var C=[];var I=Q==""?[]:Q.split(",");var F=0;for(J=1;typeof(A["customfield"+J+"cfid"])!="undefined";
++J){var B={};B.cfid=A["customfield"+J+"cfid"]!=0?A["customfield"+J+"cfid"]:(F<I.length?I[F++]:0);B.text=A["customfield"+J+"text"];B.value=A["customfield"+J+"value"];B.alttext=A["customfield"+J+"alttext"];C.push(B)}var E=A.cmd;delete A.cmd;delete A.deleteext;for(J=1;;++J){if(typeof(A["customfield"+J+"cfid"])=="undefined"){break
}delete A["customfield"+J+"cfid"];delete A["customfield"+J+"text"];delete A["customfield"+J+"value"];delete A["customfield"+J+"alttext"]}A.custom_fields=C;if(E=="add"){A.ffid=N;add_ident_ffid(N);g_formfills.push(A)}else{for(J=0;J<g_formfills.length;++J){if(N==g_formfills[J].ffid){g_formfills[J]=A;break
}}}g_formfills.sort(function(T,S){return T.decprofilename.toLowerCase()<S.decprofilename.toLowerCase()?-1:1});g_local_accts_version++;rewritelocalfile();if(!compare_accounts_versions(K,g_local_accts_version)){get_accts()}refresh_windows()}}}function lpDeleteFormFillResponse(G,F,B){if(G.readyState==4&&G.status==200&&G.responseXML&&G.responseXML.documentElement){var H=G.responseXML.documentElement;
var D=H.getElementsByTagName("error");if(D.length>0){var C=D[0].getAttribute("notloggedin");if(C&&C=="1"){loggedOut();return}}var A=H.getElementsByTagName("result");if(A.length>0){var E=A[0].getAttribute("accts_version");if(!compare_accounts_versions(E,g_local_accts_version)){get_accts()}refresh_windows()
}}}function saveSiteFromSubmit(A,B){A+=get_identity_param();lpMakeRequest(base_url+"deliver_and_add.php",A,lpSaveSiteResponse,null,B)}function updateFieldsFromSubmit(A,B){A+=get_identity_param();lpMakeRequest(base_url+"gm_deliver.php",A,lpUpdateFieldsResponse,null,B)}function saveAllSite(A,B){A+=get_identity_param();
lpMakeRequest(base_url+"show.php",A,lpSaveSiteResponse,null,B)}function saveSite(A,B){A+=get_identity_param();lpMakeRequest(base_url+"show.php",A,lpSaveSiteResponse,null,B)}function lpSaveSiteResponse(K,D,J){if(K.readyState==4&&K.status==200&&K.responseXML&&K.responseXML.documentElement){var C=K.responseXML.documentElement;
var I=C.getElementsByTagName("error");if(I.length>0){var H=I[0].getAttribute("notloggedin");if(H&&H=="1"){loggedOut();return}}var M=C.getElementsByTagName("result");if(M.length>0){var B=M[0].getAttribute("msg");if(B=="accountreplaced"){g_local_accts_version++}if(J.aid=="0"){var A=M[0].getAttribute("aid");
var E=M[0].getAttribute("urid");J.aid=A;J.urid=E;if(J.fields){for(var F=0;F<J.fields.length;F++){if(!J.fields[F].otherfield&&J.fields[F].otherlogin!="1"){J.fields[F].urid=E}}}add_ident_aid(J.aid);if(J.sn){g_securenotes[J.aid]=J}else{if(typeof(g_tlds[J.tld])=="undefined"){g_tlds[J.tld]=new Array()}g_tlds[J.tld][J.aid]=true;
g_sites[J.aid]=J}for(var F in g_sites){if(g_sites[F].genpw&&g_sites[F].tld==J.tld&&g_sites[F].password==J.password){delete g_sites[F]}}g_local_accts_version++;rewritelocalfile()}var G=M[0].getAttribute("accts_version");if(!compare_accounts_versions(G,g_local_accts_version)){get_accts()}refresh_windows()
}}}function lpUpdateFieldsResponse(I,B,H){if(I.readyState==4&&I.status==200&&I.responseXML&&I.responseXML.documentElement){var A=I.responseXML.documentElement;var G=A.getElementsByTagName("error");if(G.length>0){var F=G[0].getAttribute("notloggedin");if(F&&F=="1"){loggedOut();return}}var J=A.getElementsByTagName("ok");
if(J.length>0){var E=J[0].getAttribute("accts_version");if(!compare_accounts_versions(E,g_local_accts_version)){get_accts()}else{var C=J[0].getAttribute("urid");H.urid=C;if(H.fields){for(var D=0;D<H.fields.length;D++){if(!H.fields[D].otherfield&&H.fields[D].otherlogin!="1"){H.fields[D].urid=C}}}}refresh_windows()
}}}function addNever(A){g_neverurls.neveraccounts.push(A);g_local_accts_version++;rewritelocalfile();var B="url="+en(bin2hex(A));lpMakeRequest(base_url+"add_never.php",B,null,null)}function deleteGroup(D,C,E){var A="";for(var B in g_sites){if(g_sites[B].group==D){A+=(A==""?"":",")+B}}for(var B in g_securenotes){if(g_securenotes[B].group==D){A+=(A==""?"":",")+B
}}return deleteAid(A,C,false,false,E,D)}function deleteAid(B,H,E,G,P,J){var I=B.split(",");var K="";for(var F=0;F<I.length;F++){var O=I[F];if(!check_ident_aid(O)){continue}var M=g_sites[O];var D=g_prompts.edit_site_prompt;if(!M){D=g_prompts.edit_sn_prompt;M=g_securenotes[O]}if(!M){continue}K+=(K==""?"":",")+O;
if(!E&&(M.pwprotect||D)){security_prompt(function(){deleteAid(B,H,true,G,P)});return false}}if(K==""){return false}var C=gs("Are you sure you would like to delete this site?");if(M.genpw){C=gs("Are you sure you would like to delete this generated password?")}else{if(M.sn){C=gs("Are you sure you would like to delete this secure note?")
}}C+=" ("+M.name+")";if(J){C=gs("Are you sure you would like to delete this group?")+" ("+J+")"}if(!G){if(H==null){if(!confirm(C)){return false}}else{if(!H.confirm(C)){return false}}}var A=K.split(",");for(var F=0;F<A.length;F++){var O=A[F];if(!M.sn){delete g_tlds[M.tld][O]}delete g_sites[O];delete g_securenotes[O]
}g_local_accts_version++;rewritelocalfile();var N="ajax=1&extjs=1&delete=1&aid="+en(K);N+=get_identity_param();lpMakeRequest(base_url+"show.php",N,lpDeleteResponse);if(P){P()}return true}function lpDeleteResponse(C){if(!C){return}if(C.readyState==4&&C.status==200&&C.responseXML!=null&&C.responseXML.documentElement!=null){var D=C.responseXML.documentElement;
var A=D.getElementsByTagName("result");if(A.length>0){var B=A[0].getAttribute("accts_version");if(!compare_accounts_versions(B,g_local_accts_version)){get_accts()}refresh_windows()}}}function editAid(B,C,F){if(!check_ident_aid(B)){return}var E=g_sites[B];var D=g_prompts.edit_site_prompt;if(!E){D=g_prompts.edit_sn_prompt;
E=g_securenotes[B]}if(!E){return}if(!F&&(E.pwprotect||D)){security_prompt(function(){editAid(B,C,true)});return}g_site_data=new Array();for(var A in E){g_site_data[A]=E[A]}chrome.tabs.create({url:getchromeurl("site.html")})}function saveFields(A,B){lpMakeRequest(base_url+"fields.php?"+A,B,lpSaveFieldsResponse,null)
}function lpSaveFieldsResponse(H,C){if(H.readyState==4&&H.status==200&&H.responseXML&&H.responseXML.documentElement){var B=H.responseXML.documentElement;var D=B.getElementsByTagName("response");if(D.length>0){var A=D[0].getAttribute("message");console.log("Save Fields failed: "+A)}var G=B.getElementsByTagName("error");
if(G.length>0){var F=G[0].getAttribute("notloggedin");if(F&&F=="1"){loggedOut();return}}var I=B.getElementsByTagName("result");if(I.length>0){var E=I[0].getAttribute("accts_version");if(!compare_accounts_versions(E,g_local_accts_version)){get_accts()}refresh_windows()}}}function poll_server(){if(lploggedin&&grid_getdata("active")==null){var E=(new Date()).getTime();
g_lastpollcheck=E;if(lpGetPref("logoffWhenCloseBrowser",0)==1&&lpGetPref("logoffWhenCloseBrowserVal",0)>0){lpPutUserPref("lastpollcheck",g_lastpollcheck);lpWriteAllPrefs()}var C=parseInt(lpGetPref("pollServerVal",5))*60000;if(C>0){var B=0;if(have_nplastpass()&&typeof(g_nplastpass.get_idle_ms)=="function"){B=g_nplastpass.get_idle_ms()
}if(B>=C){C*=g_logoff_other_ses?12:60}if(E-g_lastpoll>=C){var A=base_url+"poll_server.php";var D="";if(g_uid!=null&&g_uid!=""&&lp_phpsessid!=null&&lp_phpsessid!=""){A=A.replace(/^https:\/\//,"http://");D="sidhash="+LP.en(SHA256(lp_phpsessid))}lpMakeRequest(A,D,poll_server_response,null);g_lastpoll=(new Date()).getTime()
}}}setTimeout("poll_server();",60000)}function poll_server_response(C){if(4==C.readyState){if(C.status==200&&C.responseXML!=null&&C.responseXML.documentElement!=null){var E=C.responseXML.documentElement;var A=E.getElementsByTagName("ok");if(A.length>0){g_logoff_other_ses=(A[0].getAttribute("logoff_other_ses")=="1"?true:false);
var B=A[0].getAttribute("accts_version");if(B>g_local_accts_version){get_accts()}}}else{var D="Problem in poll_server_response. status="+C.status;lpReportError(D,null)}}}function upgrade_response(B){if(4==B.readyState){if(B.status==200&&B.responseXML!=null&&B.responseXML.documentElement!=null){var D=B.responseXML.documentElement;
var A=D.getElementsByTagName("updatecheck");if(A.length>0){upgrade=(A[0].getAttribute("upgrade")=="1"?true:false);upgradeurl=A[0].getAttribute("codebase");g_notification_type="upgrade";g_notification_data={upgrade:upgrade,upgradeurl:upgradeurl};sendTS({cmd:"notification",type:"upgrade"})}}else{var C="Problem in upgrade_response. status="+B.status;
lpReportError(C,null)}}}function changePassword(C,B){if(B.length==0){return}var E="xml=1";for(var D=0;D<B.length;D++){var A=D>0?D:"";E+="&username"+A+"=dummy";E+="&password"+A+"="+LP.en(lpenc(C));E+="&id"+A+"="+LP.en(B[D])}lpMakeRequest(base_url+"change_pw.php",E,lpChangePasswordResponse,null)}function lpChangePasswordResponse(J){if(J.readyState==4&&J.status==200&&J.responseXML&&J.responseXML.documentElement){var C=J.responseXML.documentElement;
var K=C.getElementsByTagName("ok");if(K.length>0){if(true){var B=atob(K[0].getAttribute("newpassword"));var E=new Array();var H="";while(K[0].hasAttribute("oldpassword"+H)){var A=parseInt(K[0].getAttribute("id"+H));var F=atob(K[0].getAttribute("oldpassword"+H));var I=g_sites[A];if(!lp_in_array(I.tld,E)){E[E.length]=I.tld
}if(I.password==F){I.password=B}if(I.fields){for(var D=0;D<I.fields.length;D++){if(I.fields[D].type=="password"&&I.fields[D].value==F){I.fields[D].value=B}}}if(H==""){H=1}else{H++}}for(var D in g_sites){if(g_sites[D].genpw&&lp_in_array(g_sites[D].tld,E)&&g_sites[D].password==B){delete g_sites[D]}}g_local_accts_version++;
rewritelocalfile();var G=K[0].getAttribute("accts_version");if(!compare_accounts_versions(G,g_local_accts_version)){get_accts()}}else{get_accts()}}}}var lpyubidata={};function yubikey_getotp(B){grid_setdata("active","1");lpdbg("yubikey","Asking user for fresh otp");var A={otp:"",username:B};openURL(getchromeurl("lp_toolstrip.html?browseraction=1&yubikey=1"));
return A.otp}function yubikey_setdata(B,A){lpdbg("yubikey","setting "+B+"="+A);lpyubidata[B]=A}function yubikey_getdata(A){if(typeof(lpyubidata[A])=="undefined"){return null}return lpyubidata[A]}function yubikey_cleardata(){lpdbg("yubikey","clearing data");lpyubidata={}}function yubikey_auth(F,C){grid_setdata("active",null);
if(F!=""){if(yubikey_getdata("offline")=="1"){var E=F.substring(0,12);F=SHA256(SHA256(SHA256(fix_username("LastPassIsGreat")+E)+E));yubikey_setdata("password_offline",F);offlineloginsuccessful("offline",0);lpReadAcctsData();yubikey_setdata("offline","0");return}var D=null;var B=null;var H=null;var A=null;
if(yubikey_getdata("postdata")){D=yubikey_getdata("postdata")+"&otp="+encodeURIComponent(F);B="login.php";H=lpLoginResponse;A=lpLoginError}else{D=sesame_getdata("logincheckpostdata")+"&otp="+encodeURIComponent(F);B="login_check.php";H=lpLoginCheckResponse;A=lpLoginCheckError}if(C!=""){D+="&trustlabel="+encodeURIComponent(C)
}var G=sesame_getdata("fromwebsite");lpMakeRequest(base_url+B,D,H,A,G)}else{lpshowError("LoginError",false,true);loggedOut()}}var lpsesamedata={};var lpsesameotp=null;function sesame_setotp(A){lpdbg("sesame","browser forwarded OTP => sesame_setotp called");lpsesameotp=A}function sesame_getotp(C){grid_setdata("active","1");
if(C&&lpsesameotp){lpdbg("sesame","Not requesting OTP - using value passed to browser");var A=lpsesameotp;lpsesameotp=null;return A}lpdbg("sesame","Asking user for fresh otp");var B={otp:"",username:C};openURL(getchromeurl("lp_toolstrip.html?browseraction=1&sesame=1"));return B.otp}function sesame_setdata(B,A){lpdbg("sesame","setting "+B+"="+A);
lpsesamedata[B]=A}function sesame_getdata(A){if(typeof(lpsesamedata[A])=="undefined"){return null}return lpsesamedata[A]}function sesame_cleardata(){lpdbg("sesame","clearing data");lpsesamedata={}}function sesame_auth(E,C){grid_setdata("active",null);if(E!=""){if(sesame_getdata("offline")=="1"){sesame_setdata("password_offline",E);
offlineloginsuccessful("offline",0);lpReadAcctsData();sesame_setdata("offline","0");return}var D=null;var B=null;var G=null;var A=null;if(sesame_getdata("postdata")){D=sesame_getdata("postdata")+"&sesameotp="+encodeURIComponent(E);B="login.php";G=lpLoginResponse;A=lpLoginError}else{D=sesame_getdata("logincheckpostdata")+"&sesameotp="+encodeURIComponent(E);
B="login_check.php";G=lpLoginCheckResponse;A=lpLoginCheckError}if(C!=""){D+="&trustlabel="+encodeURIComponent(C)}var F=sesame_getdata("fromwebsite");lpMakeRequest(base_url+B,D,G,A,F)}else{lpshowError("LoginError",false,true);loggedOut()}}var lpgriddata={};var lpgridvalues=null;function grid_getvalues(B,A){grid_setdata("active","1");
openURL(getchromeurl("lp_toolstrip.html?browseraction=1&grid=1&challenge="+encodeURIComponent(A)))}function grid_setdata(B,A){lpgriddata[B]=A}function grid_getdata(A){if(typeof(lpgriddata[A])=="undefined"){return null}return lpgriddata[A]}function grid_cleardata(){lpdbg("grid","clearing data");lpgriddata={}
}function grid_auth(E,C){grid_setdata("active",null);if(E!=""){var D=null;var B=null;var G=null;var A=null;if(grid_getdata("postdata")){D=grid_getdata("postdata")+"&gridresponse="+encodeURIComponent(E);B="login.php";G=lpLoginResponse;A=lpLoginError}else{D=sesame_getdata("logincheckpostdata")+"&gridresponse="+encodeURIComponent(E);
B="login_check.php";G=lpLoginCheckResponse;A=lpLoginCheckError}if(C!=""){D+="&trustlabel="+encodeURIComponent(C)}if(grid_getdata("wxsessid")){D+="&wxsessid="+encodeURIComponent(grid_getdata("wxsessid"))}var F=grid_getdata("fromwebsite");lpMakeRequest(base_url+B,D,G,A,F)}else{lpshowError("LoginError",false,true);
loggedOut()}}var lpmultifactordata={};var lpmultifactorresponse=null;function multifactor_getresponse(F,C){var A="";var B="";multifactor_setdata("active","1");var D=multifactor_getdata("type");var E="";if(multifactor_getdata("type")==D){E=multifactor_getdata("password_offline")}if(!E||E.length!=64){E=SHA256(SHA256(fix_username(F)+D))
}if(!E||E.length!=64){if(D=="trueapi"){if(have_nplastpass()&&typeof(g_nplastpass.trueapi_get_hash)=="function"){E=g_nplastpass.trueapi_get_hash(F)}}}multifactor_setdata("password_offline",E);multifactor_setdata("type",D);if(C){A=E!=""?SHA256(E+C):""}else{A=E}multifactor_auth(A,B)}function multifactor_setdata(B,A){lpmultifactordata[B]=A
}function multifactor_getdata(A){if(typeof(lpmultifactordata[A])=="undefined"){return null}return lpmultifactordata[A]}function multifactor_cleardata(){lpdbg("multifactor","clearing data");lpmultifactordata={}}function multifactor_auth(B,D){multifactor_setdata("active",null);if(B!=""){if(multifactor_getdata("offline")=="1"){multifactor_setdata("password_offline",B);
multifactor_setdata("type","trueapi");offlineloginsuccessful("offline",0);lpReadAcctsData();multifactor_setdata("offline","0");return}var E=null;var C=null;var G=null;var A=null;if(multifactor_getdata("postdata")){E=multifactor_getdata("postdata")+"&multifactorresponse="+encodeURIComponent(B);C="login.php";
G=lpLoginResponse;A=lpLoginError}else{E=sesame_getdata("logincheckpostdata")+"&multifactorresponse="+encodeURIComponent(B);C="login_check.php";G=lpLoginCheckResponse;A=lpLoginCheckError}if(D!=""){E+="&trustlabel="+encodeURIComponent(D)}if(multifactor_getdata("wxsessid")){E+="&wxsessid="+encodeURIComponent(multifactor_getdata("wxsessid"))
}if(multifactor_getdata("type")){E+="&type="+encodeURIComponent(multifactor_getdata("type"))}var F=multifactor_getdata("fromwebsite");var F=multifactor_getdata("fromwebsite");lpMakeRequest(base_url+C,E,G,A,F)}else{lpshowError("LoginError",false,true,false,get_multifactor_disable_url(g_username,multifactor_getdata("type")));
loggedOut()}}function lpSetupMultifactorResponse(D,H,E){if(4==D.readyState){if(200==D.status&&D.responseXML!=null&&D.responseXML.documentElement!=null){var G=D.responseXML.documentElement;var B=G.getElementsByTagName("ok");if(B.length>0){var C=B[0].getAttribute("type");var F=B[0].getAttribute("hash");
if(C=="trueapi"){if(typeof(E.password)!="undefined"){if(have_nplastpass()&&typeof(g_nplastpass.trueapi_store_default_login)=="function"){if(g_nplastpass.trueapi_store_hash(g_username,F)){var A=E.silent=="1"?F:g_nplastpass.trueapi_get_hash(g_username);if(A==F){if(g_nplastpass.trueapi_store_default_login(g_username,E.password,F)){lpPutGblPref("singlefactortype",C);
lpPutGblPref("openloginstart",1);lpWriteAllPrefs();if(E.silent!="1"){sendCS(E.tabid,{cmd:"setupsinglefactor",result:"done"},E.docnum)}return}}}}}else{if(have_nplastpass()&&typeof(g_nplastpass.trueapi_store_hash)=="function"){if(g_nplastpass.trueapi_store_hash(g_username,F)){var A=E.silent=="1"?F:g_nplastpass.trueapi_get_hash(g_username);
if(A==F&&E.silent!="1"){sendCS(E.tabid,{cmd:"setupmultifactor",result:"done"},E.docnum);return}}}}}else{if(C=="vtapi"){if(have_nplastpass()&&typeof(g_nplastpass.lpvt_store_data)=="function"){if(g_nplastpass.lpvt_store_data(encodeURIComponent(g_username)+"|"+encodeURIComponent(E.password),gs("Swipe finger"),gs("Swipe your finger on the fingerprint sensor"),gs("Cancel"))){lpPutGblPref("singlefactortype",C);
lpPutGblPref("openloginstart",1);lpWriteAllPrefs();if(E.silent!="1"){sendCS(E.tabid,{cmd:"setupsinglefactor",result:"done"},E.docnum)}return}}}}}}lpSetupMultifactorError(E)}}function lpSetupMultifactorError(A){if(A.silent!=1){sendCS(A.tabid,{cmd:typeof(A.password)!="undefined"?"setupsinglefactor":"setupmultifactor",result:"error"},A.docnum)
}}function get_multifactor_disable_url(B,A){return"multifactordisable.php?cmd=sendemail&username="+en(B)+"&type="+en(A)}function lp_StartLogin(A){if(g_loginstarted){return}g_loginstarted=true;if(A){rsa_setpendingsharests();lplogincheck("frompipes")}else{httptest()}};
