function oninitgenerate(){}function onshowgenerate(){var A=getBG();document.getElementById("advanced").checked=parseInt(A.lpGetPref("generate_advanced",0));document.getElementById("length").value=parseInt(A.lpGetPref("generate_length",8));document.getElementById("upper").checked=parseInt(A.lpGetPref("generate_upper",1));
document.getElementById("lower").checked=parseInt(A.lpGetPref("generate_lower",1));document.getElementById("digits").checked=parseInt(A.lpGetPref("generate_digits",1));document.getElementById("special").checked=parseInt(A.lpGetPref("generate_special",0));document.getElementById("mindigits").value=parseInt(A.lpGetPref("generate_mindigits",1));
document.getElementById("ambig").checked=parseInt(A.lpGetPref("generate_ambig",0));document.getElementById("reqevery").checked=parseInt(A.lpGetPref("generate_reqevery",1));if(document.getElementById("advanced").checked==0){document.getElementById("advancedoptions").style.display="none"}create_combo("password",new Array());
dogenerate();chrome.tabs.getSelected(null,function(B){if(g_generate_url==""){g_generate_url=B.url}if(!g_tabid){g_tabid=B.id}A.g_checkgeneratepasswordcallback=function(){g_generate_found=true;sr(document,"generatesave","value","Accept");sr(document,"generateclose","value","Cancel")};A.sendCS(g_tabid,{cmd:"checkgeneratepassword"})
})}function onhidegenerate(){var A=getBG();A.lpPutUserPref("generate_advanced",document.getElementById("advanced").checked?1:0);A.lpPutUserPref("generate_length",document.getElementById("length").value);A.lpPutUserPref("generate_upper",document.getElementById("upper").checked?1:0);A.lpPutUserPref("generate_lower",document.getElementById("lower").checked?1:0);
A.lpPutUserPref("generate_digits",document.getElementById("digits").checked?1:0);A.lpPutUserPref("generate_special",document.getElementById("special").checked?1:0);A.lpPutUserPref("generate_mindigits",document.getElementById("mindigits").value);A.lpPutUserPref("generate_ambig",document.getElementById("ambig").checked?1:0);
A.lpPutUserPref("generate_reqevery",document.getElementById("reqevery").checked?1:0);A.lpWriteAllPrefs()}function dogenerate(){var F=document.getElementById("length").value;var D=document.getElementById("upper").checked;var C=document.getElementById("lower").checked;var G=document.getElementById("digits").checked;
var B=document.getElementById("special").checked;var E=document.getElementById("mindigits").value;var A=document.getElementById("ambig").checked;var H=document.getElementById("reqevery").checked;document.getElementById("password").value=lpCreatePass(F,D,C,G,B,E,A,H);getBG().g_genpws.unshift(document.getElementById("password").value);
if(getBG().g_genpws.length>20){getBG().g_genpws.splice(20,getBG().g_genpws.length-20)}repopulate_combo("password",getBG().g_genpws);update_password_meter("",document.getElementById("password").value)}function dosave(){var A=document.getElementById("password").value;if(!g_generate_found){Clipboard.copy(A)
}var B=getBG();B.savePassword(A,g_generate_url,g_tabid,!g_generate_found);window.close()}function lpCreatePass(C,R,U,I,B,O,S,D){if(typeof(C)=="undefined"){C=8+get_random(0,1)}if(typeof(R)=="undefined"){R=true}if(typeof(U)=="undefined"){U=true}if(typeof(I)=="undefined"){I=true}if(typeof(B)=="undefined"){B=false
}if(typeof(O)=="undefined"){O=0}if(typeof(S)=="undefined"){S=false}if(typeof(D)=="undefined"){D=true}var L=0;var F=0;var P=0;if(D){L=F=P=1}var E=new Array();if(U&&L>0){for(var Q=0;Q<L;Q++){E[E.length]="L"}}if(R&&F>0){for(var Q=0;Q<F;Q++){E[E.length]="U"}}if(I&&O>0){for(var Q=0;Q<O;Q++){E[E.length]="D"
}}if(B&&P>0){for(var Q=0;Q<P;Q++){E[E.length]="S"}}while(E.length<C){E[E.length]="A"}E.sort(function(){return get_random(0,1)*2-1});var K="";var J="abcdefghjkmnpqrstuvwxyz";if(!S){J+="ilo"}if(U){K+=J}var N="ABCDEFGHJKMNPQRSTUVWXYZ";if(!S){N+="ILO"}if(R){K+=N}var T="23456789";if(!S){T+="10"}if(I){K+=T
}var M="!@#$%^&*";if(B){K+=M}var A="";for(var G=0;G<C;G++){var H;switch(E[G]){case"L":H=J;break;case"U":H=N;break;case"D":H=T;break;case"S":H=M;break;case"A":H=K;break}var Q=get_random(0,H.length-1);A+=H.charAt(Q)}return A}function showhideadv(){var A=document.getElementById("advancedoptions");A.style.display=(A.style.display=="none"?"":"none")
};
