var g_tsstart=(new Date()).getTime();var g_bg=null;function gs(B){var A=B.replace(/[^a-zA-Z0-9_]/g,"_");var C="";if(typeof(chrome.i18n)!="undefined"&&typeof(chrome.i18n.getMessage)=="function"){C=chrome.i18n.getMessage(A)}if(typeof(C)=="undefined"||C==null){C=""}if(C==""){C=B}return C}function sr(C,E,A,D){var B=C.getElementById(E);
if(B){B.setAttribute(A,gs(D))}}function L(A){console.log(((new Date()).getTime()-g_tsstart)+" : "+A)}function probe(B,D){var C=B;for(i in D){var A=typeof(D[i]);if(A=="string"||A=="number"){A=D[i]}C+="\n"+i+" : "+A}L(C)}function getchromeurl(A){return chrome.extension.getURL(A)}function getBG(){if(g_bg!=null){return g_bg
}try{if(typeof(chrome.extension.getBackgroundPage)=="function"){g_bg=chrome.extension.getBackgroundPage();if(g_bg!=null){return g_bg}}var A=chrome.extension.getViews();for(var B in A){if(typeof(A[B].receiveTS)=="function"){g_bg=A[B];return g_bg}}L("TS : getBG FAILED");return null}catch(C){L("TS : getBG FAILED error="+C)
}return null}function array_length(B){var A=0;for(var C in B){A++}return A}Clipboard={};Clipboard.utilities={};Clipboard.utilities.createTextArea=function(B){var A=document.createElement("textarea");A.style.position="absolute";A.style.left="-100%";if(B!=null){A.value=B}document.body.appendChild(A);return A
};Clipboard.copy=function(B){if(B==null){return}if(B==""){B=" "}var A=Clipboard.utilities.createTextArea(B);A.select();document.execCommand("Copy");document.body.removeChild(A)};Clipboard.paste=function(){var A=Clipboard.utilities.createTextArea();A.focus();document.execCommand("Paste");var B=A.value;
document.body.removeChild(A);return B};function es(A){A=A.replace(/\\/g,"\\\\");A=A.replace(/'/g,"\\'");A=A.replace(/"/g,'\\"');return A}function show_password_meter(A){document.writeln('<div id="page_passwordmeterback" style="text-align:left;height:10px;border:1px solid #B5B8C8;width:'+A+'px;background-image:url(images/passwordmeter_back.gif);margin-top:3px;">');
document.writeln('<div id="page_passwordmeterfront" style="background-image:url(images/passwordmeter_front.gif);height:10px;width:50px;line-height:1px;font-size:1px;">');document.writeln("</div>");document.writeln("</div>")}function update_password_meter(C,D){var A=parseInt(document.getElementById("page_passwordmeterback").style.width);
var E=getpasswordstrength(C,D);var B=Math.round(E*A/100)+"px";document.getElementById("page_passwordmeterfront").style.width=B}function getpasswordstrength(B,D){var E=0;if(B==""&&D==""){return 0}if(D==B){return 1}if(B!=""&&B.indexOf(D)!=-1){E-=15}if(B!=""&&D.indexOf(B)!=-1){E-=B.length}E+=D.length;if(D.length>0&&D.length<=4){E+=D.length
}else{if(D.length>=5&&D.length<=7){E+=6}else{if(D.length>=8&&D.length<=15){E+=12}else{if(D.length>=16){E+=18}}}}if(D.match(/[a-z]/)){E+=1}if(D.match(/[A-Z]/)){E+=5}if(D.match(/\d/)){E+=5}if(D.match(/.*\d.*\d.*\d/)){E+=5}if(D.match(/[!,@,#,$,%,^,&,*,?,_,~]/)){E+=5}if(D.match(/.*[!,@,#,$,%,^,&,*,?,_,~].*[!,@,#,$,%,^,&,*,?,_,~]/)){E+=5
}if(D.match(/(?=.*[a-z])(?=.*[A-Z])/)){E+=2}if(D.match(/(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/)){E+=2}if(D.match(/(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!,@,#,$,%,^,&,*,?,_,~])/)){E+=2}var G=[];var A=0;var C,F;for(C=0;C<D.length;++C){F=D.charAt(C);if(typeof(G[F])=="undefined"){G[F]=1;++A}}if(A==1){return 2}E*=2;
if(E<0){E=0}else{if(E>100){E=100}}return E};
