var g_maxchars=0;var g_maxcharsmatch=0;var g_menuwidth=0;var g_menuwidthmatch=0;var g_menus=[];var g_menutitles=[];var g_menuspeed=10000;var g_hoverrow=null;var g_autoclickenabled=false;function onheightmenu(){return getBG().getmenuheight(true,true,true,g_browseraction)}function oninitmenu(){}function onshowmenu(){rebuildmenu();
setTimeout("menuconnectevents()",100)}function onhidemenu(){$("#menu").html("")}function menuaction(E,C){L("TSM : menuaction cmd="+E);g_hoverrow=null;var B=getBG();if(!B){return}var D="";var F="";var A="";if(E.indexOf("identity")==0&&E!="identityadd"){F=E.substring(8);if(F=="all"){F=""}E="identityswitch"
}if(E.indexOf("matchopen")==0){D=E.substring(9);L("menuopen: "+D+" title: "+C);menuopen("match"+D,"match",C);return}else{if(E.indexOf("opendelete")==0){var G=E.substring(10);menuopendelete(G,C);return}else{if(E.indexOf("matchedit")==0){D=E.substring(9);E="matchedit"}else{if(E.indexOf("matchfill")==0){D=E.substring(9);
E="matchfill"}else{if(E.indexOf("matchcopyusername")==0){D=E.substring(17);E="matchcopyusername"}else{if(E.indexOf("matchcopypassword")==0){D=E.substring(17);E="matchcopypassword"}else{if(E.indexOf("matchdelete")==0){D=E.substring(11);E="matchdelete"}else{if(E.indexOf("matchgotourl")==0){D=E.substring(12);
E="matchgotourl"}}}}}}}}if(E.indexOf("recentlyused")==0){D=E.substring(12);E=D=="clear"?"clearrecent":"site"}else{if(E.indexOf("site")==0&&E!="siteadd"){D=E.substring(4);E="site"}else{if(E.indexOf("note")==0&&E!="noteadd"){D=E.substring(4);E="note"}else{if(E.indexOf("fillforms")==0){A=E.substring(9);
E="fillforms"}else{if(E.indexOf("editprofile")==0){A=E.substring(11);E="editprofile"}}}}}switch(E){case"logoff":B.loggedOut();break;case"vault":B.openvault();break;case"openfavorites":B.openfavorites();break;case"preferences":B.openprefs();break;case"help":B.openhelp();break;case"premium":B.openpremium();
break;case"server":B.upgradetoserver();break;case"saveall":B.saveall();break;case"tools":case"feedback":B.openfeedback();break;case"generate":if(g_browseraction){hidemenu();openmole("lpgenerate");return}else{B.opengenpw()}break;case"search":B.opensearch();break;case"recheck":B.recheckpage();break;case"refresh":B.refreshsites();
break;case"importgooglechrome":B.openimportchrome();break;case"lpimport":B.openimport();break;case"importfirefoxgo":break;case"importfirefoxhelp":break;case"import1passwordgo":break;case"import1passwordhelp":break;case"importkeepassgo":break;case"importkeepasshelp":break;case"importlastpassgo":break;
case"importlastpasshelp":break;case"importmsipasswordkeepergo":break;case"importmsipasswordkeeperhelp":break;case"importmypasswordsafego":break;case"importmypasswordsafehelp":break;case"importpasspackgo":break;case"importpasspackhelp":break;case"importpasswordagentgo":break;case"importpasswordagenthelp":break;
case"importpasswordkeepergo":break;case"importpasswordkeeperhelp":break;case"importpasswordsafego":break;case"importpasswordsafehelp":break;case"importroboformgo":break;case"importroboformhelp":break;case"importturbopasswordsgo":break;case"importturbopasswordshelp":break;case"importcsvgo":break;case"importcsvhelp":break;
case"exportlastpass":break;case"exportchrome":break;case"exportcsv":B.openexport();break;case"printsites":B.openprint(false);break;case"printnotes":B.openprint(true);break;case"update":hidemenu();B.checkforupdates();return;case"clear":B.clearCache(false);break;case"sessions":B.opensessions();break;case"seccheck":B.openseccheck();
break;case"about":B.openabout();break;case"addsite":B.openaddsite();break;case"addnote":B.openaddsecurenote();break;case"clearrecent":B.clearrecent();break;case"identityswitch":B.switch_identity(F);break;case"identityadd":B.add_identity();break;case"site":B.launch(D);break;case"siteadd":B.openaddsite();
break;case"note":B.launch(D);break;case"noteadd":B.openaddsecurenote();break;case"fillforms":B.fillform(A);break;case"editprofile":B.editprofile(A);break;case"addprofile":B.addprofile();break;case"addcreditcard":B.addcreditcard();break;case"clearforms":B.clearforms();break;case"chooseprofilecc":if(g_browseraction){hidemenu();
openmole("lpchooseprofilecc");return}else{B.openchooseprofilecc()}break;case"matchedit":B.editAid(D);break;case"matchfill":B.fillaid(D);break;case"matchcopyusername":B.copyusername(D);break;case"matchcopypassword":B.copypassword(D);break;case"matchdelete":B.deleteAid(D,null);break;case"matchgotourl":B.gotourl(D,null);
break;default:L("TSM : INVALID MENU ACTION cmd="+E);break}closemole()}function deletenever(C,B){var A=getBG().getnevers();var D=A[C];getBG().deleteNever(D);closemole()}function rightclickmenuaction(B){var A="";if(B.indexOf("site")==0&&B!="siteadd"){A=B.substring(4);B="match_noautofill"+A}else{if(B.indexOf("recentlyused")==0){A=B.substring(12);
B="match_noautofill"+A}else{if(B.indexOf("note")==0&&B!="noteadd"){A=B.substring(4);B="match_note"+A}else{return}}}menuopen(B,"match","")}function getmenu(){var G=getBG();var Z="";if(G.g_identity==""){Z=gs("All")}else{var X;for(X=0;X<G.g_identities.length;X++){if(G.g_identities[X].iid==G.g_identity){Z=G.g_identities[X].deciname;
break}}}var J={identityall:{title:gs("All")}};if(G.g_identity==""){J.identityall.icon="images/checkmark.gif"}var I=G.g_identities.length;for(X=0;X<I;++X){J["identity"+G.g_identities[X].iid]={title:G.g_identities[X].deciname};if(G.g_identities[X].iid==G.g_identity){J["identity"+G.g_identities[X].iid].icon="images/checkmark.gif"
}}J.linebreak0=null;J.identityadd={title:gs("Add Identity")};var W={};var D=G.lpGetPref("showAcctsInGroups",1)==1;var V={};var M;var N;var A=false;var c=new Array();var O=new Array();var B=false;for(M in G.g_sites){if(G.check_ident_aid(M)){A=true;N=G.g_sites[M].group;if(N==null||N==""){N=gs("(none)")
}var K=N.split("\\");var T="";for(var X=0;X<K.length;X++){if(T!=""){T+="\\"}T+=K[X];if(!lp_in_array(T,c)){c[c.length]=T}}O[O.length]=G.g_sites[M];if(G.g_sites[M].fav=="1"){B=true}}}c.sort(function(f,e){return f.toLowerCase()<e.toLowerCase()?-1:1});var a=D&&(B||c.length>1);if(a&&B){V[gs("favorites")]={title:gs("favorites"),children:{}}
}var H=c.length;var d=new Array();for(var X=0;X<H;X++){var N=c[X];var U=N.lastIndexOf("\\");var T=U==-1?N:N.substring(U+1);var S={title:T,children:{}};d[N]=S;if(U==-1){if(a){V[N+"sites"]=S}}else{d[N.substring(0,U)].children[N.replace(/\\/g,"~|~")+"sites"]=S}}O.sort(function(f,e){return f.last_touch>e.last_touch?-1:1
});var E=localStorage.getItem(G.g_username_hash+"recent");if(E==null){E=0}for(var X=0;X<O.length&&X<10;X++){if(O[X].last_touch<E){continue}W["recentlyused"+O[X].aid]={title:O[X].name,icon:G.geticonurl(O[X].fiid,true)}}if(array_length(W)==0){W.recentlyused0={title:gs("None Available")}}else{W.linebreak0=null;
W.recentlyusedclear={title:gs("Clear Recent")}}O.sort(function(f,e){return f.name.toLowerCase()<e.name.toLowerCase()?-1:1});for(var X=0;X<O.length;X++){if(a&&O[X].fav=="1"){V[gs("favorites")].children["site"+O[X].aid]={title:O[X].name,icon:G.geticonurl(O[X].fiid)}}N=O[X].group;if(N==null||N==""){N=gs("(none)")
}var S={title:O[X].name,icon:G.geticonurl(O[X].fiid)};if(a){d[N].children["site"+O[X].aid]=S}else{V["site"+O[X].aid]=S}}if(A){V.linebreak0=null}V.siteadd={title:gs("Add Site")};var R={};var M;var N;A=false;var c=new Array();var Y=new Array();for(M in G.g_securenotes){if(G.check_ident_aid(M)){A=true;N=G.g_securenotes[M].group;
if(N==null||N==""){N=gs("(none)")}if(N!=gs("Secure Notes")){var K=N.split("\\");var T="";for(var X=0;X<K.length;X++){if(T!=""){T+="\\"}T+=K[X];if(!lp_in_array(T,c)){c[c.length]=T}}}Y[Y.length]=G.g_securenotes[M]}}c.sort(function(f,e){return f.toLowerCase()<e.toLowerCase()?-1:1});var P=D&&c.length>1;d=new Array();
for(var X=0;X<c.length;X++){var N=c[X];var U=N.lastIndexOf("\\");var T=U==-1?N:N.substring(U+1);var S={title:T,children:{}};d[N]=S;if(U==-1){if(P){R[N+"notes"]=S}}else{d[N.substring(0,U)].children[N.replace(/\\/g,"~|~")+"notes"]=S}}Y.sort(function(f,e){return f.name.toLowerCase()<e.name.toLowerCase()?-1:1
});for(var X=0;X<Y.length;X++){N=Y[X].group;if(N==null||N==""){N=gs("(none)")}if(P&&N!=gs("Secure Notes")){d[N].children["note"+Y[X].aid]={title:Y[X].name,icon:G.geticonurl(Y[X].fiid)}}}for(var X=0;X<Y.length;X++){N=Y[X].group;if(!P||N==gs("Secure Notes")){R["note"+Y[X].aid]={title:Y[X].name,icon:G.geticonurl(Y[X].fiid,true)}
}}if(A){R.linebreak0=null}R.noteadd={title:gs("Add Secure Note")};var Q={};A=false;var C=false;var b=false;for(var X=0;X<G.g_formfills.length;X++){if(G.check_ident_ffid(G.g_formfills[X].ffid)){A=true;Q["fillforms"+G.g_formfills[X].ffid]={title:G.g_formfills[X].decprofilename};if(G.g_formfills[X].profiletype==0){C=true
}if(G.g_formfills[X].ccnum!=""){b=true}}}if(A){Q.linebreak0=null;Q.editprofiles={title:gs("Edit"),children:{}};for(var X=0;X<G.g_formfills.length;X++){if(G.check_ident_ffid(G.g_formfills[X].ffid)){Q.editprofiles.children["editprofile"+G.g_formfills[X].ffid]={title:G.g_formfills[X].decprofilename}}}}Q.addprofile={title:gs("Add Profile")};
Q.addcreditcard={title:gs("Add Credit Card")};Q.clearforms={title:gs("Clear Forms")};if(C&&b){Q.chooseprofilecc={title:gs("Choose Profile and Credit Card")}}var F={logoff:{icon:"images/icon_lock.png",title:gs("Logoff:")+" "+G.g_username,cmd:"logoff"},identities:{icon:"images/icon_identities.png",title:gs("Identities")+" ("+Z+")",hidden:G.g_hideidentities,children:J},linebreak1:null,vault:{icon:"images/icon_vault.png",title:gs("My LastPass Vault"),hotkey:"Ctrl+Alt+H",cmd:"vault"},recent:{icon:"images/icon_recent.png",title:gs("Recently Used"),children:W},sites:{icon:"images/icon_sites.png",title:gs("Sites"),children:V},notes:{icon:"images/icon_notes.png",title:gs("Secure Notes"),hidden:G.g_hidenotes,children:R},openfavorites:{icon:"images/icon_favorites.png",title:gs("Open Favorites"),cmd:"openfavorites",hidden:!B},formfill:{icon:"images/icon_formfill.png",title:gs("Fill Forms"),children:Q},preferences:{icon:"images/icon_preferences.png",title:gs("Preferences"),cmd:"preferences"},help:{icon:"images/icon_help.png",title:gs("Help..."),cmd:"help"},tools:{icon:"images/icon_tools.png",title:gs("Tools"),children:{generate:{icon:"images/keyboard.png",title:gs("Generate Secure Password"),key:"Alt+G"},feedback:{icon:"images/up-red.gif",title:gs("Feedback")},search:{icon:"images/search-icon-blue.gif",title:gs("Site Search"),key:"Alt+W"},recheck:{icon:"images/page_gear.png",title:gs("Recheck Page"),key:"Alt+I"},refresh:{icon:"images/reload.gif",title:gs("Refresh Sites"),hidden:G.LPISLOC},importmenu:{icon:"images/import.png",title:gs("Import From"),hidden:G.g_hideimport,children:{importgooglechrome:{title:gs("Google Chrome Password Manager")},lpimport:{title:gs("Other"),hidden:G.LPISLOC}}},lpexport:{icon:"images/export.png",title:gs("Export To"),hidden:G.g_hideexport,children:{exportcsv:{title:gs("LastPass CSV File")},}},print:{icon:"images/printer.png",title:gs("Print"),hidden:G.g_hideprint,children:{printsites:{title:gs("Sites")},printnotes:{title:gs("Secure Notes")}}},update:{icon:"images/exclamation.png",title:gs("Check For Updates")},clear:{icon:"images/computer_delete.png",title:gs("Clear Local Cache"),hidden:G.LPISLOC},seccheck:{icon:"images/tick.png",title:gs("Security Check"),hidden:G.LPISLOC},sessions:{icon:"images/group_key.png",title:gs("Other Sessions"),hidden:G.LPISLOC},about:{icon:"images/icon16.png",title:gs("About...")},linebreak0:null,addsite:{icon:"images/icon_saveall.png",title:gs("Add Site")},addnote:{icon:"images/note_add.png",title:gs("Add Secure Note"),hidden:G.g_hidenotes}}},linebreak2:null,premium:{icon:"images/icon_premium.png",title:gs("Go Premium!"),cmd:"premium",hidden:G.LPISLOC},server:{icon:"images/icon_premium.png",title:gs("Upgrade to LastPass Online!"),cmd:"server",hidden:!G.LPISLOC},saveall:{icon:"images/icon_saveall.png",title:gs("Save All Entered Data"),cmd:"saveall"},matchscroll:null};
return F}function rebuildmenu(){g_hoverrow=null;var G="";G+='<div id="menutitle" style="display:none;margin:0 5px 1px 5px;padding:0 5px;cursor:pointer;background:url(menuheader.png) repeat-x;color:#fff;text-align:center;height:20px;line-height:20px;vertical-align:middle;font-weight:bold;"></div>';G+='<div id="backbutton1" class="backbutton" style="display:none;margin:0px 5px;padding:0 5px;cursor:pointer;background:url(backbg.png) repeat-x;color:#fff;text-align:center;height:20px;line-height:20px;vertical-align:middle;font-weight:bold;"><img src="backarrow.png"/> BACK</div>';
G+='<table cellspacing="0"><tr>';G+='<td>&nbsp;<div id="menu0" style="overflow-y:auto;overflow-x:hidden;max-height:400px;"></div></td>';G+='<td>&nbsp;<div id="menu1" style="overflow-y:auto;overflow-x:hidden;max-height:400px;width:0px;display:none;"></div></td>';G+="</tr></table>";G+='<div id="backbutton2" class="backbutton" style="display:none;margin:10px 5px 0 5px;padding:0 5px;cursor:pointer;background:url(backbg.png) repeat-x;color:#fff;text-align:center;height:20px;line-height:20px;vertical-align:middle;font-weight:bold;"><img src="backarrow.png"/> BACK</div>';
$("#menucontainer").html(G);$(".backbutton").hover(function(){g_hoverrow=$(this).attr("id");setTimeout('menuautoclick("'+g_hoverrow+'")',1000);$(this).css({background:"url(backbgover.png) repeat-x"})},function(){g_hoverrow=null;$(this).css({background:"url(backbg.png) repeat-x"})}).click(function(){popmenu()
});var A=getmenu();var K=60;var N=40;g_maxchars=40;g_maxcharsmatch=33;g_menuwidth=9*g_maxchars;g_menuwidthmatch=9*g_maxcharsmatch;var G="";var F;var H;var B;var E;var J;var M;for(F in A){if(F=="matchscroll"){var D=getBG().getnevers();if(D.length>0){G+='\n<div style="height:1px;margin:5px 0;background:#ccc;"></div>';
for(F in D){var I=gs("Never Add Site");if(D[F]["type"]=="neverautologins"){I=gs("Never AutoLogin")}if(D[F]["type"]=="nevergenerates"){I=gs("Never Generate Password")}if(D[F]["type"]=="neverformfills"){I=gs("Never Fill Forms")}if(D[F]["domain"]==1){I+=" "+gs("(domain)")}G+="<div>";G+='<div class="newmenurow" style="float:left;color:#000;padding:1px 5px;" onclick="menuaction(\''+("opendelete"+F)+"','"+es(lpxmlescape(I))+"');\">";
G+='<div style="float:left;width:'+g_menuwidth+'px;cursor:pointer;overflow:hidden;background:url(close.png) no-repeat;padding-left:20px;padding-bottom:2px;">'+I+"</div>";G+='<img src="arrow.png">&nbsp;';G+="</div>";G+='<div style="clear:both;"></div>';G+="</div>"}}var D=getBG().getmatchingsites();if(D.length>0){G+='\n<div style="height:1px;margin:5px 0;background:#ccc;"></div>';
for(F in D){H="match"+D[F]["aid"];I=D[F]["name"]+(D[F]["username"]==""?"":(" ("+D[F]["username"]+")"));if(I.length>g_maxcharsmatch){B=D[F]["name"];E=D[F]["username"];if(B.length>(N-3)){B=B.substring(0,N)+"..."}if(E.length>=(g_maxcharsmatch-B.length-3)){E=E.substring(0,g_maxcharsmatch-B.length-3)+"..."
}I=B+(E==""?"":(" ("+E+")"))}G+="<div>";G+='<div id="menurow'+es(lpxmlescape(H))+'" class="newmenurow" style="float:left;color:#000;padding:1px 5px;" onclick="menuaction(\''+("matchopen"+D[F]["aid"])+"','"+es(lpxmlescape(I))+"');\">";G+='<div style="float:left;width:'+g_menuwidthmatch+"px;cursor:pointer;overflow:hidden;background:url("+getBG().geticonurl(D[F].fiid)+') no-repeat;padding-left:20px;padding-bottom:2px;">'+I+"</div>";
G+='<img src="arrow.png" alt="expand"/>&nbsp;';G+='<div style="clear:both;"></div>';G+="</div>";G+='<img src="fill.png" alt="autofill" style="cursor:pointer;" title="AutoFill" onclick="menuaction(\''+("matchfill"+D[F]["aid"])+"');\"/>&nbsp;";G+='<img src="copyusername.png" alt="copyusername" style="cursor:pointer;" title="Copy Username" onclick="menuaction(\''+("matchcopyusername"+D[F]["aid"])+"');\"/>&nbsp;";
G+='<img src="copypassword.png" alt="copypassword" style="cursor:pointer;" title="Copy Password" onclick="menuaction(\''+("matchcopypassword"+D[F]["aid"])+"');\"/>&nbsp;";G+="&nbsp;&nbsp;&nbsp;&nbsp;";G+='<div style="clear:both;"></div>';G+="</div>"}}continue}else{if(A[F]==null){G+='\n<div style="height:1px;margin:5px 0;background:#ccc;"></div>';
continue}else{if(A[F]["cmd"]=="premium"&&getBG().g_premium_exp>0){continue}}}I=A[F].title;if(I.length>g_maxchars){I=I.substring(0,g_maxchars-3)+"..."}M="";if(typeof(A[F].children)!="undefined"){M=" onclick=\"menuopen('"+es(lpxmlescape(F))+"',null,'"+es(lpxmlescape(I))+"')\""}else{if(typeof(A[F].cmd)!="undefined"){M=" onclick=\"menuaction('"+es(A[F].cmd)+"')\""
}}var C="";if(A[F].hidden){C="display: none;"}G+='<div id="menurow'+es(lpxmlescape(F))+'" class="newmenurow" style="color:#000;padding:1px 5px;'+C+'"'+M+">";G+='<div style="float:left;width:'+g_menuwidth+"px;cursor:pointer;overflow:hidden;background:url("+A[F].icon+') no-repeat;padding-left:20px;padding-bottom:2px;">'+of(I)+"</div>";
if(typeof(A[F].children)!="undefined"){G+='<img src="arrow.png" alt="expand"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'}G+='<div style="clear:both;"></div>';G+="</div>"}pushmenu(G,"")}function pushmenu(C,D){var B=$("#menu0");var A=$("#menu1");var E=A.width();var G=false;if(C){g_menus.push(C);if(g_menus.length==1){B.html(C);
return}A.html(C)}var F=Math.abs(parseInt(B.css("margin-left").replace("px","")));if(F<g_menuwidth){F=(F+g_menuspeed)<g_menuwidth?(F+g_menuspeed):g_menuwidth;B.css("margin-left",-F+"px");if(F==g_menuwidth){B.hide()}else{G=true}}if(g_menus.length!=2){if(E<g_menuwidth){if(E==0){A.show()}E=(E+g_menuspeed)<g_menuwidth?(E+g_menuspeed):g_menuwidth;
A.width(E);G=true}}if(G){setTimeout('pushmenu(null,"'+es(D)+'")',0)}else{B.html(A.html()).css("margin-left","0px");A.hide().html("").css("width","0px");B.show();setTimeout("menuconnectevents()",100);g_menutitles.push(D);$("#menutitle").html(of(D)).show();$(".backbutton").show()}}function popmenu(D){var B=$("#menu0");
var A=$("#menu1");var C=A.width();var F=false;if(!D){B.hide().html(g_menus[g_menus.length-2]).css("margin-left",g_menuwidth+"px");A.css("width",g_menuwidth+"px").html(g_menus[g_menus.length-1]).show();g_menus.pop();C=g_menuwidth}if(C>0){C=(C-g_menuspeed)>0?(C-g_menuspeed):0;A.width(C);if(C==0){A.hide()
}else{F=true}}var E=Math.abs(parseInt(B.css("margin-left").replace("px","")));if(E==g_menuwidth){B.show()}if(E>0){E=(E-g_menuspeed)>0?(E-g_menuspeed):0;B.css("margin-left",-E+"px");F=true}if(F){setTimeout("popmenu(1)",0)}else{A.html("");setTimeout("menuconnectevents()",100);g_menutitles.pop();if(g_menus.length==1){$("#menutitle").hide().html("");
$(".backbutton").hide()}else{$("#menutitle").html(of(g_menutitles[g_menutitles.length-1]))}}}function menuconnectevents(){$(".newmenurow").hover(function(){g_hoverrow=$(this).attr("id");setTimeout('menuautoclick("'+g_hoverrow+'")',1000);$(this).css({background:"#316AC5",color:"#fff"}).children("img").attr("src","arrowon.png")
},function(){g_hoverrow=null;$(this).css({background:"#fff",color:"#000"}).children("img").attr("src","arrow.png")})}function menuautoclick(C){if(!g_autoclickenabled){return}if(C==g_hoverrow){g_hoverrow=null;if(C=="backbutton1"||C=="backbutton2"){$("#"+C).click();return}var D=C.substring(7);var B=D.indexOf("match")==0?"match":null;
var A=getmenuchildren(D,B);if(A==null){return}$("#"+C).click()}}function menuopen(C,H,F){L("menuopen cmd="+C+" menutitle="+F);var B=getmenuchildren(C,H);if(B==null){L("No children for cmd="+C+" menutitle="+F);return}var G="";var K;var A;var I;var J;for(var E in B){A=B[E];if(A==null){G+='\n<div style="height:1px;margin:5px 0;background:#ccc;"></div>';
continue}J=A.title;if(J.length>g_maxchars){J=J.substring(0,g_maxchars-3)+"..."}K="";if(typeof(A.children)!="undefined"){K=" onclick=\"menuopen('"+es(lpxmlescape(E))+"',null,'"+es(lpxmlescape(J))+"')\""}else{K=" onclick=\"menuaction('"+es(lpxmlescape(E))+"','"+es(lpxmlescape(J))+"')\" onContextMenu=\"rightclickmenuaction('"+es(E)+"')\""
}bgicon=typeof(A.icon)!="undefined"?("background:url("+A.icon+") no-repeat;"):"";var D="";if(A.hidden){D="display: none;"}G+='<div id="menurow'+es(lpxmlescape(E))+'" class="newmenurow" style="color:#000;padding:1px 5px;'+D+'"'+K+">";G+='<div style="float:left;width:'+g_menuwidth+"px;cursor:pointer;overflow:hidden;"+bgicon+'padding-left:20px;padding-bottom:2px;">'+lpxmlescape(J)+"</div>";
if(typeof(A.children)!="undefined"){G+='<img src="arrow.png" alt="expand"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'}G+='<div style="clear:both;"></div>';G+="</div>"}pushmenu(G,F)}function menuopendelete(E,C){var B="";var D=gs("Delete");var A=" onclick=\"deletenever('"+es(E)+"')\"";B+='<div id="menurow'+es(E)+'" class="newmenurow" style="color:#000;padding:1px 5px;"'+A+">";
B+='<div style="float:left;width:'+g_menuwidth+'px;cursor:pointer;overflow:hidden;padding-left:20px;padding-bottom:2px;">'+lpxmlescape(D)+"</div>";B+='<div style="clear:both;"></div>';B+="</div>";pushmenu(B,C)}function getmenuchildren(C,B){var A=null;if(B=="match"){A=findmatchmenuchildren(C);if(A!=null){return A
}}return findmenuchildren(C)}function findmenuchildren(D,E){var B;var C=typeof(E)=="undefined"?getmenu():E;for(var A in C){if(A==D){return(C[A]==null||typeof(C[A].children)=="undefined")?null:C[A].children}if(C[A]!=null&&typeof(C[A].children)!="undefined"){B=findmenuchildren(D,C[A].children);if(B!=null){return B
}}}return null}function findmatchmenuchildren(D){if(D.indexOf("match")!=0){return null}var I=true;var H=true;var E=true;var A=false;var C=null;if(D.indexOf("match_noautofill")==0){I=false;A=true;C=D.substring(16)}else{if(D.indexOf("match_note")==0){I=false;H=false;E=false;A=true;C=D.substring(10)}else{C=D.substring(5)
}}var J="matchedit"+C;var N="matchfill"+C;var G="matchcopyusername"+C;var M="matchcopypassword"+C;var K="matchdelete"+C;var B="matchgotourl"+C;var F={};if(A){F[J]={title:gs("Edit")}}if(I){F[N]={title:gs("AutoFill")}}if(H){F[G]={title:gs("Copy Username")};F[M]={title:gs("Copy Password")}}if(!A){F[J]={title:gs("Edit")}
}if(E){F[B]={title:gs("Go to URL")}}F[K]={title:gs("Delete")};return F};
