var g_np_init=false;var namedpipeobserverfunction=null;function lpnp_init(){var A=false;if(A){return}if(!g_is_win&&(!g_is_mac||!LPISLOC)){lpdbg("namedpipes","Linux is totally broken on named pipes, simply quit for now");g_np_init=false;return}if(!g_nplastpass){lpdbg("namedpipes","named pipe server could not be started g_nplastpass="+g_nplastpass);
return}lpdbg("namedpipes","lpnp_init : initializing named pipe server");var B={observe:function(J,M,W){try{if(M!="lpxpcom"){return}var P="";var F=W.match(/^<([^ \/]+)/);if(F){P=F[1]}if(LPISLOC&&P!="refresh_local"&&P!="local_pwchange"){return}lpdbg("namedpipes","received cmd="+P+" data="+W);switch(P){case"pipeinitdone":var Q=g_nplastpass.NamedPipeNumClients();
if(Q>1){var C=new Array();lpnp_notify("internal_logincheck",C);setTimeout(function(){lp_StartLogin()},500)}else{lp_StartLogin()}break;case"logout":lplogoff(true);break;case"login":var V=W.match(/data0=\"([^\"]*)\"/);var U=W.match(/data1=\"([^\"]*)\"/);if(V&&U){var H=V[1];var D=U[1];if(H!=""&&D!=""){lp_loginhelper(H,D,"namedpipes")
}}break;case"refresh":refresh_windows();break;case"switchidentity":var U=W.match(/data0=\"([^\"]*)\"/);if(U){var L=U[1];switch_identity(L,true,false,true)}break;case"launch":var U=W.match(/id=\"([^\"]*)\"/);var S=W.match(/existing=\"([^\"]*)\"/);if(U){var K=U[1];var C=new Array();C.data0=K;lpnp_notify("launchok",C);
if(S){fillaid(K)}else{launch(K)}}break;case"internal_logincheck":if(lploggedin){var C=new Array();C.data0=lp_phpsessid;C.data1=g_username;C.data2=g_identity;lpnp_notify("internal_logincheck_ack",C)}break;case"internal_logincheck_ack":var N=W.match(/data0=\"([^\"]*)\"/);var H=W.match(/data1=\"([^\"]*)\"/);
var X=W.match(/data2=\"([^\"]*)\"/);if(!lploggedin&&N&&H){var T=opendb();createSavedLoginsTable(T);if(T){T.transaction(function(Y){var Z=new Date().getTime();Y.executeSql("UPDATE LastPassSavedLogins2 SET last_login = ? WHERE username = ?",[Z,H[1]],function(a,b){if(b.rowsAffected==0){a.executeSql("INSERT INTO LastPassSavedLogins2 (username, password, last_login) VALUES (?, '', ?)",[H[1],Z])
}},function(a,b){console.log(b)})})}var O=g_username_hash;var E=g_username;g_username=H[1];g_username_hash=SHA256(H[1]);g_identity=""+(X?X[1]:"");lpPutUserPref("identity",X?X[1]:"");g_username=E;g_username_hash=O;lpWriteAllPrefs();lp_phpsessid=N[1];rsa_setpendingsharests();if(have_nplastpass()&&typeof(g_nplastpass.read_file)=="function"){var W=g_nplastpass.read_file(db_prepend(SHA256(H[1])+"_lpall.slps"));
if(typeof(W)!="string"||W==""){W=g_nplastpass.read_file(db_prepend(SHA256(H[1])+"_lpall.lps"));if(typeof(W)=="string"&&W!=""){var I=protect_data(W,true);g_nplastpass.write_file(db_prepend(SHA256(H[1])+"_lpall.slps"),I);g_nplastpass.delete_file(db_prepend(SHA256(H[1])+"_lpall.lps"))}}else{W=unprotect_data(W,true)
}if(typeof(W)=="string"&&W!=""){var T=opendb();createDataTable(T);if(T){T.transaction(function(Y){Y.executeSql("REPLACE INTO LastPassData (username_hash, type, data) VALUES (?, 'key', ?)",[db_prepend(SHA256(H[1])),W],function(Z,a){lp_StartLogin(true)},function(Z,a){console.log(a)})})}}}}else{if(lploggedin&&N&&H){if(lp_phpsessid!=N[1]||g_username!=H[1]){lplogoff()
}}}break;case"refresh_local":var G=W.match(/data0=\"([^\"]*)\"/);if(G&&G[1]==g_username_hash){get_accts_local()}break;case"local_pwchange":lplogoff();break;default:lpdbg("namedpipes","received unknown message. data="+W);break}}catch(R){}}};namedpipeobserverfunction=B.observe;g_nplastpass.StartNamedPipeServer();
g_np_init=true;setTimeout(function(){lpnp_notify("logincheck")},1000)}function lpnp_notify(B,A){if(LPISLOC&&B!="refresh_local"&&B!="local_pwchange"){return}if(!g_nplastpass||!g_np_init||!have_nplastpass()||typeof(g_nplastpass.SendNamedPipeMessageToAll)!="function"){return}var C=lpnp_xml_msg(B,A);lpdbg("namedpipes","broadcasting "+C);
g_nplastpass.SendNamedPipeMessageToAll(C)}function lpnp_xml_msg(C,A){var D="<"+C;var B;if(typeof(A)!="undefined"){for(B in A){D+=" "+B+'="'+lpxmlescape(A[B])+'"'}}D+="/>";return D};
