var yubikeysubmit=false;function oninityubikey(){}function onshowyubikey(){document.getElementById("yubikeyotp").value="";setTimeout("document.getElementById('yubikeyotp').focus();",0);yubikeysubmit=false;sendBG({cmd:"turnofficon"})}function onhideyubikey(){if(!yubikeysubmit){sendBG({cmd:"yubikeyauth",otp:""})
}closemole()}function otpcheck(){var D=document.getElementById("lptrustyubi").checked;var B="";if(D){var A=document.getElementById("yubitrustlabel").value;if(A==""){document.getElementById("labelyubi").style.color="red";return}else{B=A}}var C=document.getElementById("yubikeyotp").value;if(C!=""){yubikeysubmit=true;
sendBG({cmd:"yubikeyauth",otp:C,label:B})}onhideyubikey()}function lostkey(){sendBG({cmd:"lostkey"});closemole()}var sesamesubmit=false;function oninitsesame(){}function onshowsesame(){document.getElementById("sesameotplocal").value="";setTimeout("document.getElementById('sesameotplocal').focus();",0);
sesamesubmit=false;sendBG({cmd:"turnofficon"})}function onhidesesame(){if(!sesamesubmit){sendBG({cmd:"sesameauth",otp:""})}closemole()}function sesameotpcheck(){var D=document.getElementById("lptrustsesame").checked;var B="";if(D){var A=document.getElementById("sesametrustlabel").value;if(A==""){document.getElementById("labelsesame").style.color="red";
return}else{B=A}}var C=document.getElementById("sesameotplocal").value;if(C!=""){sesamesubmit=true;sendBG({cmd:"sesameauth",otp:C,label:B})}onhidesesame()}function sesamelostkey(){sendBG({cmd:"sesamelostkey"});closemole()}var gridsubmit=false;function oninitgrid(){}function onshowgrid(){document.getElementById("lpgridinput1").value="";
document.getElementById("lpgridinput2").value="";document.getElementById("lpgridinput3").value="";document.getElementById("lpgridinput4").value="";sendBG({cmd:"turnofficon"});var B=document.location.href;var D=decodeURIComponent(B.substr(B.indexOf("challenge=")+10));D=D.replace(/^\s+|\s+$/g,"");var A=D.split(" ");
for(var C=0;C<A.length;C++){document.getElementById("grid"+(C+1)+"label").innerHTML=A[C]}console.log(D);setTimeout("document.getElementById('lpgridinput1').focus();",0);gridsubmit=false}function onhidegrid(){if(!gridsubmit){sendBG({cmd:"gridauth",gridvalues:""})}closemole()}function gridcheck(){var C=document.getElementById("lptrustgrid").checked;
var B="";if(C){var A=document.getElementById("gridtrustlabel").value;if(A==""){document.getElementById("labelgrid").style.color="red";return}else{B=A}}var D="";if(document.getElementById("lpgridinput1").value!=""&&document.getElementById("lpgridinput2").value!=""&&document.getElementById("lpgridinput3").value!=""&&document.getElementById("lpgridinput4").value!=""){D=document.getElementById("lpgridinput1").value+","+document.getElementById("lpgridinput2").value+","+document.getElementById("lpgridinput3").value+","+document.getElementById("lpgridinput4").value
}if(D!=""){gridsubmit=true;sendBG({cmd:"gridauth",gridvalues:D,label:B})}onhidegrid()}function lostgrid(){sendBG({cmd:"gridlostkey"});closemole()};
