function lpPutUserPref(A,B){g_userprefs[A]=B}function lpPutGblPref(A,B){g_gblprefs[A]=B}function lpGetPref(A,B){if(typeof(g_userprefs[A])!="undefined"){return g_userprefs[A]}if(typeof(g_gblprefs[A])!="undefined"){return g_gblprefs[A]}return B}function lpReadAllPrefs(C){var B=g_username_hash&&g_username_hash!=""?g_username_hash:"";
g_userprefs=new Array();g_identity="";var A=opendb();createPrefsTable(A);if(A){A.transaction(function(D){D.executeSql("SELECT * FROM LastPassPreferences where username_hash=? or username_hash=?",[B,""],function(F,G){g_gblprefs=new Array();for(var I=0;I<G.rows.length;I++){var E=G.rows.item(I)["username_hash"];
var H=G.rows.item(I)["prefname"];var J=G.rows.item(I)["prefvalue"];if(E!=""){g_userprefs[H]=J;if(H=="identity"){g_identity=J}}else{g_gblprefs[H]=J}}start_idle_checker();if(typeof(g_gblprefs.generateHkKeyCode)=="undefined"){setup_default_hotkeys()}console.log("read: "+G.rows.length+" preferences");if(C){C(G.rows.length)
}},function(E,F){console.log(F)})})}else{if(C){C()}}}function setup_default_hotkeys(){if(g_is_mac){lpPutGblPref("generateHkKeyCode",0);lpPutGblPref("generateHkMods","");lpPutGblPref("recheckHkKeyCode",0);lpPutGblPref("recheckHkMods","");lpPutGblPref("searchHkKeyCode",0);lpPutGblPref("searchHkMods","");
lpPutGblPref("nextHkKeyCode",33);lpPutGblPref("nextHkMods","meta");lpPutGblPref("prevHkKeyCode",34);lpPutGblPref("prevHkMods","meta");lpPutGblPref("homeHkKeyCode",0);lpPutGblPref("homeHkMods","")}else{lpPutGblPref("generateHkKeyCode",71);lpPutGblPref("generateHkMods","alt");lpPutGblPref("recheckHkKeyCode",73);
lpPutGblPref("recheckHkMods","alt");lpPutGblPref("searchHkKeyCode",87);lpPutGblPref("searchHkMods","alt");lpPutGblPref("nextHkKeyCode",33);lpPutGblPref("nextHkMods","alt");lpPutGblPref("prevHkKeyCode",34);lpPutGblPref("prevHkMods","alt");lpPutGblPref("homeHkKeyCode",72);lpPutGblPref("homeHkMods","control alt")
}lpPutGblPref("submitHkKeyCode",0);lpPutGblPref("submitHkMods","");lpPutGblPref("saveallHkKeyCode",0);lpPutGblPref("saveallHkMods","");lpPutGblPref("logoffHkKeyCode",0);lpPutGblPref("logoffHkMods","");lpWriteAllPrefs()}function lpWriteAllPrefs(){var A=opendb();createPrefsTable(A);if(A){A.transaction(function(B){if(g_username_hash!=null&&g_username_hash!=""){for(var C in g_userprefs){B.executeSql("REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES (?, ?, ?)",[g_username_hash,C,g_userprefs[C]],function(D,E){},function(D,E){console.log(E)
})}}for(var C in g_gblprefs){B.executeSql("REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES (?, ?, ?)",["",C,g_gblprefs[C]],function(D,E){},function(D,E){console.log(E)})}})}}optionsData=new Array();optionsData.HotKeys=new Array();function capturehk(C,B){var A="";A+=(B.ctrlKey?"control":"");
A+=(B.metaKey?(A!=""?" ":"")+"meta":"");A+=(B.altKey?(A!=""?" ":"")+"alt":"");A+=(B.shiftKey?(A!=""?" ":"")+"shift":"");if(A==""||A=="shift"){A=getBG().g_is_mac?"meta":"alt"}if(B.keyCode==8||B.keyCode==127||B.keyCode==46){optionsData.HotKeys[C+"KeyCode"]=0}else{if(B.keyCode<=32||B.keyCode==91){return
}else{if(B.keyCode!=0){optionsData.HotKeys[C+"KeyCode"]=B.keyCode}else{optionsData.HotKeys[C+"KeyCode"]=B.charCode}}}optionsData.HotKeys[C+"Mods"]=A;writeHotKeyValue(C)}function writeHotKeyValue(D){var B=optionsData.HotKeys[D+"KeyCode"];var C=document.getElementById(D);var G="";if(B!=0){var A=optionsData.HotKeys[D+"Mods"];
if(typeof(A)!="string"){A=""}var F=A.split(" ");for(var E in F){if(F[E]=="control"){G+=gs("Ctrl")+"+"}if(F[E]=="meta"){G+=gs("Meta")+"+"}if(F[E]=="alt"){G+=gs("Alt")+"+"}if(F[E]=="shift"){G+=gs("Shift")+"+"}}}if(B!=0){if(B==33){G+=gs("Page Up")}else{if(B==34){G+=gs("Page Down")}else{if(B==35){G+=gs("End")
}else{if(B==36){G+=gs("Home")}else{if(B==37){G+=gs("Left")}else{if(B==38){G+=gs("Up")}else{if(B==39){G+=gs("Right")}else{if(B==40){G+=gs("Down")}else{G+=String.fromCharCode(B).toUpperCase()}}}}}}}}C.value=G}else{C.value=""}}function fixhk(B,A){if(optionsData.HotKeys[B+"KeyCode"]<32){optionsData.HotKeys[B+"Mods"]="";
writeHotKeyValue(B)}A.cancelBubble=true;A.stopPropagation()}var last_idle_check=0;function start_idle_checker(){if(last_idle_check==0){var A=parseInt(lpGetPref("idleLogoffVal",0));if(A>0){last_idle_check=lp_get_gmt_timestamp();setTimeout("idle_checker();",10000)}}}function idle_checker(){var B=parseInt(lpGetPref("idleLogoffVal",0));
if(B>0){var C=0;if(have_nplastpass()&&typeof(g_nplastpass.get_idle_ms)=="function"){C=g_nplastpass.get_idle_ms()}idlesecs=parseInt(C/1000);var A=B*60;var D=lp_get_gmt_timestamp();if(A!=0&&((A<idlesecs||(A<D-last_idle_check)))){lplogoff_if()}last_idle_check=D}setTimeout("idle_checker();",10000)};
