var g_toolstripid=get_random(0,999999999);var g_moles={};var g_curmole=null;var g_newmole=null;var g_changepwnewpw="";var g_changepwtld="";var g_browseraction=document.location.href.indexOf("?browseraction=1")!=-1;var g_yubikey=document.location.href.indexOf("&yubikey=1")!=-1;var g_sesame=document.location.href.indexOf("&sesame=1")!=-1;
var g_grid=document.location.href.indexOf("&grid=1")!=-1;var g_generate=document.location.href.indexOf("&generate=1")!=-1;var g_chooseprofilecc=document.location.href.indexOf("&chooseprofilecc=1")!=-1;var g_changepw=document.location.href.indexOf("&changepw=1")!=-1;var g_generate_url="";if(g_generate){g_generate_url=getBG().g_generate_url;
getBG().g_generate_url=""}if(g_changepw){g_changepwnewpw=getBG().g_changepwnewpw;g_changepwtld=getBG().g_changepwtld}var g_generate_found=false;var g_tabid=null;var matches=document.location.href.match(/&tabid=(\d+)/);if(matches){g_tabid=matches[1]}function onLoad(){L("TS["+g_toolstripid+"] : loaded");
sendBG({cmd:"getloginstate"});g_curmole="lpbutton";addmole("lpbutton");addmole("lpmenu",onheightmenu,oninitmenu,onshowmenu,onhidemenu);addmole("lpnotify",80,oninitnotify,onshownotify);addmole("lpgenerate",300,oninitgenerate,onshowgenerate,onhidegenerate);addmole("lpchooseprofilecc",300,oninitchooseprofilecc,onshowchooseprofilecc,onhidechooseprofilecc);
addmole("lpchangepw",300,oninitchangepw,onshowchangepw,onhidechangepw);addmole("lpyubikey",350,oninityubikey,onshowyubikey,onhideyubikey);addmole("lpsesame",350,oninitsesame,onshowsesame,onhidesesame);addmole("lpgrid",350,oninitgrid,onshowgrid,onhidegrid);var A;for(A in g_moles){if(A!="lpbutton"||g_browseraction){$("#"+A).hide()
}if(typeof(g_moles[A]["initfunc"])=="function"){g_moles[A]["initfunc"]()}}if(g_browseraction){if(g_yubikey){openmole("lpyubikey")}else{if(g_sesame){openmole("lpsesame")}else{if(g_grid){openmole("lpgrid")}else{if(g_generate){openmole("lpgenerate")}else{if(g_chooseprofilecc){openmole("lpchooseprofilecc")
}else{if(g_changepw){openmole("lpchangepw")}else{if(getBG().g_badgedata!=null){receiveBG(getBG().g_badgedata);getBG().clear_badge()}else{openmenu()}}}}}}}}}function onUnload(){if(typeof(g_moles[g_curmole]["hidefunc"])=="function"){g_moles[g_curmole]["hidefunc"]()}}function sendBG(B){try{var A=getBG();
if(A){L("TS -> BG : cmd="+B.cmd);return A.receiveTS(g_toolstripid,B)}L("TS -> BG : FAILED")}catch(C){L("TS -> BG : FAILED error="+C)}return null}function receiveBG(B){if(typeof(B.cmd)=="undefined"){L("BG -> TS : INVALIDMSG");return}L("BG -> TS : "+B.cmd);switch(B.cmd){case"login":$("#lpicon").attr("src","icon.gif");
$("#lploggedin").show();$("#lplogin").hide();break;case"logoff":if(g_curmole=="lpmenu"){closemole()}$("#lpicon").attr("src","icon_gray.gif");$("#lploggedin").hide();$("#lplogin").show();break;case"genpw":openmole("lpgenerate");break;case"chooseprofilecc":openmole("lpchooseprofilecc");break;case"changepw":g_changepwnewpw=B.newpw;
g_changepwtld=B.tld;openmole("lpchangepw");break;case"yubikey":openmole("lpyubikey");break;case"sesame":openmole("lpsesame");break;case"notification":var A=B.type;if(getBG().lpGetPref("showNotifications",1)!=0||A=="error"||A=="upgrade"){openmole("lpnotify")}break;default:L("BG -> TS : INVALIDMSG");return;
break}}function isloggedin(){return getBG().lploggedin}function openmenu(){if(!isloggedin()){closemole();getBG().open_login(true);return}openmole("lpmenu")}function addmole(E,A,C,D,B){g_moles[E]={height:A,initfunc:C,showfunc:D,hidefunc:B}}function hidemenu(){$("#menucontainer").hide()}function hidemoles(){var A;
for(A in g_moles){if(A!="lpbutton"||g_browseraction){$("#"+A).hide()}}}function closemole(){if(g_browseraction){window.close()}else{$("#body").css("background","");g_newmole=null;if(g_curmole=="lpbutton"){return}chrome.toolstrip.collapse({})}}function openmole(B){if(g_browseraction){hidemoles()}else{closemole()
}$("#content").show();g_newmole=B;if(B=="lpbutton"){$("#lpbutton").show();if(typeof(g_moles.lpbutton["showfunc"])=="function"){g_moles.lpbutton["showfunc"]()}}else{if(g_curmole=="lpbutton"){$("#lpbutton").hide();if(typeof(g_moles.lpbutton["hidefunc"])=="function"){g_moles.lpbutton["hidefunc"]()}chrome.tabs.getSelected(null,function(D){getBG().setcurrenttabid(D.id);
getBG().setcurrenturl(D.url);if(g_browseraction){toolstrip_expanded()}else{var C=typeof(g_moles[g_newmole]["height"])=="function"?g_moles[g_newmole]["height"]():g_moles[g_newmole]["height"];chrome.toolstrip.expand({height:C})}})}else{if(g_browseraction){toolstrip_expanded()}else{var A=typeof(g_moles[g_newmole]["height"])=="function"?g_moles[g_newmole]["height"]():g_moles[g_newmole]["height"];
chrome.toolstrip.expand({height:A})}}}}if(!g_browseraction){chrome.toolstrip.onCollapsed.addListener(function(){L("TS: collapsing mole="+g_curmole);if(typeof(g_moles[g_curmole]["hidefunc"])=="function"){g_moles[g_curmole]["hidefunc"]()}$("#"+g_curmole).hide();g_curmole="lpbutton";$("#lpbutton").show();
if(typeof(g_moles.lpbutton["showfunc"])=="function"){g_moles.lpbutton["showfunc"]()}});chrome.toolstrip.onExpanded.addListener(toolstrip_expanded)}function toolstrip_expanded(){g_curmole=g_newmole;g_newmole=null;if(typeof(g_moles[g_curmole]["showfunc"])=="function"){g_moles[g_curmole]["showfunc"]()}$("#"+g_curmole).show()
};
